#!/usr/bin/env python3
"""RPCS3-only Universal JIT stop-reply repair; retains both emulator cores.

Generate a private script from the pinned, already patched StikJIT universal
script. Other emulators keep their original script selection and resources.
Apply after the native Build 270 transport patch. No entitlement changes.
"""
from pathlib import Path
import argparse

ROOT = Path(__file__).resolve().parents[1]
MARKER = 'NEOSTATION_RPCS3_STOP_REPLY_270'


def replace(text, old, new):
    if new in text:
        return text
    if text.count(old) != 1:
        raise RuntimeError(f'Build 270 source drift ({text.count(old)} matches): {old[:90]}')
    return text.replace(old, new, 1)


def change(relative, old, new):
    path = ROOT / relative
    path.write_text(replace(path.read_text(), old, new))


UTILITIES = r'''
// NEOSTATION_RPCS3_STOP_REPLY_270: every resume reply is an event, not an ACK.
function requireStopReply(reply, phase) {
    if (typeof reply !== 'string' || !/^[TS][0-9a-fA-F]{2}/.test(reply)) {
        const detail = typeof reply === 'string' ? reply.slice(0, 160) : '<absent>';
        throw new Error(`NEOSTATION_RPCS3_STOP_REPLY_270: ${phase}: invalid/terminal stop reply ${detail}`);
    }
    return reply;
}

function stopThread(reply) {
    // Debugserver may put metype/mecount/name before thread, or omit registers.
    const match = /(?:^T[0-9a-fA-F]{2}|;)thread:([0-9a-fA-F]+|p[0-9a-fA-F]+\.[0-9a-fA-F]+);/.exec(reply);
    if (match) return match[1];
    const current = send_command('qC');
    const fallback = /^QC([0-9a-fA-F]+|p[0-9a-fA-F]+\.[0-9a-fA-F]+)$/.exec(current);
    if (!fallback) throw new Error('NEOSTATION_RPCS3_STOP_REPLY_270: missing stopped thread');
    return fallback[1];
}

function stopRegister(reply, index, thread) {
    const expression = new RegExp(`(?:^T[0-9a-fA-F]{2}|;)${index}:([0-9a-fA-F]{16});`);
    const match = expression.exec(reply);
    const value = match ? match[1] : send_command(`p${index};thread:${thread};`);
    if (!/^[0-9a-fA-F]{16}$/.test(value))
        throw new Error(`NEOSTATION_RPCS3_STOP_REPLY_270: unreadable register ${index}`);
    return littleEndianHexStringToNumber(value);
}

function requireOK(reply, phase) {
    if (reply !== 'OK') throw new Error(`NEOSTATION_RPCS3_STOP_REPLY_270: ${phase} rejected: ${String(reply).slice(0, 80)}`);
}
'''


def protocol_script(source):
    if MARKER in source:
        return source
    if 'NEOSTATION_STIKJIT_UNIVERSAL_V1' not in source:
        raise RuntimeError('Apply the existing full-width/page-reply StikJIT patch first')
    source = replace(source, 'let totalBreakpoints = 0;', '''requireStopReply(attachResponse, 'attach');
let pendingStopReply = null;
let pendingWasStep = false;
let totalBreakpoints = 0;''')
    source = replace(source, '''    let brkResponse = send_command(`c`);
    log_verbose(`brkResponse = ${brkResponse}`);''', '''    const fromSignalStep = pendingWasStep;
    const brkResponse = requireStopReply(
        pendingStopReply === null ? send_command(`c`) : pendingStopReply, 'resume');
    pendingStopReply = null;
    pendingWasStep = false;
    log(`NEOSTATION_RPCS3_STOP_REPLY_270: stop ${totalBreakpoints}: ${brkResponse.slice(0, 240)}`);''')
    start = source.index('    // extract tid, pc, x16\n')
    end = source.index('    let instructionResponse', start)
    source = source[:start] + '''    tid = stopThread(brkResponse);
    pc = stopRegister(brkResponse, '20', tid);
    x16 = stopRegister(brkResponse, '10', tid);
    const stopSignal = brkResponse.slice(1, 3).toLowerCase();

''' + source[end:]
    source = replace(source, '''        if (continuesWithSignal) {''', '''        // A single-step's SIGTRAP is generated by the debugger, not the app.
        if (fromSignalStep && stopSignal === '05') continue;
        if (continuesWithSignal) {''')
    source = replace(source, '''            let signum = /^T(?<sig>[a-z0-9;]{2})/.exec(brkResponse);
            signum = signum ? signum.groups['sig'] : null;
            if (!signum) {
                log(`Failed to extract signal number: ${signum}`);
                continue;
            }''', '''            const signum = stopSignal;''')
    source = replace(source, '''            send_command(`vCont;S${signum}:${tid}`);''', '''            // vCont replies with the NEXT stop. Do not discard it and send c:
            // that skips a JIT BRK and can leave the arena unprepared.
            pendingStopReply = send_command(`vCont;S${signum}:${tid}`);
            pendingWasStep = true;''')
    start = source.index('        // when we find a valid brk immediate command, parse x0 and x1\n')
    end = source.index('        // jump over brk', start)
    source = source[:start] + '''        x0 = stopRegister(brkResponse, '00', tid);
        x1 = stopRegister(brkResponse, '01', tid);

''' + source[end:]
    source = replace(source, '        log(`pcPlus4Response = ${pcPlus4Response}`);',
                     '        log(`pcPlus4Response = ${pcPlus4Response}`);\n        requireOK(pcPlus4Response, "advance BRK");')
    source = replace(source, '''        log(`Skipping breakpoint: brk immediate 0x${brkImmediate.toString(16)} was not handled by this script. You could add it by evaluating legacyCommands[0x${brkImmediate.toString(16)}] = yourFunction;`);
        continue;''', '''        throw new Error(`NEOSTATION_RPCS3_STOP_REPLY_270: unsupported BRK 0x${brkImmediate.toString(16)}`);''')
    source = replace(source, '''    log_verbose(`detachResponse = ${detachResponse}`);
    detached = true;''', '''    log_verbose(`detachResponse = ${detachResponse}`);
    requireOK(detachResponse, 'detach');
    detached = true;
    log('NEOSTATION_RPCS3_STOP_REPLY_270: detach confirmed');''')
    source = replace(source, '''        log(`Unknown command ${x16.toString(16)}`);
        return;''', '''        throw new Error(`NEOSTATION_RPCS3_STOP_REPLY_270: unknown JIT command ${x16.toString(16)}`);''')
    source = replace(source, '''    let jitPageAddress = x0;
    if (x0 == 0n) {''', '''    // JavaScriptCore's native prepare bridge converts BigInt to Double.
    // Reject unrepresentable values rather than silently changing an address.
    if (x0 < 0n || x0 > BigInt(Number.MAX_SAFE_INTEGER) || x1 <= 0n ||
        x1 > BigInt(Number.MAX_SAFE_INTEGER) || x0 + x1 > BigInt(Number.MAX_SAFE_INTEGER))
        throw new Error('NEOSTATION_RPCS3_STOP_REPLY_270: invalid JIT region');
    log(`NEOSTATION_RPCS3_STOP_REPLY_270: prepare begin address=0x${x0.toString(16)} bytes=${x1}`);
    let jitPageAddress = x0;
    if (x0 == 0n) {''')
    source = replace(source, '''        if (!requestRXResponse || requestRXResponse.length === 0) {
            log(`Failed to allocate RX memory`);
            return;
        }''', '''        if (!/^[0-9a-fA-F]+$/.test(requestRXResponse)) {
            requireOK(send_command(`P0=${numberToLittleEndianHexString(0n)};thread:${tid};`), 'allocation failure return');
            log('NEOSTATION_RPCS3_STOP_REPLY_270: RX allocation refused');
            return;
        }''')
    source = replace(source, '''        log(`putFailureX0Response = ${putFailureX0Response}`);
        return;''', '''        log(`putFailureX0Response = ${putFailureX0Response}`);
        requireOK(putFailureX0Response, 'preparation failure return');
        return;''')
    # Only the active function, not the upstream commented example.
    start = source.index('function JIT26PrepareRegion(')
    end = source.index('// utilities', start)
    handler = source[start:end]
    handler = replace(handler, '    log(`putX0Response = ${putX0Response}`);',
                      '''    log(`putX0Response = ${putX0Response}`);
    requireOK(putX0Response, 'prepared address return');
    log(`NEOSTATION_RPCS3_STOP_REPLY_270: prepare complete address=0x${jitPageAddress.toString(16)} bytes=${x1}`);''')
    source = source[:start] + handler + source[end:]
    source = replace(source, '''function littleEndianHexToU32(hexStr) {
    return parseInt''', '''function littleEndianHexToU32(hexStr) {
    if (typeof hexStr !== 'string' || !/^[0-9a-fA-F]{8}$/.test(hexStr))
        throw new Error('NEOSTATION_RPCS3_STOP_REPLY_270: invalid instruction response');
    return parseInt''')
    source += '\n' + UTILITIES
    return source


def host():
    helper = 'packages/rpcs3_jit_helper/ios/Classes/Rpcs3JITRequestHandlerBase.swift'
    change(helper, '      try StikJIT.enableJIT(\n', '''      // Only RPCS3 opts into the stop-reply repair. Other emulators are unchanged.
      let selectedScript: StikJIT.Script
      if requiresCoreHandshake {
        guard let framework = Bundle(identifier: "com.stik.StikJIT"),
              let scriptURL = framework.url(forResource: "rpcs3-universal", withExtension: "js") else {
          throw Rpcs3HelperError.invalidRequest("The RPCS3 JIT protocol resource is missing.")
        }
        selectedScript = .custom(scriptURL)
        try reporter?.send(event: "log", message: "NEOSTATION_RPCS3_STOP_REPLY_270: dedicated protocol selected.")
      } else {
        selectedScript = .universal
      }
      try StikJIT.enableJIT(
''')
    change(helper, '        script: .universal,', '        script: selectedScript,')
    change(helper, '    guard reply.count >= 3, reply.first == "T" else { return false }',
           '    guard reply.count >= 3, reply.first == "T" || reply.first == "S" else { return false }')
    change('test/rpcs3_internal_integration_test.dart',
           "      expect(helper, contains('script: .universal'));",
           "      expect(helper, contains('script: selectedScript'));\n"
           "      expect(helper, contains('selectedScript = .custom(scriptURL)'));\n"
           "      expect(helper, contains('selectedScript = .universal'));\n"
           "      expect(helper, contains('forResource: \"rpcs3-universal\"'));")
    change('build-utils/reuse_build266_rpcs3_for267.py', 'ALLOWED = {',
           "ALLOWED = {\n    'build-utils/patch_rpcs3_stop_reply270.py',\n    'test/rpcs3_stop_reply270_test.py',")
    print('RPCS3-only stop-reply protocol selected; native transport diagnostics retained.')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--stik-source', type=Path)
    args = parser.parse_args()
    if args.stik_source:
        resource = args.stik_source / 'Resources'
        original = (resource / 'universal.js').read_text()
        (resource / 'rpcs3-universal.js').write_text(protocol_script(original))
        print('Generated dedicated RPCS3 stop-reply script; original universal.js unchanged.')
    else:
        host()
