#!/usr/bin/env python3
"""Patch the pinned Dolphin into a strict, process-local NeoStation engine."""
from __future__ import annotations
import argparse
from pathlib import Path

BRIDGE_SOURCE = r'''// Generated by NeoStation. SPDX-License-Identifier: GPL-2.0-or-later
#if !__has_feature(objc_arc)
#error NeoStationBridge.mm requires ARC for Foundation objects captured by host queue blocks.
#endif
#import <Foundation/Foundation.h>
#import <Metal/Metal.h>
#import <QuartzCore/CAMetalLayer.h>
#import <libkern/OSCacheControl.h>
#import <mach/mach.h>
#import <mach/vm_map.h>
#import <mach/vm_region.h>
#import <sys/mman.h>
#include <algorithm>
#include <atomic>
#include <chrono>
#include <cstdint>
#include <cstring>
#include <vector>
#include <fstream>
#include <memory>
#include <map>
#include <mutex>
#include <optional>
#include <set>
#include <string>
#include <thread>
#include "Common/FileUtil.h"
#include "Common/MemoryUtil.h"
#include "Common/MsgHandler.h"
#include "Common/WindowSystemInfo.h"
#include "Core/Boot/Boot.h"
#include "Core/BootManager.h"
#include "Core/CPUThreadConfigCallback.h"
#include "Core/IOS/ES/ES.h"
#include "Core/IOS/IOS.h"
#include "Core/IOS/FS/FileSystem.h"
#include "Core/Config/GraphicsSettings.h"
#include "Core/Config/MainSettings.h"
#include "Core/Config/SYSCONFSettings.h"
#include "Core/Config/WiimoteSettings.h"
#include "Core/ConfigLoaders/BaseConfigLoader.h"
#include "Core/ConfigManager.h"
#include "Core/Core.h"
#include "Core/DolphinAnalytics.h"
#include "Core/HW/GCPad.h"
#include "Core/HW/Wiimote.h"
#include "InputCommon/InputConfig.h"
#include "InputCommon/ControllerInterface/iOS/StateManager.h"
#include "InputCommon/ControllerEmu/ControllerEmu.h"
#include "InputCommon/ControllerEmu/ControlGroup/Attachments.h"
#include "Core/PowerPC/JitInterface.h"
#include "Core/PowerPC/PowerPC.h"
#include "Core/State.h"
#include "Core/System.h"
#include "DiscIO/Enums.h"
#include "DiscIO/Volume.h"
#include "UICommon/UICommon.h"
#include "VideoCommon/Present.h"
#include "VideoCommon/VideoConfig.h"
#include "HostQueue.h"

namespace
{
std::mutex g_state_mutex;
std::atomic<bool> g_initialized{false};
std::atomic<bool> g_jit_handshake{false};
std::atomic<bool> g_executable_probe{false};
std::atomic<bool> g_running{false};
std::atomic<bool> g_cleanup_started{false};
std::atomic<bool> g_arena_established{false};
std::string g_user_directory;
std::string g_system_directory;
std::string g_validated_game;
std::string g_validated_system;
bool g_validated_wii_menu = false;
std::string g_log_path;
void* g_metal_surface = nullptr;
double g_metal_scale = 1.0;
std::atomic<bool> g_devices_changed{true};
std::optional<ControllerInterface::HotplugCallbackHandle> g_devices_callback;
void ConfigurePhysicalControllers();
void ApplyConsolePreferences();
void ApplyGraphicsPreferences();
void ResetInputProfiles();
std::atomic<int> g_boot_language{-1};

void Log(const std::string& stage, const std::string& message)
{
  const std::string path = g_log_path;
  if (path.empty()) return;
  std::ofstream out(path, std::ios::app);
  if (!out) return;
  const auto now = std::chrono::duration_cast<std::chrono::milliseconds>(
      std::chrono::system_clock::now().time_since_epoch()).count();
  out << "{\"timestampMs\":" << now << ",\"engine\":\"dolphin_internal\""
      << ",\"stage\":\"" << stage << "\",\"message\":\"";
  for (const unsigned char character : message)
  {
    switch (character)
    {
    case '\\': out << "\\\\"; break;
    case '"': out << "\\\""; break;
    case '\n': out << "\\n"; break;
    case '\r': out << "\\r"; break;
    case '\t': out << "\\t"; break;
    default: if (character >= 32) out << character; break;
    }
  }
  out << "\"}\n";
  out.flush();
}

bool ExpectedPlatform(DiscIO::Platform platform, const std::string& system)
{
  if (system == "gc") return platform == DiscIO::Platform::GameCubeDisc;
  if (system == "wii") return platform == DiscIO::Platform::WiiDisc || platform == DiscIO::Platform::WiiWAD;
  return false;
}

bool WaitForCoreToLeaveStarting(std::chrono::seconds timeout)
{
  const auto deadline = std::chrono::steady_clock::now() + timeout;
  auto& system = Core::System::GetInstance();
  while (Core::GetState(system) == Core::State::Starting && std::chrono::steady_clock::now() < deadline)
    std::this_thread::sleep_for(std::chrono::milliseconds(25));
  return Core::GetState(system) != Core::State::Starting;
}

void ResetSessionFlags()
{
  g_jit_handshake = false;
  g_executable_probe = false;
  g_running = false;
  g_validated_game.clear();
  g_validated_system.clear();
  g_validated_wii_menu = false;
  g_metal_surface = nullptr;
  g_metal_scale = 1.0;
  g_boot_language = -1;
}

void ShutdownRuntime(const char* reason)
{
  // All lifecycle entries run on the dedicated serial Dolphin queue. Never
  // release Metal after a timeout while the emulation thread still owns it.
  if (!g_initialized || g_cleanup_started.exchange(true)) return;
  g_running = false;
  Log("cleanup.begin", reason == nullptr ? "cleanup" : reason);
  DOLHostQueueRunSync(^{
    auto& system = Core::System::GetInstance();
    Log("cleanup.core_stop.begin", "Requesting CPU and GPU shutdown.");
    Core::Stop(system);
    Log("cleanup.core_join.begin", "Waiting for the emulation thread.");
    Core::Shutdown(system); // Pinned API joins the real emulation thread.
    Log("cleanup.core_join.complete", "Emulation thread joined; surface can be detached after cleanup.");
    ApplyConsolePreferences();
    Config::Save();
    // UICommon/config/input backends belong to the process, like the upstream
    // frontend. Their callbacks and Core::System singletons survive a game.
    // Destroying them between Wii and GC can leave cross-queue notifications and
    // cached references racing their replacements. Core::Shutdown above still
    // releases all per-game RAM, CPU, GPU, audio and NAND resources.
    ciface::iOS::StateManager::GetInstance()->Init();
    g_devices_changed = true;
  });
  ResetSessionFlags();
  Log("cleanup.complete", "Game joined and released; process input/config services retained for the next console.");
  g_cleanup_started = false;
}

bool HasMemoryPermissions(void* pointer, size_t length, vm_prot_t required)
{
  // iPhoneOS exposes vm_region_64 via vm_map.h; mach_vm.h is unavailable.
  // Only inspect this arm64 process, keeping addresses pointer-sized.
  static_assert(sizeof(vm_address_t) == sizeof(void*), "VM address must preserve pointer width");
  if (pointer == nullptr || length == 0) return false;
  vm_address_t address = reinterpret_cast<vm_address_t>(pointer);
  const vm_address_t requested = address;
  vm_size_t size = 0;
  vm_region_basic_info_data_64_t info{};
  mach_msg_type_number_t count = VM_REGION_BASIC_INFO_COUNT_64;
  mach_port_t object = MACH_PORT_NULL;
  const kern_return_t status = vm_region_64(mach_task_self(), &address, &size,
      VM_REGION_BASIC_INFO_64, reinterpret_cast<vm_region_info_t>(&info), &count, &object);
  if (object != MACH_PORT_NULL) mach_port_deallocate(mach_task_self(), object);
  return status == KERN_SUCCESS && count == VM_REGION_BASIC_INFO_COUNT_64 &&
      address <= requested && size >= length &&
      requested - address <= size - length && (info.protection & required) == required;
}

bool SelectRegionalIPL(const std::string& game_path)
{
  if (g_validated_system != "gc") return true;
  auto volume = DiscIO::CreateVolume(game_path);
  if (!volume) return false;
  const std::string region = Config::GetDirectoryForRegion(volume->GetRegion());
  const std::string ipl_path = Config::GetBootROMPath(region);
  if (!File::Exists(ipl_path))
  {
    Config::SetBase(Config::MAIN_SKIP_IPL, true);
    Log("ipl.not_installed", "No matching regional IPL; use normal Dolphin HLE boot, not a CPU interpreter fallback.");
    return true;
  }
  std::ifstream stream(ipl_path, std::ios::binary | std::ios::ate);
  constexpr size_t size = 2 * 1024 * 1024;
  if (!stream || stream.tellg() != static_cast<std::streamoff>(size))
  {
    Log("ipl.rejected", "Installed regional IPL has an invalid size.");
    return false;
  }
  std::vector<unsigned char> data(size);
  stream.seekg(0);
  if (!stream.read(reinterpret_cast<char*>(data.data()), size)) return false;
  const std::string header(reinterpret_cast<const char*>(data.data()), 0x100);
  uint32_t crc = 0xffffffff;
  for (unsigned char byte : data)
  {
    crc ^= byte;
    for (int bit = 0; bit < 8; ++bit)
      crc = (crc >> 1) ^ (0xedb88320U & (0U - (crc & 1)));
  }
  crc ^= 0xffffffff;
  const bool pal = crc == 0x4f319f43 || crc == 0xad1b7f16;
  const bool ntsc = crc == 0x6dac1f2a || crc == 0xd5e6feea || crc == 0xd235e3f9 ||
                    crc == 0x86573808 || crc == 0x667d0b64;
  if (header.find("Nintendo") == std::string::npos || header.find("ArtX Inc.") == std::string::npos ||
      !(region == "EUR" ? pal : ntsc))
  {
    Log("ipl.rejected", "Installed IPL failed Nintendo/ArtX, full-content CRC or region-family validation.");
    return false;
  }
  Config::SetBase(Config::MAIN_SKIP_IPL, false);
  Log("ipl.accepted", "Validated regional IPL selected: " + region);
  return true;
}

bool RunExecutableProbe()
{
#if !defined(__aarch64__)
  Log("jit.executable_probe_failed", "Executable probe requires arm64.");
  return false;
#else
  Common::SetJitType(Common::JitType::LuckTXM);
  const bool existing_arena = g_arena_established.load();
  if (!existing_arena)
  {
    Log("jit.legacy_handshake_started", "Entering the pinned Dolphin arena BRK #0x69 protocol.");
    Common::AllocateExecutableMemoryRegion();
  }
  constexpr std::size_t probe_size = 0x4000;
  void* rx = Common::AllocateExecutableMemory(probe_size);
  if (rx == nullptr || rx == MAP_FAILED)
  {
    Log("jit.executable_probe_failed", "Dolphin returned no RX probe page.");
    return false;
  }
  if (existing_arena)
  {
    // The upstream arena initializer returns early after its first invocation.
    // Every new helper still needs a fresh transaction, not a cached attach bit.
    Log("jit.legacy_handshake_started", "Fresh legacy transaction for a page in the existing arena.");
    asm volatile("mov x0, %0\nmov x1, %1\nbrk #0x69" : : "r"(rx), "r"(probe_size) : "x0", "x1", "memory");
  }
  const std::ptrdiff_t writable_difference = Common::AllocateWritableRegionAndGetDiff(rx, probe_size);
  if (writable_difference == 0)
  {
    Log("jit.executable_probe_failed", "Dolphin returned no writable alias.");
    return false;
  }
  auto* rw = reinterpret_cast<std::uint32_t*>(reinterpret_cast<std::uint8_t*>(rx) + writable_difference);
  if (!HasMemoryPermissions(rx, 8, VM_PROT_READ | VM_PROT_EXECUTE) ||
      !HasMemoryPermissions(rw, 8, VM_PROT_READ | VM_PROT_WRITE))
  {
    Log("jit.executable_probe_failed", "The RX page or writable alias lacks required VM protections.");
    Common::FreeExecutableMemory(rx, probe_size);
    return false;
  }
  g_jit_handshake = true;
  g_arena_established = true;
  Log("jit.legacy_handshake_validated", "Legacy breakpoint returned; RX/RW mappings passed VM protection checks.");
  rw[0] = 0x52800540; // mov w0, #42
  rw[1] = 0xD65F03C0; // ret
  sys_dcache_flush(rw, 2 * sizeof(std::uint32_t));
  sys_icache_invalidate(rx, 2 * sizeof(std::uint32_t));
  using Probe = int (*)();
  const int value = reinterpret_cast<Probe>(rx)();
  Common::FreeExecutableMemory(rx, probe_size);
  if (value != 42)
  {
    Log("jit.executable_probe_failed", "Generated ARM64 code returned an unexpected value.");
    return false;
  }
  g_executable_probe = true;
  Log("jit.executable_probe_passed", "Generated ARM64 code executed and returned 42.");
  return true;
#endif
}
} // namespace

// DiscIO metadata works before core/JIT initialization, including RVZ/WBFS/WAD.
// The returned identity is never based on the selected file's display name.
extern "C" __attribute__((visibility("default")))
char* neostation_dolphin_save_identity(const char* game_path, const char* expected_system)
{
  if (!game_path || !expected_system) return nullptr;
  const std::string system(expected_system);
  if (system != "gc" && system != "wii") return nullptr;
  try
  {
    const auto volume = DiscIO::CreateVolume(std::string(game_path));
    if (!volume || !ExpectedPlatform(volume->GetVolumeType(), system)) return nullptr;
    NSString* region = @"unknown";
    switch (volume->GetRegion())
    {
    case DiscIO::Region::NTSC_J: region = @"JAP"; break;
    case DiscIO::Region::NTSC_U: region = @"USA"; break;
    case DiscIO::Region::PAL: region = @"EUR"; break;
    default: break;
    }
    NSMutableDictionary* identity = [@{
      @"system": [NSString stringWithUTF8String:expected_system],
      @"gameId": [NSString stringWithUTF8String:volume->GetGameID().c_str()] ?: @"",
      @"region": region
    } mutableCopy];
    if (const auto title_id = volume->GetTitleID())
      identity[@"titleId"] = [NSString stringWithFormat:@"%016llx", static_cast<unsigned long long>(*title_id)];
    NSData* data = [NSJSONSerialization dataWithJSONObject:identity options:0 error:nil];
    if (!data) return nullptr;
    NSString* json = [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];
    return json ? strdup(json.UTF8String) : nullptr;
  }
  catch (...) { return nullptr; }
}

extern "C" __attribute__((visibility("default")))
int32_t neostation_dolphin_initialize(const char* user_directory, const char* system_directory, const char* log_path)
{
  std::lock_guard<std::mutex> lock(g_state_mutex);
  if (!user_directory || !system_directory || !*user_directory || !*system_directory) return 0;
  if (g_running || g_cleanup_started || !Core::IsUninitialized(Core::System::GetInstance())) return 0;
  if (g_initialized && (g_user_directory != user_directory || g_system_directory != system_directory))
    return 0; // Never repoint process-wide config/input/NAND services at another container.
  g_user_directory = user_directory;
  g_system_directory = system_directory;
  g_log_path = log_path == nullptr ? "" : log_path;
  ResetSessionFlags();
  try
  {
    DOLHostQueueRunSync(^{
      if (!g_initialized)
      {
        UICommon::SetUserDirectory(g_user_directory);
        UICommon::CreateDirectories();
        UICommon::Init();
        WindowSystemInfo controller_wsi;
        controller_wsi.type = WindowSystemType::iOS;
        UICommon::InitControllers(controller_wsi);
        g_devices_callback = g_controller_interface.RegisterDevicesChangedCallback([] {
          // Apple notifications never wait on host/input locks.
          g_devices_changed = true;
        });
        g_initialized = true;
        DolphinAnalytics::Instance().ReportDolphinStart("neostation-ios");
      }
      // Import/NeoSync may have replaced config or NAND files while idle.
      Config::Load();
      ApplyConsolePreferences();
      g_devices_changed = true;
      ConfigurePhysicalControllers();
    });
    Log("core.initialized", "Process services ready; per-game state cleared on the host queue.");
    return 1;
  }
  catch (...)
  {
    Log("core.initialize_failed", "Exception during embedded Dolphin initialization.");
    return 0;
  }
}

extern "C" __attribute__((visibility("default")))
int32_t neostation_dolphin_validate_image(const char* game_path, const char* expected_system, const char* log_path)
{
  if (log_path) g_log_path = log_path;
  if (!g_initialized || g_running || g_cleanup_started || !game_path || !expected_system ||
      !Core::IsUninitialized(Core::System::GetInstance())) return 0;
  g_validated_game.clear();
  g_validated_system.clear();
  g_validated_wii_menu = false;
  const std::string path(game_path), system(expected_system);
  if (system != "gc" && system != "wii")
  {
    Log("image.route_rejected", "Dolphin route is not GameCube/Wii.");
    return 0;
  }
  std::unique_ptr<DiscIO::Volume> volume = DiscIO::CreateVolume(path);
  if (!volume)
  {
    Log("image.open_failed", "DiscIO could not open the selected image.");
    return 0;
  }
  if (!ExpectedPlatform(volume->GetVolumeType(), system))
  {
    Log("image.platform_mismatch", "Image platform does not match the selected playlist.");
    return 0;
  }
  g_validated_game = path;
  g_validated_system = system;
  g_validated_wii_menu = false;
  Log("image.validated", "DiscIO validated the selected GameCube/Wii image.");
  return 1;
}

// Read user-imported NAND metadata with a bound before the upstream parsers.
static std::vector<u8> DOLReadNandMetadata(IOS::HLE::FS::FileSystem& fs,
                                         const std::string& path, size_t maximum)
{
  auto file = fs.OpenFile(0, 0, path, IOS::HLE::FS::Mode::Read);
  if (!file) return {};
  const auto status = file->GetStatus();
  if (!status || status->size == 0 || status->size > maximum) return {};
  std::vector<u8> bytes(status->size);
  if (!file->Read(bytes.data(), bytes.size())) return {};
  return bytes;
}

extern "C" __attribute__((visibility("default")))
int32_t neostation_dolphin_validate_wii_menu(const char* log_path)
{
  if (log_path) g_log_path = log_path;
  if (!g_initialized || g_running || g_cleanup_started ||
      !Core::IsUninitialized(Core::System::GetInstance())) return 0;
  g_validated_game.clear();
  g_validated_system.clear();
  g_validated_wii_menu = false;
  __block bool valid = false;
  DOLHostQueueRunSync(^{
    // A temporary non-emulating IOS instance resolves this container's NAND,
    // including shared contents, exactly like the upstream desktop menu boot.
    IOS::HLE::Kernel ios;
    auto fs = ios.GetFS();
    auto& es = ios.GetESCore();
    const IOS::ES::TMDReader tmd(DOLReadNandMetadata(*fs,
        "/title/00000001/00000002/content/title.tmd", IOS::ES::MAX_TMD_SIZE));
    const IOS::ES::TicketReader ticket(DOLReadNandMetadata(*fs,
        "/ticket/00000001/00000002.tik", 64 * 1024));
    IOS::ES::Content boot_content;
    constexpr u64 menu_title = 0x0000000100000002ULL;
    if (!tmd.IsValid() || tmd.GetTitleId() != menu_title || tmd.GetNumContents() == 0 ||
        !tmd.GetContent(tmd.GetBootIndex(), &boot_content) ||
        !ticket.IsValid() || ticket.GetTitleId() != menu_title) return;
    const u64 ios_id = tmd.GetIOSId();
    if ((ios_id >> 32) != 1 || static_cast<u32>(ios_id) <= 2) return;
    // IOS modules are emulated by Dolphin; an IOS binary is not required.
    valid = es.GetStoredContentsFromTMD(tmd).size() == tmd.GetNumContents();
  });
  if (!valid)
  {
    Log("wii_menu.rejected", "Imported NAND has no complete, bootable Wii System Menu and ticket.");
    return 0;
  }
  g_validated_game.clear();
  g_validated_system = "wii";
  g_validated_wii_menu = true;
  Log("wii_menu.validated", "Installed Wii System Menu metadata, ticket and contents validated.");
  return 1;
}

extern "C" __attribute__((visibility("default")))
int32_t neostation_dolphin_prepare_legacy_jit(const char* log_path)
{
  if (log_path) g_log_path = log_path;
  if (!g_initialized || (g_validated_game.empty() && !g_validated_wii_menu))
  {
    Log("jit.precondition_failed", "Core or image validation is incomplete.");
    return 0;
  }
  bool probe_ok = false;
  try { probe_ok = RunExecutableProbe(); }
  catch (...) { Log("jit.executable_probe_failed", "Exception during executable-memory validation."); }
  int32_t flags = 0;
  if (g_jit_handshake) flags |= 0x1;
  if (probe_ok && g_executable_probe) flags |= 0x2;
  return flags;
}

static int32_t DOLLaunch(const char* game_path, const char* expected_system,
                         void* metal_layer, double metal_scale, const char* log_path,
                         bool wii_menu)
{
  if (log_path) g_log_path = log_path;
  if (!g_initialized || g_running || g_cleanup_started || !Core::IsUninitialized(Core::System::GetInstance()) ||
      !g_jit_handshake || !g_executable_probe || !game_path || !expected_system || !metal_layer)
  {
    Log("launch.precondition_failed", "One or more strict Dolphin launch gates are incomplete.");
    return 0;
  }
  const std::string path(game_path), system_name(expected_system);
  if (path != g_validated_game || system_name != g_validated_system ||
      wii_menu != g_validated_wii_menu || (system_name != "gc" && system_name != "wii"))
  {
    Log("launch.image_changed", "The game or system changed after validation.");
    return 0;
  }
  __block bool booted = false;
  __block WindowSystemInfo wsi;
  wsi.type = WindowSystemType::iOS;
  wsi.render_surface = metal_layer;
  wsi.render_surface_scale = metal_scale > 0.0 ? metal_scale : 1.0;
  g_metal_surface = metal_layer;
  g_metal_scale = wsi.render_surface_scale;
  DOLHostQueueRunSync(^{
    ApplyConsolePreferences();
    ApplyGraphicsPreferences();
    ConfigurePhysicalControllers();
    SConfig::GetInstance().bBootToPause = true;
    Config::SetBase(Config::MAIN_CPU_CORE, PowerPC::CPUCore::JITARM64);
    Config::SetBase(Config::MAIN_GFX_BACKEND, std::string("Metal"));
    Config::SetBase(Config::GFX_VERTEX_LOADER_TYPE, VertexLoaderType::Native);
    if (!SelectRegionalIPL(path)) return;
    // Waiting for cached shaders moves their compilation out of gameplay.
    // Keep the selected resolution and upstream shader mode unchanged.
    Config::SetBase(Config::GFX_SHADER_CACHE, true);
    Config::SetBase(Config::GFX_WAIT_FOR_SHADERS_BEFORE_STARTING, true);
    std::unique_ptr<BootParameters> boot = wii_menu ?
        std::make_unique<BootParameters>(BootParameters::NANDTitle{0x0000000100000002ULL}) :
        BootParameters::GenerateFromFile(path);
    if (boot) booted = BootManager::BootCore(Core::System::GetInstance(), std::move(boot), wsi);
  });
  if (!booted || !WaitForCoreToLeaveStarting(std::chrono::seconds(120)))
  {
    Log("core.boot_failed", "BootManager did not start the selected image.");
    ShutdownRuntime("boot_failed");
    return 0;
  }
  int32_t flags = 0;
  if (Core::IsRunning(Core::System::GetInstance()) &&
      Config::Get(Config::MAIN_CPU_CORE) == PowerPC::CPUCore::JITARM64 &&
      Core::System::GetInstance().GetJitInterface().GetCore() != nullptr &&
      std::strcmp(Core::System::GetInstance().GetPowerPC().GetCPUName(), "JITARM64") == 0)
  {
    flags |= 0x1;
    Log("jit.jitarm64_initialized", "Dolphin reports an initialized JITARM64 CPU core.");
  }
  else Log("jit.jitarm64_failed", "JITARM64 was not initialized; interpreter fallback is blocked.");
  if (g_presenter != nullptr && Core::IsRunning(Core::System::GetInstance()) &&
      Config::Get(Config::MAIN_GFX_BACKEND) == "Metal")
  {
    flags |= 0x2;
    Log("metal.initialized", "Dolphin Metal presenter initialized on NeoStation CAMetalLayer.");
  }
  else Log("metal.initialize_failed", "Dolphin did not create a Metal presenter.");
  if ((flags & 0x3) == 0x3 && Core::IsRunning(Core::System::GetInstance()))
  {
    flags |= 0x4;
    g_boot_language = system_name == "wii" ? static_cast<int>(Config::Get(Config::SYSCONF_LANGUAGE)) : Config::Get(Config::MAIN_GC_LANGUAGE);
    g_running = true;
    Log("game.submitted", "Validated game submitted to the embedded core.");
    DOLHostQueueRunSync(^{ Core::SetState(Core::System::GetInstance(), Core::State::Running); });
    Log("launch.authorized", "JITARM64 and Metal validated while paused; CPU execution now released.");
  }
  else ShutdownRuntime("strict_launch_gate_failed");
  return flags;
}

extern "C" __attribute__((visibility("default")))
int32_t neostation_dolphin_launch(const char* game_path, const char* expected_system,
                                  void* metal_layer, double metal_scale, const char* log_path)
{
  return DOLLaunch(game_path, expected_system, metal_layer, metal_scale, log_path, false);
}

extern "C" __attribute__((visibility("default")))
int32_t neostation_dolphin_launch_wii_menu(void* metal_layer, double metal_scale, const char* log_path)
{
  return DOLLaunch("", "wii", metal_layer, metal_scale, log_path, true);
}

extern "C" __attribute__((visibility("default")))
int32_t neostation_dolphin_is_running(void)
{
  return g_running && Core::IsRunning(Core::System::GetInstance()) ? 1 : 0;
}
extern "C" __attribute__((visibility("default")))
int32_t neostation_dolphin_set_paused(int32_t paused)
{
  if (!g_running) return 0;
  Log("menu.pause.begin", paused ? "Pause requested." : "Resume requested.");
  DOLHostQueueRunSync(^{ Core::SetState(Core::System::GetInstance(), paused ? Core::State::Paused : Core::State::Running); });
  const bool success = Core::GetState(Core::System::GetInstance()) ==
      (paused ? Core::State::Paused : Core::State::Running);
  Log("menu.pause.complete", success ? "State change completed." : "State change rejected.");
  return success ? 1 : 0;
}
namespace
{
struct DOLControlEntry
{
  std::string id;
  std::string group;
  ControllerEmu::Control* control;
};

void DOLCollectControls(ControllerEmu::ControlGroupContainer* container,
                        const std::string& prefix, std::vector<DOLControlEntry>& output)
{
  if (!container) return;
  for (const auto& group : container->groups)
  {
    if (!group) continue;
    const auto group_id = prefix + group->name + "/";
    for (const auto& control : group->controls)
    {
      if (control && control->control_ref && control->control_ref->IsInput())
        output.push_back({group_id + control->name, prefix + group->ui_name, control.get()});
    }
    if (group->type == ControllerEmu::GroupType::Attachments)
    {
      const auto* attachments = static_cast<ControllerEmu::Attachments*>(group.get());
      for (const auto& attachment : attachments->GetAttachmentList())
        DOLCollectControls(attachment.get(), group_id + attachment->GetName() + "/", output);
    }
  }
}

InputConfig* DOLInputConfig(bool wii) { return wii ? Wiimote::GetConfig() : Pad::GetConfig(); }
NSString* DOLString(const std::string& text)
{
  return [NSString stringWithUTF8String:text.c_str()] ?: @"";
}

// NEOSTATION_SESSION_HELPERS

template <typename T>
void DOLSetGraphics(const Config::Info<T>& info, T value)
{
  // Update the current session even when a game INI overrides the base value,
  // and save the user's choice in the normal Dolphin configuration.
  Config::SetBase(info, value);
  Config::SetCurrent(info, value);
}
}

// NEOSTATION_SAVESTATE_HELPERS

// NEOSTATION_PERFORMANCE_HELPERS

extern "C" __attribute__((visibility("default")))
char* neostation_dolphin_menu_snapshot(int32_t wii, int32_t slot)
{
  if (!g_running || slot < -1 || slot > 3) return nullptr;
  Log("menu.snapshot.begin", slot < 0 ? "Console/graphics settings." : "Controller settings.");
  __block char* result = nullptr;
  DOLHostQueueRunSync(^{
    @autoreleasepool {
    @try {
    ConfigurePhysicalControllers();
    auto lock = ControllerEmu::EmulatedController::GetStateLock();
    InputConfig* config = DOLInputConfig(wii != 0);
    auto* controller = config && slot >= 0 && slot < config->GetControllerCount() ? config->GetController(slot) : nullptr;
    if (slot >= 0 && !controller) return;
    std::vector<DOLControlEntry> entries;
    DOLCollectControls(controller, "", entries);
    NSMutableArray* controls = [NSMutableArray array];
    for (const auto& entry : entries)
      [controls addObject:@{@"id": DOLString(entry.id), @"group": DOLString(entry.group),
        @"name": DOLString(entry.control->ui_name),
        @"expression": DOLString(entry.control->control_ref->GetExpression())}];

    NSMutableArray* devices = [NSMutableArray array];
    if (slot >= 0) for (const auto& device : g_controller_interface.GetAllDevices())
    {
      ciface::Core::DeviceQualifier qualifier;
      qualifier.FromDevice(device.get());
      NSMutableArray* inputs = [NSMutableArray array];
      for (const auto* input : device->Inputs())
      {
        const std::string qualified = qualifier.ToString() + ":" + input->GetName();
        if (qualified.find('`') != std::string::npos) continue;
        [inputs addObject:@{@"name": DOLString(input->GetName()),
          @"expression": DOLString("`" + qualified + "`")}];
      }
      [devices addObject:@{@"name": DOLString(qualifier.ToString()), @"inputs": inputs}];
    }
    NSMutableArray* extensions = [NSMutableArray array];
    if (controller) for (const auto& group : controller->groups)
    {
      if (group->type != ControllerEmu::GroupType::Attachments) continue;
      const auto* attachments = static_cast<ControllerEmu::Attachments*>(group.get());
      int index = 0;
      for (const auto& attachment : attachments->GetAttachmentList())
      {
        [extensions addObject:@{@"group": DOLString(group->name), @"index": @(index),
          @"name": DOLString(attachment->GetDisplayName()),
          @"selected": @(index == static_cast<int>(attachments->GetSelectedAttachment()))}];
        ++index;
      }
    }
    NSMutableArray* languages = [NSMutableArray array];
    NSArray* names = @[@"日本語", @"English", @"Deutsch", @"Français", @"Español", @"Italiano", @"Nederlands", @"简体中文", @"繁體中文", @"한국어"];
    const int language = wii ? static_cast<int>(Config::Get(Config::LayerType::Base, Config::SYSCONF_LANGUAGE)) : Config::Get(Config::LayerType::Base, Config::MAIN_GC_LANGUAGE);
    for (int index = 0; index < (wii ? 10 : 6); ++index)
      [languages addObject:@{@"name": names[wii ? index : index + 1], @"value": @(index), @"selected": @(index == language)}];
    NSDictionary* snapshot = @{
      @"console": @{@"language": @(language), @"languages": languages,
        @"restartNeeded": @(language != g_boot_language.load())},
      @"device": controller ? DOLString(controller->GetDefaultDevice().ToString()) : @"",
      @"graphics": @{@"resolution": @(Config::Get(Config::GFX_EFB_SCALE)),
        @"aspect": @(static_cast<int>(Config::Get(Config::GFX_ASPECT_RATIO))),
        @"vsync": @(Config::Get(Config::GFX_VSYNC)),
        @"anisotropy": @(static_cast<int>(Config::Get(Config::GFX_ENHANCE_MAX_ANISOTROPY)))},
      @"controls": controls, @"devices": devices, @"extensions": extensions,
    };
    NSData* json = [NSJSONSerialization dataWithJSONObject:snapshot options:0 error:nil];
    NSString* text = json ? [[NSString alloc] initWithData:json encoding:NSUTF8StringEncoding] : nil;
    // Copy bytes before leaving the host queue/autorelease pool. No Objective-C
    // object crosses this C ABI or depends on a queue's autorelease lifetime.
    if (text.UTF8String) result = strdup(text.UTF8String);
    } @catch (NSException* exception) {
      Log("menu.snapshot.exception", "Could not encode the requested settings.");
    }
    }
  });
  Log("menu.snapshot.complete", result ? "Settings copied." : "Settings unavailable.");
  return result;
}

extern "C" __attribute__((visibility("default")))
int32_t neostation_dolphin_menu_apply(const char* request_json)
{
  if (!g_running || !request_json) return 0;
  NSData* data = [[NSString stringWithUTF8String:request_json] dataUsingEncoding:NSUTF8StringEncoding];
  NSDictionary* request = [NSJSONSerialization JSONObjectWithData:data options:0 error:nil];
  if (![request isKindOfClass:NSDictionary.class]) return 0;
  __block bool success = false;
  DOLHostQueueRunSync(^{
    if ([request[@"kind"] isEqual:@"graphics"])
    {
      const int value = [request[@"value"] intValue];
      NSString* key = request[@"key"];
      if ([key isEqual:@"resolution"] && value >= 1 && value <= 4)
        DOLSetGraphics(Config::GFX_EFB_SCALE, value);
      else if ([key isEqual:@"aspect"] && value >= 0 && value <= 3)
        DOLSetGraphics(Config::GFX_ASPECT_RATIO, static_cast<AspectMode>(value));
      else if ([key isEqual:@"vsync"] && value >= 0 && value <= 1)
        DOLSetGraphics(Config::GFX_VSYNC, value != 0);
      else if ([key isEqual:@"anisotropy"] && value >= -1 && value <= 4)
        DOLSetGraphics(Config::GFX_ENHANCE_MAX_ANISOTROPY, static_cast<AnisotropicFilteringMode>(value));
      else return;
      Common::IniFile preferences;
      preferences.Load(SessionPreferencesPath());
      preferences.GetOrCreateSection("Graphics")->Set([key UTF8String], value);
      if (!preferences.Save(SessionPreferencesPath())) return;
      Config::Save();
      // Config callbacks are normally deferred until CPU execution resumes.
      // Drain them on the actual CPU thread while paused so the renderer's
      // config is updated before acknowledging the user's selection.
      Core::RunOnCPUThread(Core::System::GetInstance(), [] {
        CPUThreadConfigCallback::CheckForConfigChanges();
      }, true);
      Log("graphics.applied", "Internal scale requested=" +
          std::to_string(Config::Get(Config::GFX_EFB_SCALE)) +
          "; renderer=" + std::to_string(g_Config.iEFBScale));
      success = g_Config.iEFBScale == Config::Get(Config::GFX_EFB_SCALE);
      return;
    }
    if ([request[@"kind"] isEqual:@"language"])
    {
      const bool wii = [request[@"wii"] boolValue];
      if (![request[@"value"] isKindOfClass:NSNumber.class]) return;
      const int value = [request[@"value"] intValue];
      if (value < 0 || value > (wii ? 9 : 5)) return;
      Common::IniFile preferences;
      preferences.Load(SessionPreferencesPath());
      preferences.GetOrCreateSection("Console")->Set(wii ? "WiiLanguage" : "GCLanguage", value);
      if (!preferences.Save(SessionPreferencesPath())) return;
      if (wii) DOLSetGraphics(Config::SYSCONF_LANGUAGE, static_cast<u32>(value));
      else DOLSetGraphics(Config::MAIN_GC_LANGUAGE, value);
      Config::Save();
      success = true;
      return;
    }
    const int slot = [request[@"slot"] intValue];
    if (slot < 0 || slot > 3) return;
    const Core::CPUThreadGuard cpu_guard(Core::System::GetInstance());
    auto lock = ControllerEmu::EmulatedController::GetStateLock();
    InputConfig* config = DOLInputConfig([request[@"wii"] boolValue]);
    if (!config || slot >= config->GetControllerCount()) return;
    auto* controller = config->GetController(slot);
    if (!controller) return;
    if ([request[@"kind"] isEqual:@"device"])
    {
      if (![request[@"device"] isKindOfClass:NSString.class]) return;
      success = SelectInputProfile([request[@"wii"] boolValue], slot, [request[@"device"] UTF8String]);
      return;
    }
    if ([request[@"kind"] isEqual:@"binding"])
    {
      if (![request[@"id"] isKindOfClass:NSString.class] ||
          ![request[@"expression"] isKindOfClass:NSString.class]) return;
      const std::string id = [request[@"id"] UTF8String];
      const std::string expression = [request[@"expression"] UTF8String];
      std::vector<DOLControlEntry> entries;
      DOLCollectControls(controller, "", entries);
      for (const auto& entry : entries)
      {
        if (entry.id != id) continue;
        const auto previous = entry.control->control_ref->GetExpression();
        if (entry.control->control_ref->SetExpression(expression).has_value())
        {
          entry.control->control_ref->SetExpression(previous);
          return;
        }
        controller->UpdateReferences(g_controller_interface);
        config->SaveConfig();
        StoreInputProfile([request[@"wii"] boolValue], slot);
        success = true;
        return;
      }
    }
    else if ([request[@"kind"] isEqual:@"extension"])
    {
      const int index = [request[@"index"] intValue];
      for (const auto& group : controller->groups)
      {
        if (group->type != ControllerEmu::GroupType::Attachments ||
            ![DOLString(group->name) isEqual:request[@"group"]]) continue;
        auto* attachments = static_cast<ControllerEmu::Attachments*>(group.get());
        if (index < 0 || index >= static_cast<int>(attachments->GetAttachmentList().size())) return;
        attachments->SetSelectedAttachment(index);
        controller->UpdateReferences(g_controller_interface);
        config->SaveConfig();
        StoreInputProfile([request[@"wii"] boolValue], slot);
        success = true;
        return;
      }
    }
  });
  return success ? 1 : 0;
}

extern "C" __attribute__((visibility("default")))
int32_t neostation_dolphin_restart(void)
{
  if (!g_initialized || !g_running || !g_metal_surface) return 0;
  const std::string game = g_validated_game, system_name = g_validated_system;
  const bool wii_menu = g_validated_wii_menu;
  void* surface = g_metal_surface;
  const double scale = g_metal_scale;
  Log("session.restart.begin", "Stopping the console before applying saved settings.");
  g_running = false;
  DOLHostQueueRunSync(^{
    auto& system = Core::System::GetInstance();
    Core::Stop(system);
    Core::Shutdown(system);
    ApplyConsolePreferences();
    Config::Save();
  });
  // Keep the initialized process and the verified legacy JIT authorization.
  // Boot still enforces JITARM64 and Metal before releasing CPU execution.
  const int32_t flags = DOLLaunch(game.c_str(), system_name.c_str(), surface, scale, nullptr, wii_menu);
  Log("session.restart.complete", (flags & 7) == 7 ? "Console restarted." : "Restart failed.");
  return (flags & 7) == 7 ? 1 : 0;
}

extern "C" __attribute__((visibility("default")))
int32_t neostation_dolphin_refresh_controllers(void)
{
  if (!g_initialized || !g_running) return 0;
  __block int32_t layout = 1;
  DOLHostQueueRunSync(^{
    ConfigurePhysicalControllers();
    auto lock = ControllerEmu::EmulatedController::GetStateLock();
    auto* config = Wiimote::GetConfig();
    if (!config || config->GetControllerCount() == 0) return;
    for (const auto& group : config->GetController(0)->groups)
    {
      if (group->type != ControllerEmu::GroupType::Attachments) continue;
      auto* attachments = static_cast<ControllerEmu::Attachments*>(group.get());
      const auto index = attachments->GetSelectedAttachment();
      if (index < attachments->GetAttachmentList().size() &&
          attachments->GetAttachmentList()[index]->GetName() == "Classic") layout = 2;
    }
  });
  return layout;
}

extern "C" __attribute__((visibility("default")))
void neostation_dolphin_touch_event(int32_t controller, int32_t input, float value, int32_t axis)
{
  if (controller < 0 || controller > 7 || input < 0 || input > 905 || !std::isfinite(value)) return;
  if (!g_initialized || !g_running) return;
  auto lock = ControllerEmu::EmulatedController::GetStateLock();
  if (!g_initialized || !g_running) return;
  auto* manager = ciface::iOS::StateManager::GetInstance();
  if (axis) manager->SetAxisValue(controller, static_cast<ciface::iOS::ButtonType>(input), std::clamp(value, -1.0f, 1.0f));
  else manager->SetButtonPressed(controller, static_cast<ciface::iOS::ButtonType>(input), value != 0);
}

extern "C" __attribute__((visibility("default")))
void neostation_dolphin_release_touches(void)
{
  // UIKit notifications can arrive during shutdown. Do not wait on input
  // locks once the session has stopped accepting touch events.
  if (!g_initialized || !g_running) return;
  auto lock = ControllerEmu::EmulatedController::GetStateLock();
  if (g_initialized && g_running) ciface::iOS::StateManager::GetInstance()->Init();
}

extern "C" __attribute__((visibility("default")))
int32_t neostation_dolphin_stop(const char* log_path)
{
  if (log_path) g_log_path = log_path;
  if (!g_initialized) return 1;
  ShutdownRuntime("host_stop");
  return 1;
}
'''


BRIDGE_SOURCE = BRIDGE_SOURCE.replace('// NEOSTATION_SESSION_HELPERS',
    (Path(__file__).resolve().parents[1] / 'packages/dolphin_internal_bridge/core/NeoStationSession.inc').read_text())
BRIDGE_SOURCE = BRIDGE_SOURCE.replace('// NEOSTATION_SAVESTATE_HELPERS',
    (Path(__file__).resolve().parents[1] / 'packages/dolphin_internal_bridge/core/NeoStationSavestates.inc').read_text())

BRIDGE_SOURCE = BRIDGE_SOURCE.replace('// NEOSTATION_PERFORMANCE_HELPERS',
    (Path(__file__).resolve().parents[1] / 'packages/dolphin_internal_bridge/core/NeoStationPerformance.inc').read_text())

def replace_once(path: Path, old: str, new: str, description: str) -> None:
    text = path.read_text(encoding='utf-8')
    count = text.count(old)
    if count == 0 and new in text:
        return
    if count != 1:
        raise SystemExit(f'{description}: expected one anchor in {path}, got {count}')
    path.write_text(text.replace(old, new, 1), encoding='utf-8')


def patch_savestate_results(root: Path) -> None:
    """Expose the result of the synchronous operation without replacing Dolphin's state format.

    Upstream's after-load callback fires for failures too, and SaveAs returns void.
    A serialized caller with wait=True can read this flag after the worker finishes.
    """
    def patch(path: Path, old: str, new: str, description: str) -> None:
        if new in path.read_text(encoding='utf-8'):
            return
        replace_once(path, old, new, description)

    header = root / 'Source/Core/Core/State.h'
    source = root / 'Source/Core/Core/State.cpp'
    patch(header, 'u32 GetVersion();',
                 'u32 GetVersion();\n\n// NeoStation: read only after a serialized, synchronous save/load.\n'
                 'bool NeoStationLastOperationSucceeded();', 'declare savestate result')
    patch(source, '#include "Core/State.h"',
                 '#include "Core/State.h"\n#include <atomic>', 'savestate atomic result')
    patch(source, 'static AfterLoadCallbackFunc s_on_after_load_callback;',
                 'static AfterLoadCallbackFunc s_on_after_load_callback;\n'
                 'static std::atomic<bool> s_neostation_last_operation_succeeded{false};\n'
                 'bool NeoStationLastOperationSucceeded()\n{\n'
                 '  return s_neostation_last_operation_succeeded.load();\n}\n', 'savestate result accessor')
    for signature in ('void SaveAs(Core::System& system, const std::string& filename, bool wait)',
                      'void LoadAs(Core::System& system, const std::string& filename)'):
        patch(source, signature + '\n{', signature + '\n{\n'
                     '  s_neostation_last_operation_succeeded = false;', 'reset savestate result')
    # A failed write/close must leave the previous slot intact, not rename bad bytes over it.
    patch(source, '  if (!f.IsGood())\n    Core::DisplayMessage("Failed to write state file", 2000);',
                 '  if (!f.IsGood() || !f.Close())\n  {\n'
                 '    Core::DisplayMessage("Failed to write state file", 2000);\n'
                 '    f.Close();\n    File::Delete(temp_filename);\n    return;\n  }', 'preserve state on write failure')
    patch(source, '    if (!f.Close())\n      Core::DisplayMessage("Failed to close state file", 2000);',
                 '    // NeoStation closed and verified the temporary file before touching the old slot.',
                 'state file is already closed')
    patch(source, '    // Backup existing state (overwriting an existing backup, if any).\n    if (File::Exists(filename))',
                 '    // Backup existing state (overwriting an existing backup, if any).\n'
                 '    const bool had_previous = File::Exists(filename);\n    if (had_previous)',
                 'track the previous slot for rollback')
    patch(source, '      const std::filesystem::path temp_path(filename);\n'
                 '      Core::DisplayMessage(fmt::format("Saved State to {}", temp_path.filename().string()), 2000);',
                 '      s_neostation_last_operation_succeeded = true;\n'
                 '      const std::filesystem::path temp_path(filename);\n'
                 '      Core::DisplayMessage(fmt::format("Saved State to {}", temp_path.filename().string()), 2000);',
                 'publish confirmed state write result')
    patch(source, '      Core::DisplayMessage("Failed to rename state file", 2000);',
                 '      Core::DisplayMessage("Failed to rename state file", 2000);\n'
                 '      // The old slot may already have moved to the undo file. Restore it on failure.\n'
                 '      if (had_previous && !File::Exists(filename) && File::Exists(last_state_filename))\n'
                 '        File::Rename(last_state_filename, filename);\n'
                 '      File::Delete(temp_filename);', 'recover state after failed publication')
    patch(source, '        if (s_on_after_load_callback)\n          s_on_after_load_callback();',
                 '        // Set this after UndoLoadState: a successful rollback is still a failed load.\n'
                 '        s_neostation_last_operation_succeeded = loadedSuccessfully;\n'
                 '        if (s_on_after_load_callback)\n          s_on_after_load_callback();',
                 'publish actual state load result')


def patch_savestate_memory(root: Path) -> None:
    """Bound the LZ4 workspace without changing the pinned native state format."""
    source = root / 'Source/Core/Core/State.cpp'
    def patch(old: str, new: str, description: str) -> None:
        if new not in source.read_text(encoding='utf-8'):
            replace_once(source, old, new, description)

    helper = (Path(__file__).resolve().parents[1] /
              'packages/dolphin_internal_bridge/core/NeoStationStateCompression.inc').read_text()
    text = source.read_text(encoding='utf-8')
    if helper not in text:
        start = text.index('static void CompressBufferToFile(')
        end = text.index('static void CreateExtendedHeader(', start)
        source.write_text(text[:start] + helper + '\n' + text[end:], encoding='utf-8')
    patch('#include <atomic>', '#include <atomic>\n#include <new>',
          'savestate allocation failure support')
    patch(
                 '  if (s_use_compression)\n    CompressBufferToFile(buffer_data, buffer_size, f);\n'
                 '  else\n    f.WriteBytes(buffer_data, buffer_size);',
                 '  if (s_use_compression)\n  {\n'
                 '    if (!CompressBufferToFile(buffer_data, buffer_size, f))\n    {\n'
                 '      Core::DisplayMessage("Failed to compress or write state file", 2000);\n'
                 '      f.Close();\n      File::Delete(temp_filename);\n      return;\n    }\n  }\n'
                 '  else\n    f.WriteBytes(buffer_data, buffer_size);',
                 'abort state publication on compression failure')
    patch(
                 '    if (args.state_write_done_event)\n      args.state_write_done_event->Set();',
                 '    // Release the raw snapshot before the synchronous caller can start another state.\n'
                 '    args.buffer.reset();\n'
                 '    if (args.state_write_done_event)\n      args.state_write_done_event->Set();',
                 'release state memory before completion')


def patch_performance_metrics(root: Path) -> None:
    """Expose atomic metrics and publish render dimensions from the GPU thread."""
    def patch(path: Path, old: str, new: str, description: str) -> None:
        if new not in path.read_text(encoding='utf-8'):
            replace_once(path, old, new, description)
    header = root / 'Source/Core/VideoCommon/PerformanceMetrics.h'
    old = '  double GetMaxSpeed() const;'
    new = old + """

  // NeoStation: PerformanceTracker getters read atomic samples.
  double GetFrameTimeMs() const { return DT_ms(m_fps_counter.GetDtAvg()).count(); }
  double GetLastFrameTimeMs() const { return DT_ms(m_fps_counter.GetLastRawDt()).count(); }
  double GetFrameTimeStdMs() const { return DT_ms(m_fps_counter.GetDtStd()).count(); }"""
    patch(header, old, new, 'expose atomic frame timing')
    source = root / 'Source/Core/VideoCommon/FramebufferManager.cpp'
    old = '#include "VideoCommon/FramebufferManager.h"'
    new = old + '\n\nextern "C" void neostation_dolphin_record_render_size(u32 width, u32 height);'
    patch(source, old, new, 'declare actual render size recorder')
    old = '  Core::System::GetInstance().GetPixelShaderManager().Dirty();\n\n  return true;'
    new = '  Core::System::GetInstance().GetPixelShaderManager().Dirty();\n\n' + \
          '  neostation_dolphin_record_render_size(width, height);\n  return true;'
    patch(source, old, new, 'publish successful EFB allocation')
    old = 'void FramebufferManager::DestroyEFBFramebuffer()\n{'
    new = old + '\n  neostation_dolphin_record_render_size(0, 0);'
    patch(source, old, new, 'clear released EFB dimensions')


def patch_metal_shutdown(root: Path) -> None:
    """Finish Metal callbacks before destroying their per-game result owners."""
    def patch(path: Path, old: str, new: str, description: str) -> None:
        if new not in path.read_text(encoding='utf-8'):
            replace_once(path, old, new, description)

    header = root / 'Source/Core/VideoBackends/Metal/MTLStateTracker.h'
    tracker = root / 'Source/Core/VideoBackends/Metal/MTLStateTracker.mm'
    backend = root / 'Source/Core/VideoBackends/Metal/MTLMain.mm'
    patch(header, '  void WaitForFlushedEncoders();',
          '  void WaitForFlushedEncoders();\n  void PrepareForShutdown();',
          'declare Metal shutdown callback drain')
    old = 'void Metal::StateTracker::WaitForFlushedEncoders()\n{'
    new = '''void Metal::StateTracker::PrepareForShutdown()
{
  // Called by the emulation/GPU thread after CPU execution has joined, while
  // g_perf_query and g_framebuffer_manager still belong to this session.
  FlushEncoders();
  // waitUntilCompleted also waits for this command buffer's completion handlers.
  // Never hold the backref mutex here: those handlers need it to finish.
  WaitForFlushedEncoders();
  // Older completion handlers can still be entering on their callback threads.
  // Finish any handler already inside the lock and reject all late callbacks
  // before ShutdownShared releases their query/framebuffer objects.
  std::lock_guard<std::mutex> lock(m_backref->mtx);
  m_backref->state_tracker = nullptr;
}

''' + old
    patch(tracker, old, new, 'drain and detach Metal completion callbacks')
    old = 'void Metal::VideoBackend::Shutdown()\n{\n  ShutdownShared();'
    new = '''void Metal::VideoBackend::Shutdown()
{
  // Shared renderer destruction releases objects used by asynchronous Metal
  // completion handlers. Joining Dolphin's CPU thread alone does not join them.
  if (g_state_tracker)
    g_state_tracker->PrepareForShutdown();
  ShutdownShared();'''
    patch(backend, old, new, 'drain Metal before renderer destruction')


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument('dolphin_root', type=Path)
    root = parser.parse_args().dolphin_root.resolve()
    cmake = root / 'Source/iOS/Library/CMakeLists.txt'
    memory = root / 'Source/Core/Common/MemoryUtil_iOS_LuckTXM.cpp'
    bridge = root / 'Source/iOS/Library/NeoStationBridge.mm'
    if not cmake.is_file() or not memory.is_file():
        raise SystemExit('Not a compatible pinned dolphin-ios checkout')
    replace_once(cmake, '  HostQueue.mm\n)', '  HostQueue.mm\n  NeoStationBridge.mm\n)', 'add NeoStation bridge')
    definition = 'target_compile_definitions(dolphin PRIVATE NEOSTATION_INTERNAL_DOLPHIN=1)'
    text = cmake.read_text()
    if definition not in text:
        cmake.write_text(text + '\n' + definition + '\n')
    # The pinned toolchain adds ARC to C/C++ flags, but Ninja compiles this .mm
    # using the separately enabled OBJCXX language. Make ownership explicit for
    # our generated bridge without changing the upstream renderer/host files.
    arc = 'set_source_files_properties(NeoStationBridge.mm PROPERTIES COMPILE_OPTIONS "-fobjc-arc")'
    text = cmake.read_text()
    if arc not in text:
        cmake.write_text(text + '\n' + arc + '\n')
    replace_once(memory, '  if (!rx_ptr)\n', '  if (rx_ptr == MAP_FAILED)\n', 'mmap failure detection')
    patch_savestate_results(root)
    patch_savestate_memory(root)
    patch_performance_metrics(root)
    patch_metal_shutdown(root)
    bridge.write_text(BRIDGE_SOURCE, encoding='utf-8')
    updated = memory.read_text()
    required = ('brk #0x69', '"mov x0, %0\\n"', '"mov x1, %1\\n"', 'if (rx_ptr == MAP_FAILED)')
    if any(needle not in updated for needle in required):
        raise SystemExit('Pinned legacy allocator protocol changed')
    if 'JIT26PrepareRegion' in updated or 'brk #0xf00d' in updated:
        raise SystemExit('Unexpected JIT ABI in the Dolphin legacy allocator')
    import re
    for header in re.findall(r'^#include "([^"]+)"', BRIDGE_SOURCE, re.MULTILINE):
        if not any((base / header).is_file() for base in (root / 'Source/Core', root / 'Source/iOS/Library')):
            raise SystemExit(f'Pinned Dolphin header is absent: {header}')
    print('Patched pinned Dolphin JITARM64/Metal runtime.')


if __name__ == '__main__':
    main()
