#!/usr/bin/env python3
"""Patch OatmealDome/dolphin-ios into a strict NeoStation-owned dylib.

The generated ABI is deliberately tiny and process-local. It accepts only
GameCube/Wii images, requires the existing Dolphin BRK #0x69 allocator protocol,
requires JITARM64 and Metal, and exposes deterministic cleanup hooks.
"""

from __future__ import annotations

import argparse
from pathlib import Path


BRIDGE_SOURCE = r'''// Generated by NeoStation. SPDX-License-Identifier: GPL-2.0-or-later
#import <Foundation/Foundation.h>
#import <Metal/Metal.h>
#import <QuartzCore/CAMetalLayer.h>
#import <libkern/OSCacheControl.h>

#include <algorithm>
#include <atomic>
#include <chrono>
#include <cstdint>
#include <cstring>
#include <fstream>
#include <memory>
#include <mutex>
#include <string>
#include <thread>

#include "Common/FileUtil.h"
#include "Common/MemoryUtil.h"
#include "Common/MsgHandler.h"
#include "Common/WindowSystemInfo.h"
#include "Core/Boot/Boot.h"
#include "Core/BootManager.h"
#include "Core/Config/GraphicsSettings.h"
#include "Core/Config/MainSettings.h"
#include "Core/ConfigManager.h"
#include "Core/Core.h"
#include "Core/DolphinAnalytics.h"
#include "Core/DolphinAnalytics.h"
#include "Core/DolphinAnalytics.h"
#include "Core/PowerPC/JitInterface.h"
#include "Core/PowerPC/JitInterface.h"
#include "Core/PowerPC/JitInterface.h"
#include "Core/PowerPC/PowerPC.h"
#include "Core/System.h"
#include "DiscIO/Enums.h"
#include "DiscIO/Volume.h"
#include "DiscIO/VolumeCreator.h"
#include "DolphinNoGUI/Platform.h"
#include "UICommon/UICommon.h"
#include "VideoCommon/Present.h"
#include "VideoCommon/VideoConfig.h"

#include "HostQueue.h"

namespace
{
std::mutex g_state_mutex;
std::atomic<bool> g_initialized{false};
std::atomic<bool> g_jit_handshake{false};
std::atomic<bool> g_executable_probe{false};
std::atomic<bool> g_running{false};
std::atomic<bool> g_cleanup_started{false};
std::atomic<bool> g_host_declared{false};
std::string g_user_directory;
std::string g_system_directory;
std::string g_validated_game;
std::string g_validated_system;
std::string g_log_path;

void Log(const std::string& stage, const std::string& message)
{
  const std::string path = g_log_path;
  if (path.empty())
    return;
  std::ofstream out(path, std::ios::app);
  if (!out)
    return;
  const auto now = std::chrono::duration_cast<std::chrono::milliseconds>(
      std::chrono::system_clock::now().time_since_epoch()).count();
  out << "{\"timestampMs\":" << now
      << ",\"engine\":\"dolphin_internal\""
      << ",\"stage\":\"" << stage << "\""
      << ",\"message\":\"";
  for (const char character : message)
  {
    switch (character)
    {
    case '\\': out << "\\\\"; break;
    case '"': out << "\\\""; break;
    case '\n': out << "\\n"; break;
    case '\r': out << "\\r"; break;
    default: out << character; break;
    }
  }
  out << "\"}\n";
  out.flush();
}

void DeclareMainAsHostThread()
{
  dispatch_block_t block = ^{
    if (!g_host_declared.exchange(true))
      Core::DeclareAsHostThread();
  };
  if ([NSThread isMainThread])
    block();
  else
    dispatch_sync(dispatch_get_main_queue(), block);
}

void UndeclareMainAsHostThread()
{
  dispatch_block_t block = ^{
    if (g_host_declared.exchange(false))
      Core::UndeclareAsHostThread();
  };
  if ([NSThread isMainThread])
    block();
  else
    dispatch_sync(dispatch_get_main_queue(), block);
}

bool ExpectedPlatform(const DiscIO::Platform platform, const std::string& system)
{
  if (system == "gc")
    return platform == DiscIO::Platform::GameCubeDisc;
  if (system == "wii")
    return platform == DiscIO::Platform::WiiDisc ||
           platform == DiscIO::Platform::WiiWAD;
  return false;
}

bool WaitForCoreToLeaveStarting(const std::chrono::seconds timeout)
{
  const auto deadline = std::chrono::steady_clock::now() + timeout;
  auto& system = Core::System::GetInstance();
  while (Core::GetState(system) == Core::State::Starting &&
         std::chrono::steady_clock::now() < deadline)
  {
    std::this_thread::sleep_for(std::chrono::milliseconds(25));
  }
  return Core::GetState(system) != Core::State::Starting;
}

void ResetSessionFlags()
{
  g_jit_handshake = false;
  g_executable_probe = false;
  g_running = false;
  g_validated_game.clear();
  g_validated_system.clear();
}

void ShutdownRuntime(const char* reason)
{
  if (g_cleanup_started.exchange(true))
    return;

  Log("cleanup.begin", reason == nullptr ? "cleanup" : reason);
  auto& system = Core::System::GetInstance();
  DOLHostQueueRunSync(^{
    if (Core::GetState(system) != Core::State::Uninitialized)
      Core::Stop(system);
  });

  const auto deadline = std::chrono::steady_clock::now() + std::chrono::seconds(15);
  while (Core::GetState(system) != Core::State::Uninitialized &&
         std::chrono::steady_clock::now() < deadline)
  {
    std::this_thread::sleep_for(std::chrono::milliseconds(25));
  }

  DOLHostQueueRunSync(^{
    Config::Save();
    Core::Shutdown(system);
    UICommon::ShutdownControllers();
    UICommon::Shutdown();
  });
  DeclareMainAsHostThread();

  {
    std::lock_guard<std::mutex> lock(g_state_mutex);
    ResetSessionFlags();
    g_initialized = false;
  }
  Log("cleanup.complete",
      "Dolphin core, threads, controllers and per-session state released.");
  g_cleanup_started = false;
}

void StartEndMonitor()
{
  std::thread([] {
    auto& system = Core::System::GetInstance();
    while (Core::IsRunning(system) || Core::GetState(system) == Core::State::Starting)
      std::this_thread::sleep_for(std::chrono::milliseconds(100));
    g_running = false;
    ShutdownRuntime("core_ended");
  }).detach();
}

bool RunExecutableProbe()
{
#if !defined(__aarch64__)
  Log("jit.executable_probe_failed", "Executable probe requires arm64.");
  return false;
#else
  // OatmealDome/dolphin-ios currently establishes the TXM writable alias by
  // stopping at BRK #0x69 with RX in x0 and length in x1. StikJIT's legacy
  // script must be attached before this call. Returning proves the handshake.
  Common::SetJitType(Common::JitType::LuckTXM);
  Common::AllocateExecutableMemoryRegion();
  g_jit_handshake = true;
  Log("jit.legacy_handshake_validated", "BRK #0x69 returned to Dolphin.");

  constexpr std::size_t probe_size = 0x4000;
  void* rx = Common::AllocateExecutableMemory(probe_size);
  if (rx == nullptr)
  {
    Log("jit.executable_probe_failed", "Dolphin returned no RX probe page.");
    return false;
  }
  const std::ptrdiff_t writable_difference =
      Common::AllocateWritableRegionAndGetDiff(rx, probe_size);
  if (writable_difference == 0)
  {
    Log("jit.executable_probe_failed", "Dolphin returned no writable alias.");
    return false;
  }

  auto* rw = reinterpret_cast<std::uint32_t*>(
      reinterpret_cast<std::uint8_t*>(rx) + writable_difference);
  // mov w0, #42 ; ret
  rw[0] = 0x52800540;
  rw[1] = 0xD65F03C0;
  sys_icache_invalidate(rx, 2 * sizeof(std::uint32_t));
  using Probe = int (*)();
  const int value = reinterpret_cast<Probe>(rx)();
  if (value != 42)
  {
    Log("jit.executable_probe_failed", "Generated ARM64 code returned an unexpected value.");
    return false;
  }
  g_executable_probe = true;
  Log("jit.executable_probe_passed", "Generated ARM64 code executed and returned 42.");
  return true;
#endif
}
}  // namespace

extern "C" __attribute__((visibility("default")))
int32_t neostation_dolphin_initialize(const char* user_directory,
                                      const char* system_directory,
                                      const char* log_path)
{
  std::lock_guard<std::mutex> lock(g_state_mutex);
  if (g_initialized)
    return 1;
  if (user_directory == nullptr || system_directory == nullptr ||
      *user_directory == '\0' || *system_directory == '\0')
    return 0;

  g_user_directory = user_directory;
  g_system_directory = system_directory;
  g_log_path = log_path == nullptr ? "" : log_path;
  g_cleanup_started = false;
  ResetSessionFlags();

  try
  {
    DeclareMainAsHostThread();
    UICommon::SetUserDirectory(g_user_directory);
    UICommon::CreateDirectories();
    UICommon::Init();
    WindowSystemInfo controller_wsi;
    controller_wsi.type = WindowSystemType::iOS;
    UICommon::InitControllers(controller_wsi);
    DolphinAnalytics::Instance().ReportDolphinStart("neostation-ios");
    g_initialized = true;
    Log("core.initialized", "Embedded Dolphin core initialized in NeoStation.");
    return 1;
  }
  catch (...)
  {
    Log("core.initialize_failed", "Exception during embedded Dolphin initialization.");
    return 0;
  }
}

extern "C" __attribute__((visibility("default")))
int32_t neostation_dolphin_validate_image(const char* game_path,
                                          const char* expected_system,
                                          const char* log_path)
{
  if (log_path != nullptr)
    g_log_path = log_path;
  if (!g_initialized || game_path == nullptr || expected_system == nullptr)
    return 0;

  const std::string path(game_path);
  const std::string system(expected_system);
  if (system != "gc" && system != "wii")
  {
    Log("image.route_rejected", "Internal Dolphin route is not GameCube/Wii.");
    return 0;
  }

  std::unique_ptr<DiscIO::Volume> volume = DiscIO::CreateVolume(path);
  if (!volume)
  {
    Log("image.open_failed", "DiscIO could not open the selected image.");
    return 0;
  }
  const DiscIO::Platform platform = volume->GetVolumeType();
  if (!ExpectedPlatform(platform, system))
  {
    Log("image.platform_mismatch", "Image platform does not match the selected playlist.");
    return 0;
  }
  g_validated_game = path;
  g_validated_system = system;
  Log("image.validated", "DiscIO validated the selected GameCube/Wii image.");
  return 1;
}

extern "C" __attribute__((visibility("default")))
int32_t neostation_dolphin_prepare_legacy_jit(const char* log_path)
{
  if (log_path != nullptr)
    g_log_path = log_path;
  if (!g_initialized || g_validated_game.empty())
  {
    Log("jit.precondition_failed", "Core or image validation is incomplete.");
    return 0;
  }

  bool probe_ok = false;
  try
  {
    probe_ok = RunExecutableProbe();
  }
  catch (...)
  {
    Log("jit.executable_probe_failed", "Exception during Dolphin executable-memory validation.");
  }
  int32_t flags = 0;
  if (g_jit_handshake) flags |= 0x1;
  if (probe_ok && g_executable_probe) flags |= 0x2;
  return flags;
}

extern "C" __attribute__((visibility("default")))
int32_t neostation_dolphin_launch(const char* game_path,
                                  const char* expected_system,
                                  void* metal_layer,
                                  double metal_scale,
                                  const char* log_path)
{
  if (log_path != nullptr)
    g_log_path = log_path;
  if (!g_initialized || !g_jit_handshake || !g_executable_probe ||
      game_path == nullptr || expected_system == nullptr || metal_layer == nullptr)
  {
    Log("launch.precondition_failed", "One or more strict Dolphin launch gates are incomplete.");
    return 0;
  }

  const std::string path(game_path);
  const std::string system_name(expected_system);
  if (path != g_validated_game || system_name != g_validated_system ||
      (system_name != "gc" && system_name != "wii"))
  {
    Log("launch.image_changed", "The game or system changed after validation.");
    return 0;
  }

  __block bool booted = false;
  __block WindowSystemInfo wsi;
  wsi.type = WindowSystemType::iOS;
  wsi.render_surface = metal_layer;
  wsi.render_surface_scale = metal_scale > 0.0 ? metal_scale : 1.0;

  UndeclareMainAsHostThread();
  DOLHostQueueRunSync(^{
    Config::SetBase(Config::MAIN_CPU_CORE, PowerPC::CPUCore::JITARM64);
    Config::SetBase(Config::MAIN_GFX_BACKEND, std::string("Metal"));
    Config::SetBase(Config::GFX_VERTEX_LOADER_TYPE, VertexLoaderType::Native);
    std::unique_ptr<BootParameters> boot = BootParameters::GenerateFromFile(path);
    if (boot)
      booted = BootManager::BootCore(Core::System::GetInstance(), std::move(boot), wsi);
  });

  if (!booted || !WaitForCoreToLeaveStarting(std::chrono::seconds(30)))
  {
    Log("core.boot_failed", "BootManager did not start the selected image.");
    ShutdownRuntime("boot_failed");
    return 0;
  }

  int32_t flags = 0;
  if (Config::Get(Config::MAIN_CPU_CORE) == PowerPC::CPUCore::JITARM64 &&
      Core::System::GetInstance().GetJitInterface().GetCore() != nullptr)
  {
    flags |= 0x1;
    Log("jit.jitarm64_initialized", "Dolphin reports an initialized JITARM64 CPU core.");
  }
  else
  {
    Log("jit.jitarm64_failed", "JITARM64 was not initialized; interpreter fallback is blocked.");
  }

  if (g_presenter != nullptr && Core::IsRunning(Core::System::GetInstance()))
  {
    flags |= 0x2;
    Log("metal.initialized", "Dolphin Metal presenter initialized on NeoStation's CAMetalLayer.");
  }
  else
  {
    Log("metal.initialize_failed", "Dolphin did not create a Metal presenter.");
  }

  if ((flags & 0x3) == 0x3 && Core::IsRunning(Core::System::GetInstance()))
  {
    flags |= 0x4;
    g_running = true;
    Log("game.submitted", "Validated game submitted to the running embedded core.");
    StartEndMonitor();
  }
  else
  {
    ShutdownRuntime("strict_launch_gate_failed");
  }
  return flags;
}

extern "C" __attribute__((visibility("default")))
int32_t neostation_dolphin_is_running(void)
{
  return g_running && Core::IsRunning(Core::System::GetInstance()) ? 1 : 0;
}

extern "C" __attribute__((visibility("default")))
int32_t neostation_dolphin_set_paused(int32_t paused)
{
  if (!g_running)
    return 0;
  DOLHostQueueRunSync(^{
    Core::SetState(Core::System::GetInstance(),
                   paused ? Core::State::Paused : Core::State::Running);
  });
  return 1;
}

extern "C" __attribute__((visibility("default")))
int32_t neostation_dolphin_stop(const char* log_path)
{
  if (log_path != nullptr)
    g_log_path = log_path;
  if (!g_initialized)
    return 1;
  ShutdownRuntime("host_stop");
  return 1;
}
'''


def replace_once(path: Path, old: str, new: str, description: str) -> None:
    text = path.read_text(encoding="utf-8")
    count = text.count(old)
    if count == 0 and new in text:
        return
    if count != 1:
        raise SystemExit(f"{description}: expected exactly one anchor in {path}, got {count}")
    path.write_text(text.replace(old, new, 1), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("dolphin_root", type=Path)
    args = parser.parse_args()
    root = args.dolphin_root.resolve()

    cmake = root / "Source/iOS/Library/CMakeLists.txt"
    memory = root / "Source/Core/Common/MemoryUtil_iOS_LuckTXM.cpp"
    bridge = root / "Source/iOS/Library/NeoStationBridge.mm"
    if not cmake.is_file() or not memory.is_file():
        raise SystemExit("Not a compatible OatmealDome/dolphin-ios checkout")

    replace_once(
        cmake,
        "  HostQueue.mm\n)",
        "  HostQueue.mm\n  NeoStationBridge.mm\n)",
        "add NeoStation bridge source",
    )
    definition = "target_compile_definitions(dolphin PRIVATE NEOSTATION_INTERNAL_DOLPHIN=1)"
    cmake_text = cmake.read_text(encoding="utf-8")
    if definition not in cmake_text:
        cmake_text += f"\n# NeoStation process-local bridge\n{definition}\n"
        cmake.write_text(cmake_text, encoding="utf-8")

    replace_once(
        memory,
        "  if (!rx_ptr)\n",
        "  if (rx_ptr == MAP_FAILED)\n",
        "correct mmap failure detection",
    )

    bridge.write_text(BRIDGE_SOURCE, encoding="utf-8")

    updated = memory.read_text(encoding="utf-8")
    required = (
        'brk #0x69',
        '"mov x0, %0\\n"',
        '"mov x1, %1\\n"',
        'if (rx_ptr == MAP_FAILED)',
    )
    missing = [needle for needle in required if needle not in updated]
    if missing:
        raise SystemExit("Legacy Dolphin ABI check failed: " + ", ".join(missing))
    if "JIT26PrepareRegion" in updated or "brk #0xf00d" in updated:
        raise SystemExit("Universal JIT ABI leaked into the Dolphin legacy allocator")

    print("Patched Dolphin for isolated NeoStation JITARM64/Metal embedding.")


if __name__ == "__main__":
    main()
