#!/usr/bin/env python3
"""Patch the pinned Dolphin into a strict, process-local NeoStation engine."""
from __future__ import annotations
import argparse
from pathlib import Path

BRIDGE_SOURCE = r'''// Generated by NeoStation. SPDX-License-Identifier: GPL-2.0-or-later
#import <Foundation/Foundation.h>
#import <Metal/Metal.h>
#import <QuartzCore/CAMetalLayer.h>
#import <libkern/OSCacheControl.h>
#import <mach/mach.h>
#import <mach/vm_map.h>
#import <mach/vm_region.h>
#import <sys/mman.h>
#include <algorithm>
#include <atomic>
#include <chrono>
#include <cstdint>
#include <cstring>
#include <vector>
#include <fstream>
#include <memory>
#include <map>
#include <mutex>
#include <optional>
#include <set>
#include <string>
#include <thread>
#include "Common/FileUtil.h"
#include "Common/MemoryUtil.h"
#include "Common/MsgHandler.h"
#include "Common/WindowSystemInfo.h"
#include "Core/Boot/Boot.h"
#include "Core/BootManager.h"
#include "Core/Config/GraphicsSettings.h"
#include "Core/Config/MainSettings.h"
#include "Core/Config/SYSCONFSettings.h"
#include "Core/Config/WiimoteSettings.h"
#include "Core/ConfigLoaders/BaseConfigLoader.h"
#include "Core/ConfigManager.h"
#include "Core/Core.h"
#include "Core/DolphinAnalytics.h"
#include "Core/HW/GCPad.h"
#include "Core/HW/Wiimote.h"
#include "InputCommon/InputConfig.h"
#include "InputCommon/ControllerInterface/iOS/StateManager.h"
#include "InputCommon/ControllerEmu/ControllerEmu.h"
#include "InputCommon/ControllerEmu/ControlGroup/Attachments.h"
#include "Core/PowerPC/JitInterface.h"
#include "Core/PowerPC/PowerPC.h"
#include "Core/System.h"
#include "DiscIO/Enums.h"
#include "DiscIO/Volume.h"
#include "UICommon/UICommon.h"
#include "VideoCommon/Present.h"
#include "VideoCommon/VideoConfig.h"
#include "HostQueue.h"

namespace
{
std::mutex g_state_mutex;
std::atomic<bool> g_initialized{false};
std::atomic<bool> g_jit_handshake{false};
std::atomic<bool> g_executable_probe{false};
std::atomic<bool> g_running{false};
std::atomic<bool> g_cleanup_started{false};
std::atomic<bool> g_host_declared{false};
std::atomic<bool> g_arena_established{false};
std::string g_user_directory;
std::string g_system_directory;
std::string g_validated_game;
std::string g_validated_system;
std::string g_log_path;
void* g_metal_surface = nullptr;
double g_metal_scale = 1.0;
std::atomic<bool> g_devices_changed{true};
std::optional<ControllerInterface::HotplugCallbackHandle> g_devices_callback;
void ConfigurePhysicalControllers();
void ApplyConsolePreferences();
void ResetInputProfiles();
std::atomic<int> g_boot_language{-1};

void Log(const std::string& stage, const std::string& message)
{
  const std::string path = g_log_path;
  if (path.empty()) return;
  std::ofstream out(path, std::ios::app);
  if (!out) return;
  const auto now = std::chrono::duration_cast<std::chrono::milliseconds>(
      std::chrono::system_clock::now().time_since_epoch()).count();
  out << "{\"timestampMs\":" << now << ",\"engine\":\"dolphin_internal\""
      << ",\"stage\":\"" << stage << "\",\"message\":\"";
  for (const unsigned char character : message)
  {
    switch (character)
    {
    case '\\': out << "\\\\"; break;
    case '"': out << "\\\""; break;
    case '\n': out << "\\n"; break;
    case '\r': out << "\\r"; break;
    case '\t': out << "\\t"; break;
    default: if (character >= 32) out << character; break;
    }
  }
  out << "\"}\n";
  out.flush();
}

void DeclareMainAsHostThread()
{
  dispatch_block_t block = ^{
    if (!g_host_declared.exchange(true)) Core::DeclareAsHostThread();
  };
  if ([NSThread isMainThread]) block();
  else dispatch_sync(dispatch_get_main_queue(), block);
}

void UndeclareMainAsHostThread()
{
  dispatch_block_t block = ^{
    if (g_host_declared.exchange(false)) Core::UndeclareAsHostThread();
  };
  if ([NSThread isMainThread]) block();
  else dispatch_sync(dispatch_get_main_queue(), block);
}

bool ExpectedPlatform(DiscIO::Platform platform, const std::string& system)
{
  if (system == "gc") return platform == DiscIO::Platform::GameCubeDisc;
  if (system == "wii") return platform == DiscIO::Platform::WiiDisc || platform == DiscIO::Platform::WiiWAD;
  return false;
}

bool WaitForCoreToLeaveStarting(std::chrono::seconds timeout)
{
  const auto deadline = std::chrono::steady_clock::now() + timeout;
  auto& system = Core::System::GetInstance();
  while (Core::GetState(system) == Core::State::Starting && std::chrono::steady_clock::now() < deadline)
    std::this_thread::sleep_for(std::chrono::milliseconds(25));
  return Core::GetState(system) != Core::State::Starting;
}

void ResetSessionFlags()
{
  g_jit_handshake = false;
  g_executable_probe = false;
  g_running = false;
  g_validated_game.clear();
  g_validated_system.clear();
}

void ShutdownRuntime(const char* reason)
{
  // All lifecycle entries run on the dedicated serial Dolphin queue. Never
  // release Metal after a timeout while the emulation thread still owns it.
  if (!g_initialized || g_cleanup_started.exchange(true)) return;
  g_running = false;
  Log("cleanup.begin", reason == nullptr ? "cleanup" : reason);
  DOLHostQueueRunSync(^{
    auto& system = Core::System::GetInstance();
    Log("cleanup.core_stop.begin", "Requesting CPU and GPU shutdown.");
    Core::Stop(system);
    Log("cleanup.core_join.begin", "Waiting for the emulation thread.");
    Core::Shutdown(system); // Pinned API joins the real emulation thread.
    Log("cleanup.core_join.complete", "Emulation thread joined; surface can be detached after cleanup.");
    ApplyConsolePreferences();
    Config::Save();
    if (g_devices_callback)
    {
      g_controller_interface.UnregisterDevicesChangedCallback(*g_devices_callback);
      g_devices_callback.reset();
    }
    ResetInputProfiles();
    Log("cleanup.controllers.begin", "Releasing controller backends.");
    UICommon::ShutdownControllers();
    Log("cleanup.controllers.complete", "Controller backends released.");
    UICommon::Shutdown();
  });
  UndeclareMainAsHostThread();
  ResetSessionFlags();
  g_initialized = false;
  Log("cleanup.complete", "Emulation thread joined; controllers, audio, GPU and per-session state released.");
  g_cleanup_started = false;
}

bool HasMemoryPermissions(void* pointer, size_t length, vm_prot_t required)
{
  // iPhoneOS exposes vm_region_64 via vm_map.h; mach_vm.h is unavailable.
  // Only inspect this arm64 process, keeping addresses pointer-sized.
  static_assert(sizeof(vm_address_t) == sizeof(void*), "VM address must preserve pointer width");
  if (pointer == nullptr || length == 0) return false;
  vm_address_t address = reinterpret_cast<vm_address_t>(pointer);
  const vm_address_t requested = address;
  vm_size_t size = 0;
  vm_region_basic_info_data_64_t info{};
  mach_msg_type_number_t count = VM_REGION_BASIC_INFO_COUNT_64;
  mach_port_t object = MACH_PORT_NULL;
  const kern_return_t status = vm_region_64(mach_task_self(), &address, &size,
      VM_REGION_BASIC_INFO_64, reinterpret_cast<vm_region_info_t>(&info), &count, &object);
  if (object != MACH_PORT_NULL) mach_port_deallocate(mach_task_self(), object);
  return status == KERN_SUCCESS && count == VM_REGION_BASIC_INFO_COUNT_64 &&
      address <= requested && size >= length &&
      requested - address <= size - length && (info.protection & required) == required;
}

bool SelectRegionalIPL(const std::string& game_path)
{
  if (g_validated_system != "gc") return true;
  auto volume = DiscIO::CreateVolume(game_path);
  if (!volume) return false;
  const std::string region = Config::GetDirectoryForRegion(volume->GetRegion());
  const std::string ipl_path = Config::GetBootROMPath(region);
  if (!File::Exists(ipl_path))
  {
    Config::SetBase(Config::MAIN_SKIP_IPL, true);
    Log("ipl.not_installed", "No matching regional IPL; use normal Dolphin HLE boot, not a CPU interpreter fallback.");
    return true;
  }
  std::ifstream stream(ipl_path, std::ios::binary | std::ios::ate);
  constexpr size_t size = 2 * 1024 * 1024;
  if (!stream || stream.tellg() != static_cast<std::streamoff>(size))
  {
    Log("ipl.rejected", "Installed regional IPL has an invalid size.");
    return false;
  }
  std::vector<unsigned char> data(size);
  stream.seekg(0);
  if (!stream.read(reinterpret_cast<char*>(data.data()), size)) return false;
  const std::string header(reinterpret_cast<const char*>(data.data()), 0x100);
  uint32_t crc = 0xffffffff;
  for (unsigned char byte : data)
  {
    crc ^= byte;
    for (int bit = 0; bit < 8; ++bit)
      crc = (crc >> 1) ^ (0xedb88320U & (0U - (crc & 1)));
  }
  crc ^= 0xffffffff;
  const bool pal = crc == 0x4f319f43 || crc == 0xad1b7f16;
  const bool ntsc = crc == 0x6dac1f2a || crc == 0xd5e6feea || crc == 0xd235e3f9 ||
                    crc == 0x86573808 || crc == 0x667d0b64;
  if (header.find("Nintendo") == std::string::npos || header.find("ArtX Inc.") == std::string::npos ||
      !(region == "EUR" ? pal : ntsc))
  {
    Log("ipl.rejected", "Installed IPL failed Nintendo/ArtX, full-content CRC or region-family validation.");
    return false;
  }
  Config::SetBase(Config::MAIN_SKIP_IPL, false);
  Log("ipl.accepted", "Validated regional IPL selected: " + region);
  return true;
}

bool RunExecutableProbe()
{
#if !defined(__aarch64__)
  Log("jit.executable_probe_failed", "Executable probe requires arm64.");
  return false;
#else
  Common::SetJitType(Common::JitType::LuckTXM);
  const bool existing_arena = g_arena_established.load();
  if (!existing_arena)
  {
    Log("jit.legacy_handshake_started", "Entering the pinned Dolphin arena BRK #0x69 protocol.");
    Common::AllocateExecutableMemoryRegion();
  }
  constexpr std::size_t probe_size = 0x4000;
  void* rx = Common::AllocateExecutableMemory(probe_size);
  if (rx == nullptr || rx == MAP_FAILED)
  {
    Log("jit.executable_probe_failed", "Dolphin returned no RX probe page.");
    return false;
  }
  if (existing_arena)
  {
    // The upstream arena initializer returns early after its first invocation.
    // Every new helper still needs a fresh transaction, not a cached attach bit.
    Log("jit.legacy_handshake_started", "Fresh legacy transaction for a page in the existing arena.");
    asm volatile("mov x0, %0\nmov x1, %1\nbrk #0x69" : : "r"(rx), "r"(probe_size) : "x0", "x1", "memory");
  }
  const std::ptrdiff_t writable_difference = Common::AllocateWritableRegionAndGetDiff(rx, probe_size);
  if (writable_difference == 0)
  {
    Log("jit.executable_probe_failed", "Dolphin returned no writable alias.");
    return false;
  }
  auto* rw = reinterpret_cast<std::uint32_t*>(reinterpret_cast<std::uint8_t*>(rx) + writable_difference);
  if (!HasMemoryPermissions(rx, 8, VM_PROT_READ | VM_PROT_EXECUTE) ||
      !HasMemoryPermissions(rw, 8, VM_PROT_READ | VM_PROT_WRITE))
  {
    Log("jit.executable_probe_failed", "The RX page or writable alias lacks required VM protections.");
    Common::FreeExecutableMemory(rx, probe_size);
    return false;
  }
  g_jit_handshake = true;
  g_arena_established = true;
  Log("jit.legacy_handshake_validated", "Legacy breakpoint returned; RX/RW mappings passed VM protection checks.");
  rw[0] = 0x52800540; // mov w0, #42
  rw[1] = 0xD65F03C0; // ret
  sys_dcache_flush(rw, 2 * sizeof(std::uint32_t));
  sys_icache_invalidate(rx, 2 * sizeof(std::uint32_t));
  using Probe = int (*)();
  const int value = reinterpret_cast<Probe>(rx)();
  Common::FreeExecutableMemory(rx, probe_size);
  if (value != 42)
  {
    Log("jit.executable_probe_failed", "Generated ARM64 code returned an unexpected value.");
    return false;
  }
  g_executable_probe = true;
  Log("jit.executable_probe_passed", "Generated ARM64 code executed and returned 42.");
  return true;
#endif
}
} // namespace

// DiscIO metadata works before core/JIT initialization, including RVZ/WBFS/WAD.
// The returned identity is never based on the selected file's display name.
extern "C" __attribute__((visibility("default")))
char* neostation_dolphin_save_identity(const char* game_path, const char* expected_system)
{
  if (!game_path || !expected_system) return nullptr;
  const std::string system(expected_system);
  if (system != "gc" && system != "wii") return nullptr;
  try
  {
    const auto volume = DiscIO::CreateVolume(std::string(game_path));
    if (!volume || !ExpectedPlatform(volume->GetVolumeType(), system)) return nullptr;
    NSString* region = @"unknown";
    switch (volume->GetRegion())
    {
    case DiscIO::Region::NTSC_J: region = @"JAP"; break;
    case DiscIO::Region::NTSC_U: region = @"USA"; break;
    case DiscIO::Region::PAL: region = @"EUR"; break;
    default: break;
    }
    NSMutableDictionary* identity = [@{
      @"system": [NSString stringWithUTF8String:expected_system],
      @"gameId": [NSString stringWithUTF8String:volume->GetGameID().c_str()] ?: @"",
      @"region": region
    } mutableCopy];
    if (const auto title_id = volume->GetTitleID())
      identity[@"titleId"] = [NSString stringWithFormat:@"%016llx", static_cast<unsigned long long>(*title_id)];
    NSData* data = [NSJSONSerialization dataWithJSONObject:identity options:0 error:nil];
    if (!data) return nullptr;
    NSString* json = [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];
    return json ? strdup(json.UTF8String) : nullptr;
  }
  catch (...) { return nullptr; }
}

extern "C" __attribute__((visibility("default")))
int32_t neostation_dolphin_initialize(const char* user_directory, const char* system_directory, const char* log_path)
{
  std::lock_guard<std::mutex> lock(g_state_mutex);
  if (g_initialized) return 1;
  if (!user_directory || !system_directory || !*user_directory || !*system_directory) return 0;
  g_user_directory = user_directory;
  g_system_directory = system_directory;
  g_log_path = log_path == nullptr ? "" : log_path;
  g_cleanup_started = false;
  ResetSessionFlags();
  try
  {
    DeclareMainAsHostThread();
    UICommon::SetUserDirectory(g_user_directory);
    UICommon::CreateDirectories();
    UICommon::Init();
    ApplyConsolePreferences();
    WindowSystemInfo controller_wsi;
    controller_wsi.type = WindowSystemType::iOS;
    UICommon::InitControllers(controller_wsi);
    g_devices_callback = g_controller_interface.RegisterDevicesChangedCallback([] {
      // Backend notifications can run on Apple's main queue. Never mutate
      // profiles or wait for the host queue from that callback.
      g_devices_changed = true;
    });
    g_devices_changed = true;
    ConfigurePhysicalControllers();
    DolphinAnalytics::Instance().ReportDolphinStart("neostation-ios");
    g_initialized = true;
    Log("core.initialized", "Embedded Dolphin initialized in NeoStation.");
    return 1;
  }
  catch (...)
  {
    Log("core.initialize_failed", "Exception during embedded Dolphin initialization.");
    return 0;
  }
}

extern "C" __attribute__((visibility("default")))
int32_t neostation_dolphin_validate_image(const char* game_path, const char* expected_system, const char* log_path)
{
  if (log_path) g_log_path = log_path;
  if (!g_initialized || !game_path || !expected_system) return 0;
  const std::string path(game_path), system(expected_system);
  if (system != "gc" && system != "wii")
  {
    Log("image.route_rejected", "Dolphin route is not GameCube/Wii.");
    return 0;
  }
  std::unique_ptr<DiscIO::Volume> volume = DiscIO::CreateVolume(path);
  if (!volume)
  {
    Log("image.open_failed", "DiscIO could not open the selected image.");
    return 0;
  }
  if (!ExpectedPlatform(volume->GetVolumeType(), system))
  {
    Log("image.platform_mismatch", "Image platform does not match the selected playlist.");
    return 0;
  }
  g_validated_game = path;
  g_validated_system = system;
  Log("image.validated", "DiscIO validated the selected GameCube/Wii image.");
  return 1;
}

extern "C" __attribute__((visibility("default")))
int32_t neostation_dolphin_prepare_legacy_jit(const char* log_path)
{
  if (log_path) g_log_path = log_path;
  if (!g_initialized || g_validated_game.empty())
  {
    Log("jit.precondition_failed", "Core or image validation is incomplete.");
    return 0;
  }
  bool probe_ok = false;
  try { probe_ok = RunExecutableProbe(); }
  catch (...) { Log("jit.executable_probe_failed", "Exception during executable-memory validation."); }
  int32_t flags = 0;
  if (g_jit_handshake) flags |= 0x1;
  if (probe_ok && g_executable_probe) flags |= 0x2;
  return flags;
}

extern "C" __attribute__((visibility("default")))
int32_t neostation_dolphin_launch(const char* game_path, const char* expected_system,
                                  void* metal_layer, double metal_scale, const char* log_path)
{
  if (log_path) g_log_path = log_path;
  if (!g_initialized || !g_jit_handshake || !g_executable_probe || !game_path || !expected_system || !metal_layer)
  {
    Log("launch.precondition_failed", "One or more strict Dolphin launch gates are incomplete.");
    return 0;
  }
  const std::string path(game_path), system_name(expected_system);
  if (path != g_validated_game || system_name != g_validated_system || (system_name != "gc" && system_name != "wii"))
  {
    Log("launch.image_changed", "The game or system changed after validation.");
    return 0;
  }
  __block bool booted = false;
  __block WindowSystemInfo wsi;
  wsi.type = WindowSystemType::iOS;
  wsi.render_surface = metal_layer;
  wsi.render_surface_scale = metal_scale > 0.0 ? metal_scale : 1.0;
  g_metal_surface = metal_layer;
  g_metal_scale = wsi.render_surface_scale;
  UndeclareMainAsHostThread();
  DOLHostQueueRunSync(^{
    ApplyConsolePreferences();
    ConfigurePhysicalControllers();
    SConfig::GetInstance().bBootToPause = true;
    Config::SetBase(Config::MAIN_CPU_CORE, PowerPC::CPUCore::JITARM64);
    Config::SetBase(Config::MAIN_GFX_BACKEND, std::string("Metal"));
    Config::SetBase(Config::GFX_VERTEX_LOADER_TYPE, VertexLoaderType::Native);
    if (!SelectRegionalIPL(path)) return;
    std::unique_ptr<BootParameters> boot = BootParameters::GenerateFromFile(path);
    if (boot) booted = BootManager::BootCore(Core::System::GetInstance(), std::move(boot), wsi);
  });
  if (!booted || !WaitForCoreToLeaveStarting(std::chrono::seconds(30)))
  {
    Log("core.boot_failed", "BootManager did not start the selected image.");
    ShutdownRuntime("boot_failed");
    return 0;
  }
  int32_t flags = 0;
  if (Core::IsRunning(Core::System::GetInstance()) &&
      Config::Get(Config::MAIN_CPU_CORE) == PowerPC::CPUCore::JITARM64 &&
      Core::System::GetInstance().GetJitInterface().GetCore() != nullptr &&
      std::strcmp(Core::System::GetInstance().GetPowerPC().GetCPUName(), "JITARM64") == 0)
  {
    flags |= 0x1;
    Log("jit.jitarm64_initialized", "Dolphin reports an initialized JITARM64 CPU core.");
  }
  else Log("jit.jitarm64_failed", "JITARM64 was not initialized; interpreter fallback is blocked.");
  if (g_presenter != nullptr && Core::IsRunning(Core::System::GetInstance()) &&
      Config::Get(Config::MAIN_GFX_BACKEND) == "Metal")
  {
    flags |= 0x2;
    Log("metal.initialized", "Dolphin Metal presenter initialized on NeoStation CAMetalLayer.");
  }
  else Log("metal.initialize_failed", "Dolphin did not create a Metal presenter.");
  if ((flags & 0x3) == 0x3 && Core::IsRunning(Core::System::GetInstance()))
  {
    flags |= 0x4;
    g_boot_language = system_name == "wii" ? static_cast<int>(Config::Get(Config::SYSCONF_LANGUAGE)) : Config::Get(Config::MAIN_GC_LANGUAGE);
    g_running = true;
    Log("game.submitted", "Validated game submitted to the embedded core.");
    DOLHostQueueRunSync(^{ Core::SetState(Core::System::GetInstance(), Core::State::Running); });
    Log("launch.authorized", "JITARM64 and Metal validated while paused; CPU execution now released.");
  }
  else ShutdownRuntime("strict_launch_gate_failed");
  return flags;
}

extern "C" __attribute__((visibility("default")))
int32_t neostation_dolphin_is_running(void)
{
  return g_running && Core::IsRunning(Core::System::GetInstance()) ? 1 : 0;
}
extern "C" __attribute__((visibility("default")))
int32_t neostation_dolphin_set_paused(int32_t paused)
{
  if (!g_running) return 0;
  Log("menu.pause.begin", paused ? "Pause requested." : "Resume requested.");
  DOLHostQueueRunSync(^{ Core::SetState(Core::System::GetInstance(), paused ? Core::State::Paused : Core::State::Running); });
  const bool success = Core::GetState(Core::System::GetInstance()) ==
      (paused ? Core::State::Paused : Core::State::Running);
  Log("menu.pause.complete", success ? "State change completed." : "State change rejected.");
  return success ? 1 : 0;
}
namespace
{
struct DOLControlEntry
{
  std::string id;
  std::string group;
  ControllerEmu::Control* control;
};

void DOLCollectControls(ControllerEmu::ControlGroupContainer* container,
                        const std::string& prefix, std::vector<DOLControlEntry>& output)
{
  if (!container) return;
  for (const auto& group : container->groups)
  {
    if (!group) continue;
    const auto group_id = prefix + group->name + "/";
    for (const auto& control : group->controls)
    {
      if (control && control->control_ref && control->control_ref->IsInput())
        output.push_back({group_id + control->name, prefix + group->ui_name, control.get()});
    }
    if (group->type == ControllerEmu::GroupType::Attachments)
    {
      const auto* attachments = static_cast<ControllerEmu::Attachments*>(group.get());
      for (const auto& attachment : attachments->GetAttachmentList())
        DOLCollectControls(attachment.get(), group_id + attachment->GetName() + "/", output);
    }
  }
}

InputConfig* DOLInputConfig(bool wii) { return wii ? Wiimote::GetConfig() : Pad::GetConfig(); }
NSString* DOLString(const std::string& text)
{
  return [NSString stringWithUTF8String:text.c_str()] ?: @"";
}

// NEOSTATION_SESSION_HELPERS

template <typename T>
void DOLSetGraphics(const Config::Info<T>& info, T value)
{
  // Update the current session even when a game INI overrides the base value,
  // and save the user's choice in the normal Dolphin configuration.
  Config::SetBase(info, value);
  Config::SetCurrent(info, value);
}
}

extern "C" __attribute__((visibility("default")))
char* neostation_dolphin_menu_snapshot(int32_t wii, int32_t slot)
{
  if (!g_running || slot < -1 || slot > 3) return nullptr;
  Log("menu.snapshot.begin", slot < 0 ? "Console/graphics settings." : "Controller settings.");
  __block char* result = nullptr;
  DOLHostQueueRunSync(^{
    @autoreleasepool {
    @try {
    ConfigurePhysicalControllers();
    auto lock = ControllerEmu::EmulatedController::GetStateLock();
    InputConfig* config = DOLInputConfig(wii != 0);
    auto* controller = config && slot >= 0 && slot < config->GetControllerCount() ? config->GetController(slot) : nullptr;
    if (slot >= 0 && !controller) return;
    std::vector<DOLControlEntry> entries;
    DOLCollectControls(controller, "", entries);
    NSMutableArray* controls = [NSMutableArray array];
    for (const auto& entry : entries)
      [controls addObject:@{@"id": DOLString(entry.id), @"group": DOLString(entry.group),
        @"name": DOLString(entry.control->ui_name),
        @"expression": DOLString(entry.control->control_ref->GetExpression())}];

    NSMutableArray* devices = [NSMutableArray array];
    if (slot >= 0) for (const auto& device : g_controller_interface.GetAllDevices())
    {
      ciface::Core::DeviceQualifier qualifier;
      qualifier.FromDevice(device.get());
      NSMutableArray* inputs = [NSMutableArray array];
      for (const auto* input : device->Inputs())
      {
        const std::string qualified = qualifier.ToString() + ":" + input->GetName();
        if (qualified.find('`') != std::string::npos) continue;
        [inputs addObject:@{@"name": DOLString(input->GetName()),
          @"expression": DOLString("`" + qualified + "`")}];
      }
      [devices addObject:@{@"name": DOLString(qualifier.ToString()), @"inputs": inputs}];
    }
    NSMutableArray* extensions = [NSMutableArray array];
    if (controller) for (const auto& group : controller->groups)
    {
      if (group->type != ControllerEmu::GroupType::Attachments) continue;
      const auto* attachments = static_cast<ControllerEmu::Attachments*>(group.get());
      int index = 0;
      for (const auto& attachment : attachments->GetAttachmentList())
      {
        [extensions addObject:@{@"group": DOLString(group->name), @"index": @(index),
          @"name": DOLString(attachment->GetDisplayName()),
          @"selected": @(index == static_cast<int>(attachments->GetSelectedAttachment()))}];
        ++index;
      }
    }
    NSMutableArray* languages = [NSMutableArray array];
    NSArray* names = @[@"日本語", @"English", @"Deutsch", @"Français", @"Español", @"Italiano", @"Nederlands", @"简体中文", @"繁體中文", @"한국어"];
    const int language = wii ? static_cast<int>(Config::Get(Config::LayerType::Base, Config::SYSCONF_LANGUAGE)) : Config::Get(Config::LayerType::Base, Config::MAIN_GC_LANGUAGE);
    for (int index = 0; index < (wii ? 10 : 6); ++index)
      [languages addObject:@{@"name": names[wii ? index : index + 1], @"value": @(index), @"selected": @(index == language)}];
    NSDictionary* snapshot = @{
      @"console": @{@"language": @(language), @"languages": languages,
        @"restartNeeded": @(language != g_boot_language.load())},
      @"device": controller ? DOLString(controller->GetDefaultDevice().ToString()) : @"",
      @"graphics": @{@"resolution": @(Config::Get(Config::GFX_EFB_SCALE)),
        @"aspect": @(static_cast<int>(Config::Get(Config::GFX_ASPECT_RATIO))),
        @"vsync": @(Config::Get(Config::GFX_VSYNC)),
        @"anisotropy": @(static_cast<int>(Config::Get(Config::GFX_ENHANCE_MAX_ANISOTROPY)))},
      @"controls": controls, @"devices": devices, @"extensions": extensions,
    };
    NSData* json = [NSJSONSerialization dataWithJSONObject:snapshot options:0 error:nil];
    NSString* text = json ? [[NSString alloc] initWithData:json encoding:NSUTF8StringEncoding] : nil;
    // Copy bytes before leaving the host queue/autorelease pool. No Objective-C
    // object crosses this C ABI or depends on a queue's autorelease lifetime.
    if (text.UTF8String) result = strdup(text.UTF8String);
    } @catch (NSException* exception) {
      Log("menu.snapshot.exception", "Could not encode the requested settings.");
    }
    }
  });
  Log("menu.snapshot.complete", result ? "Settings copied." : "Settings unavailable.");
  return result;
}

extern "C" __attribute__((visibility("default")))
int32_t neostation_dolphin_menu_apply(const char* request_json)
{
  if (!g_running || !request_json) return 0;
  NSData* data = [[NSString stringWithUTF8String:request_json] dataUsingEncoding:NSUTF8StringEncoding];
  NSDictionary* request = [NSJSONSerialization JSONObjectWithData:data options:0 error:nil];
  if (![request isKindOfClass:NSDictionary.class]) return 0;
  __block bool success = false;
  DOLHostQueueRunSync(^{
    if ([request[@"kind"] isEqual:@"graphics"])
    {
      const int value = [request[@"value"] intValue];
      NSString* key = request[@"key"];
      if ([key isEqual:@"resolution"] && value >= 1 && value <= 4)
        DOLSetGraphics(Config::GFX_EFB_SCALE, value);
      else if ([key isEqual:@"aspect"] && value >= 0 && value <= 3)
        DOLSetGraphics(Config::GFX_ASPECT_RATIO, static_cast<AspectMode>(value));
      else if ([key isEqual:@"vsync"] && value >= 0 && value <= 1)
        DOLSetGraphics(Config::GFX_VSYNC, value != 0);
      else if ([key isEqual:@"anisotropy"] && value >= -1 && value <= 4)
        DOLSetGraphics(Config::GFX_ENHANCE_MAX_ANISOTROPY, static_cast<AnisotropicFilteringMode>(value));
      else return;
      Config::Save();
      success = true;
      return;
    }
    if ([request[@"kind"] isEqual:@"language"])
    {
      const bool wii = [request[@"wii"] boolValue];
      if (![request[@"value"] isKindOfClass:NSNumber.class]) return;
      const int value = [request[@"value"] intValue];
      if (value < 0 || value > (wii ? 9 : 5)) return;
      Common::IniFile preferences;
      preferences.Load(SessionPreferencesPath());
      preferences.GetOrCreateSection("Console")->Set(wii ? "WiiLanguage" : "GCLanguage", value);
      if (!preferences.Save(SessionPreferencesPath())) return;
      if (wii) DOLSetGraphics(Config::SYSCONF_LANGUAGE, static_cast<u32>(value));
      else DOLSetGraphics(Config::MAIN_GC_LANGUAGE, value);
      Config::Save();
      success = true;
      return;
    }
    const int slot = [request[@"slot"] intValue];
    if (slot < 0 || slot > 3) return;
    const Core::CPUThreadGuard cpu_guard(Core::System::GetInstance());
    auto lock = ControllerEmu::EmulatedController::GetStateLock();
    InputConfig* config = DOLInputConfig([request[@"wii"] boolValue]);
    if (!config || slot >= config->GetControllerCount()) return;
    auto* controller = config->GetController(slot);
    if (!controller) return;
    if ([request[@"kind"] isEqual:@"device"])
    {
      if (![request[@"device"] isKindOfClass:NSString.class]) return;
      success = SelectInputProfile([request[@"wii"] boolValue], slot, [request[@"device"] UTF8String]);
      return;
    }
    if ([request[@"kind"] isEqual:@"binding"])
    {
      if (![request[@"id"] isKindOfClass:NSString.class] ||
          ![request[@"expression"] isKindOfClass:NSString.class]) return;
      const std::string id = [request[@"id"] UTF8String];
      const std::string expression = [request[@"expression"] UTF8String];
      std::vector<DOLControlEntry> entries;
      DOLCollectControls(controller, "", entries);
      for (const auto& entry : entries)
      {
        if (entry.id != id) continue;
        const auto previous = entry.control->control_ref->GetExpression();
        if (entry.control->control_ref->SetExpression(expression).has_value())
        {
          entry.control->control_ref->SetExpression(previous);
          return;
        }
        controller->UpdateReferences(g_controller_interface);
        config->SaveConfig();
        StoreInputProfile([request[@"wii"] boolValue], slot);
        success = true;
        return;
      }
    }
    else if ([request[@"kind"] isEqual:@"extension"])
    {
      const int index = [request[@"index"] intValue];
      for (const auto& group : controller->groups)
      {
        if (group->type != ControllerEmu::GroupType::Attachments ||
            ![DOLString(group->name) isEqual:request[@"group"]]) continue;
        auto* attachments = static_cast<ControllerEmu::Attachments*>(group.get());
        if (index < 0 || index >= static_cast<int>(attachments->GetAttachmentList().size())) return;
        attachments->SetSelectedAttachment(index);
        controller->UpdateReferences(g_controller_interface);
        config->SaveConfig();
        StoreInputProfile([request[@"wii"] boolValue], slot);
        success = true;
        return;
      }
    }
  });
  return success ? 1 : 0;
}

extern "C" __attribute__((visibility("default")))
int32_t neostation_dolphin_restart(void)
{
  if (!g_initialized || !g_running || !g_metal_surface) return 0;
  const std::string game = g_validated_game, system_name = g_validated_system;
  void* surface = g_metal_surface;
  const double scale = g_metal_scale;
  Log("session.restart.begin", "Stopping the console before applying saved settings.");
  g_running = false;
  DOLHostQueueRunSync(^{
    auto& system = Core::System::GetInstance();
    Core::Stop(system);
    Core::Shutdown(system);
    ApplyConsolePreferences();
    Config::Save();
  });
  // Keep the initialized process and the verified legacy JIT authorization.
  // Boot still enforces JITARM64 and Metal before releasing CPU execution.
  const int32_t flags = neostation_dolphin_launch(game.c_str(), system_name.c_str(), surface, scale, nullptr);
  Log("session.restart.complete", (flags & 7) == 7 ? "Console restarted." : "Restart failed.");
  return (flags & 7) == 7 ? 1 : 0;
}

extern "C" __attribute__((visibility("default")))
int32_t neostation_dolphin_refresh_controllers(void)
{
  if (!g_initialized || !g_running) return 0;
  __block int32_t layout = 1;
  DOLHostQueueRunSync(^{
    ConfigurePhysicalControllers();
    auto lock = ControllerEmu::EmulatedController::GetStateLock();
    auto* config = Wiimote::GetConfig();
    if (!config || config->GetControllerCount() == 0) return;
    for (const auto& group : config->GetController(0)->groups)
    {
      if (group->type != ControllerEmu::GroupType::Attachments) continue;
      auto* attachments = static_cast<ControllerEmu::Attachments*>(group.get());
      const auto index = attachments->GetSelectedAttachment();
      if (index < attachments->GetAttachmentList().size() &&
          attachments->GetAttachmentList()[index]->GetName() == "Classic") layout = 2;
    }
  });
  return layout;
}

extern "C" __attribute__((visibility("default")))
void neostation_dolphin_touch_event(int32_t controller, int32_t input, float value, int32_t axis)
{
  if (controller < 0 || controller > 7 || input < 0 || input > 905 || !std::isfinite(value)) return;
  if (!g_initialized || !g_running) return;
  auto lock = ControllerEmu::EmulatedController::GetStateLock();
  if (!g_initialized || !g_running) return;
  auto* manager = ciface::iOS::StateManager::GetInstance();
  if (axis) manager->SetAxisValue(controller, static_cast<ciface::iOS::ButtonType>(input), std::clamp(value, -1.0f, 1.0f));
  else manager->SetButtonPressed(controller, static_cast<ciface::iOS::ButtonType>(input), value != 0);
}

extern "C" __attribute__((visibility("default")))
void neostation_dolphin_release_touches(void)
{
  // UIKit notifications can arrive during shutdown. Do not wait on input
  // locks once the session has stopped accepting touch events.
  if (!g_initialized || !g_running) return;
  auto lock = ControllerEmu::EmulatedController::GetStateLock();
  if (g_initialized && g_running) ciface::iOS::StateManager::GetInstance()->Init();
}

extern "C" __attribute__((visibility("default")))
int32_t neostation_dolphin_stop(const char* log_path)
{
  if (log_path) g_log_path = log_path;
  if (!g_initialized) return 1;
  ShutdownRuntime("host_stop");
  return 1;
}
'''


BRIDGE_SOURCE = BRIDGE_SOURCE.replace('// NEOSTATION_SESSION_HELPERS',
    (Path(__file__).resolve().parents[1] / 'packages/dolphin_internal_bridge/core/NeoStationSession.inc').read_text())

def replace_once(path: Path, old: str, new: str, description: str) -> None:
    text = path.read_text(encoding='utf-8')
    count = text.count(old)
    if count == 0 and new in text:
        return
    if count != 1:
        raise SystemExit(f'{description}: expected one anchor in {path}, got {count}')
    path.write_text(text.replace(old, new, 1), encoding='utf-8')


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument('dolphin_root', type=Path)
    root = parser.parse_args().dolphin_root.resolve()
    cmake = root / 'Source/iOS/Library/CMakeLists.txt'
    memory = root / 'Source/Core/Common/MemoryUtil_iOS_LuckTXM.cpp'
    bridge = root / 'Source/iOS/Library/NeoStationBridge.mm'
    if not cmake.is_file() or not memory.is_file():
        raise SystemExit('Not a compatible pinned dolphin-ios checkout')
    replace_once(cmake, '  HostQueue.mm\n)', '  HostQueue.mm\n  NeoStationBridge.mm\n)', 'add NeoStation bridge')
    definition = 'target_compile_definitions(dolphin PRIVATE NEOSTATION_INTERNAL_DOLPHIN=1)'
    text = cmake.read_text()
    if definition not in text:
        cmake.write_text(text + '\n' + definition + '\n')
    replace_once(memory, '  if (!rx_ptr)\n', '  if (rx_ptr == MAP_FAILED)\n', 'mmap failure detection')
    bridge.write_text(BRIDGE_SOURCE, encoding='utf-8')
    updated = memory.read_text()
    required = ('brk #0x69', '"mov x0, %0\\n"', '"mov x1, %1\\n"', 'if (rx_ptr == MAP_FAILED)')
    if any(needle not in updated for needle in required):
        raise SystemExit('Pinned legacy allocator protocol changed')
    if 'JIT26PrepareRegion' in updated or 'brk #0xf00d' in updated:
        raise SystemExit('Unexpected JIT ABI in the Dolphin legacy allocator')
    import re
    for header in re.findall(r'^#include "([^"]+)"', BRIDGE_SOURCE, re.MULTILINE):
        if not any((base / header).is_file() for base in (root / 'Source/Core', root / 'Source/iOS/Library')):
            raise SystemExit(f'Pinned Dolphin header is absent: {header}')
    print('Patched pinned Dolphin JITARM64/Metal runtime.')


if __name__ == '__main__':
    main()
