#!/usr/bin/env python3
"""Generate the production CMake target with controlled dependency locations.

Checks dependency-header propagation and source-specific ARC flags, without
compiling an emulator or claiming iOS/device validation.
"""
from pathlib import Path
import json
import argparse
import os
import platform
import shlex
import subprocess
import sys
import tempfile

ROOT=Path(__file__).resolve().parents[1]
parser=argparse.ArgumentParser(description=__doc__)
parser.add_argument('--upstream',type=Path,required=True)
args=parser.parse_args()
with tempfile.TemporaryDirectory(prefix='armsx2-cmake-') as directory:
    fixture=Path(directory)
    upstream=fixture/'upstream'
    source=upstream/'platforms/ios/app/src/main/cpp'
    adapter=fixture/'packages/armsx2_internal_bridge'
    build=fixture/'build'
    zstd=fixture/'relocated-zstd/include'
    zstd.mkdir(parents=True)
    for path in [source/'ios_main.mm',source/'IOS/GamepadHaptics.mm',
                 source/'IOS/HostImpls.mm',source/'IOS/PlaySoundAsync.mm',
                 source/'IOS/ARMSX2GameView.h',source/'ARMSX2Bridge.mm',
                 adapter/'core/ARMSX2Core.mm',adapter/'core/exports.txt',
                 upstream/'bin/resources-overlay/armsx2_overrides.yaml',
                 source.parent/'assets/resources/patches.zip']:
        path.parent.mkdir(parents=True,exist_ok=True)
        path.write_text('')
    target=ROOT/'packages/armsx2_internal_bridge/core/target.cmake'
    cmake=f'''
cmake_minimum_required(VERSION 3.20)
project(ARMSX2BuildContract LANGUAGES CXX)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
set(NEO_ARMSX2_ADAPTER_DIR "{adapter}")
set(NEO_ARMSX2_SOURCE_REVISION test-revision)
set(ARMSX2_ROOT "{upstream}")
set(ARMSX2_HAVE_LIBRASHADER TRUE)
foreach(name PCSX2 PCSX2_FLAGS librashader)
  add_library(${{name}} INTERFACE)
endforeach()
add_library(SDL3::SDL3 INTERFACE IMPORTED)
add_library(Zstd::Zstd INTERFACE IMPORTED)
set_property(TARGET Zstd::Zstd PROPERTY INTERFACE_INCLUDE_DIRECTORIES "{zstd}")
include("{target}")
# This fixture generates compiler arguments; none of the dummy sources is built.
set_source_files_properties(ios_main.mm IOS/GamepadHaptics.mm IOS/HostImpls.mm
  IOS/PlaySoundAsync.mm ARMSX2Bridge.mm "{adapter}/core/ARMSX2Core.mm"
  PROPERTIES LANGUAGE CXX)
get_target_property(owned_link_options ARMSX2Core LINK_OPTIONS)
file(WRITE "{fixture}/link-options.txt" "${{owned_link_options}}")
'''
    (source/'CMakeLists.txt').write_text(cmake)
    subprocess.run(['cmake','-S',str(source),'-B',str(build),'-G','Unix Makefiles'],
                   check=True,stdout=subprocess.PIPE,stderr=subprocess.STDOUT,text=True)
    commands=json.loads((build/'compile_commands.json').read_text())
    def flags(name):
        entries=[entry for entry in commands if Path(entry['file']).name==name]
        assert len(entries)==1,(name,entries)
        return shlex.split(entries[0]['command'])
    bridge=flags('ARMSX2Bridge.mm')
    assert str(zstd) in bridge or '-I'+str(zstd) in bridge
    assert bridge.index('-fobjc-arc')>bridge.index('-fno-objc-arc'),bridge
    for name in ('ARMSX2Core.mm','ios_main.mm','HostImpls.mm'):
        assert '-fobjc-arc' not in flags(name),name
    assert '-fexceptions' in flags('ARMSX2Core.mm')
    linker=(fixture/'link-options.txt').read_text().split(';')
    oso=[option for option in linker if option.startswith('LINKER:-oso_prefix,')]
    assert oso==['LINKER:-oso_prefix,'+str(fixture)+'/'],oso
    if platform.system()=='Darwin':
        # Reproduce an absolute archive/member debug-map path with a tiny native
        # library, then apply the actual option generated by the Core target.
        objects=fixture/'archive-origin';objects.mkdir()
        unit=objects/'fixture.c';unit.write_text('int neo_fixture_value(void) { return 7; }\n')
        obj=objects/'fixture.o';archive=objects/'libfixture.a'
        subprocess.run(['xcrun','clang','-g','-fdebug-prefix-map='+str(fixture)+'=/fixture','-c',str(unit),'-o',str(obj)],check=True)
        subprocess.run(['xcrun','ar','rcs',str(archive),str(obj)],check=True)
        for suffix,extra in [('original',[]),('mapped',['-Wl,'+oso[0].removeprefix('LINKER:')])]:
            binary=fixture/(suffix+'.dylib')
            subprocess.run(['xcrun','clang','-dynamiclib','-Wl,-all_load',str(archive),*extra,'-o',str(binary)],check=True)
            contains=str(fixture).encode() in binary.read_bytes()
            assert contains==(suffix=='original'),suffix
print('PASS: native linker removes absolute archive debug-map origins' if platform.system()=='Darwin' else 'PASS: production linker option generated; native behavior requires macOS')
print('PASS: production CMake propagates relocated Zstandard headers; ARC applies only to the 2.6 bridge')

# Generate the actual patched cargo command, then run it with host flags removed
# from the build environment, as happens across Xcode's script-phase boundary.
module=(args.upstream/'platforms/ios/app/src/main/cpp/3rdparty/librashader/CMakeLists.txt').read_text()
start=module.index('set(_lrs_out_dir ')
end=module.index('set(ARMSX2_HAVE_LIBRASHADER ON PARENT_SCOPE)',start)
with tempfile.TemporaryDirectory(prefix='armsx2-cargo-env-') as directory:
    fixture=Path(directory);build=fixture/'build';source=fixture/'source'
    source.mkdir();(source/'include').mkdir()
    cargo=fixture/'cargo'
    cargo.write_text('#!'+sys.executable+'\n'+r'''
import json,os,sys
from pathlib import Path
arguments=sys.argv[1:]
target=Path(arguments[arguments.index('--target-dir')+1])
output=target/'aarch64-apple-ios/release/liblibrashader_capi.a'
output.parent.mkdir(parents=True,exist_ok=True);output.write_bytes(b'fixture')
(target/'environment.json').write_text(json.dumps({k:os.environ.get(k) for k in ('RUSTFLAGS','CFLAGS','CXXFLAGS','IPHONEOS_DEPLOYMENT_TARGET')}))
''')
    cargo.chmod(0o755)
    cmake=f'''
cmake_minimum_required(VERSION 3.20)
project(ARMSX2CargoEnvironment LANGUAGES NONE)
set(NEO_ARMSX2_ADAPTER_DIR "{ROOT}/packages/armsx2_internal_bridge")
set(ARMSX2_IOS_DEPLOYMENT_TARGET 18.0)
set(_lrs_rust_target aarch64-apple-ios)
set(librashader_src_SOURCE_DIR "{source}")
set(CARGO_EXECUTABLE "{cargo}")
'''+module[start:end]
    (fixture/'CMakeLists.txt').write_text(cmake)
    configured=os.environ.copy()
    expected={'RUSTFLAGS':'--remap-path-prefix=/Users/runner/example=/source',
              'CFLAGS':'-ffile-prefix-map=/Users/runner/example=/source -fmacro-prefix-map=/Users/runner/example=/source',
              'CXXFLAGS':'-ffile-prefix-map=/Users/runner/example=/source -fdebug-prefix-map=/Users/runner/example=/source'}
    configured.update(expected)
    subprocess.run(['cmake','-S',str(fixture),'-B',str(build),'-G','Unix Makefiles'],env=configured,check=True,stdout=subprocess.PIPE,stderr=subprocess.STDOUT,text=True)
    clean=os.environ.copy()
    for key in expected:clean.pop(key,None)
    subprocess.run(['cmake','--build',str(build),'--target','librashader_cargo'],env=clean,check=True,stdout=subprocess.PIPE,stderr=subprocess.STDOUT,text=True)
    seen=json.loads((build/'cargo/environment.json').read_text())
    assert all(seen[key]==value for key,value in expected.items()),seen
    assert seen['IPHONEOS_DEPLOYMENT_TARGET']=='18.0'
print('PASS: production cargo command preserves Rust and C/C++ path maps after the host environment is cleared')
