"""The generated iOS host must use Flutter's complete, locked plugin registry."""
from __future__ import annotations

import importlib.util
from pathlib import Path
import sys
import tempfile
import unittest
from unittest.mock import patch

ROOT = Path(__file__).resolve().parents[1]
CI = ROOT / 'packages/dolphin_internal_bridge/ci'
sys.path.insert(0, str(CI))
try:
    SPEC = importlib.util.spec_from_file_location('dolphin_build_support', CI / 'build_support.py')
    assert SPEC and SPEC.loader
    SUPPORT = importlib.util.module_from_spec(SPEC)
    SPEC.loader.exec_module(SUPPORT)
finally:
    sys.path.pop(0)


class DolphinRegistrantTests(unittest.TestCase):
    def test_uses_flutter_after_scaffolding_and_keeps_lockfile_enforcement(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            ios = root / 'ios'
            runner = ios / 'Runner'
            runner.mkdir(parents=True)
            SUPPORT.write_plist(runner / 'Info.plist', {'CFBundleIdentifier': 'com.neogamelab.neostation'})
            (ios / 'Podfile').write_text('# Existing CocoaPods configuration\n')
            def command(*args):
                if args[:3] == ('flutter', 'pub', 'get'):
                    self.assertTrue(runner.is_dir())
                    self.assertIn('--enforce-lockfile', args)
                    # Test-only output of the mocked Flutter command. Production
                    # sources are always generated by Flutter, never by this test.
                    for name in ('GeneratedPluginRegistrant.h', 'GeneratedPluginRegistrant.m'):
                        (runner / name).write_text('// Test-only registrant output\n')
            with patch.object(SUPPORT, 'ROOT', root), patch.object(SUPPORT, 'run', side_effect=command) as run:
                SUPPORT.scaffold()
                run.assert_any_call('flutter', 'pub', 'get', '--enforce-lockfile')
                run.assert_any_call('git', 'diff', '--exit-code', '--', 'pubspec.yaml', 'pubspec.lock')
            self.assertEqual((ios / 'Podfile').read_text(), '# Existing CocoaPods configuration\n')

    def test_rejects_missing_or_empty_registrant(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            ios = Path(temporary)
            (ios / 'Runner').mkdir()
            with patch.object(SUPPORT, 'run'):
                with self.assertRaisesRegex(ValueError, 'plugin registrant'):
                    SUPPORT.generate_plugin_registrant(ios)
                for name in ('GeneratedPluginRegistrant.h', 'GeneratedPluginRegistrant.m'):
                    (ios / 'Runner' / name).touch()
                with self.assertRaisesRegex(ValueError, 'plugin registrant'):
                    SUPPORT.generate_plugin_registrant(ios)


if __name__ == '__main__':
    unittest.main()
