/// Reviewed cores from the pinned RetroArch iOS donor IPA and supplements.
///
/// Each entry matches an App Store allowlisted, nonexperimental packaged
/// framework or a separately pinned supplemental build, plus an existing
/// NeoStation system definition. Unqualified hardware cores and missing
/// frameworks stay unavailable. PSP uses a separately pinned GLES build with
/// an interpreter profile because its framework is absent from the donor IPA.
/// N64 uses the donor GLES3 core with protected interpreter and GLideN64 options.
class RetroArchCoreDescriptor {
  const RetroArchCoreDescriptor({
    required this.identifier,
    required this.displayName,
    required this.frameworkStem,
    required this.systems,
    required this.validExtensions,
  });

  final String identifier;
  final String displayName;
  final String frameworkStem;
  final Set<String> systems;

  /// Exact supported_extensions from the pinned donor core information.
  final Set<String> validExtensions;
  String get uniqueId => 'ios_retroarch_internal:$identifier';
  String get frameworkName => '$frameworkStem.libretro.framework';
  String get executableName => '$frameworkStem.libretro';

  bool matchesIdentifier(String value) =>
      value == identifier ||
      value == uniqueId ||
      value == executableName ||
      value == frameworkName ||
      value == '${identifier}_libretro' ||
      value == '${identifier}_libretro.so' ||
      value == '${identifier}_libretro.dll' ||
      value == '${identifier}_libretro.dylib';
}

abstract final class RetroArchCoreCatalog {
  static const supportedSystems = <String>{
    "2600",
    "32x",
    "3do",
    "5200",
    "7800",
    "a2",
    "a2001",
    "amiga",
    "arc",
    "ard",
    "c64",
    "chf",
    "cpc",
    "cps1",
    "cps2",
    "cps3",
    "cv",
    "dos",
    "ds",
    "duck",
    "fbneo",
    "fc",
    "fds",
    "gb",
    "gb-hacks",
    "gba",
    "gba-hacks",
    "gbc",
    "gbc-hacks",
    "gen-hacks",
    "genesis",
    "gg",
    "gg-hacks",
    "gw",
    "intv",
    "jag",
    "lynx",
    "mark3",
    "mcd",
    "md",
    "md-hacks",
    "mini",
    "mo2",
    "msx",
    'n64',
    "neogeo",
    "nes",
    "nes-hacks",
    "ngcd",
    "ngp",
    "ngpc",
    "palm",
    "pc98",
    "pccd",
    "pce",
    "pcfx",
    "pet",
    "pico",
    "plus4",
    "ps1",
    "psp",
    "pspminis",
    "rpgmaker",
    "sat",
    "satellaview",
    "scd",
    "scummvm",
    "sfc",
    "sfc-hacks",
    "sg1k",
    "sharpx68000",
    "sms",
    "snes",
    "snes-hacks",
    "tg16",
    "tgcd",
    "uze",
    "vb",
    "vic20",
    "wasm4",
    "ws",
    "wsc",
    "wsv",
    "zxspectrum",
  };

  // Keep the first eleven smoke-test cores in their original order so
  // existing console defaults do not change when alternatives are added.
  static const cores = <RetroArchCoreDescriptor>[
    RetroArchCoreDescriptor(
      identifier: "fceumm",
      displayName: "FCEUmm",
      frameworkStem: "fceumm",
      systems: {"fc", "fds", "nes", "nes-hacks"},
      validExtensions: {"fds", "nes", "unf", "unif"},
    ),
    RetroArchCoreDescriptor(
      identifier: "nestopia",
      displayName: "Nestopia UE",
      frameworkStem: "nestopia",
      systems: {"fc", "fds", "nes", "nes-hacks"},
      validExtensions: {"fds", "nes", "nsf", "unf", "unif"},
    ),
    RetroArchCoreDescriptor(
      identifier: "snes9x",
      displayName: "Snes9x",
      frameworkStem: "snes9x",
      systems: {"satellaview", "sfc", "sfc-hacks", "snes", "snes-hacks"},
      validExtensions: {"bs", "fig", "sfc", "smc", "st", "swc"},
    ),
    RetroArchCoreDescriptor(
      identifier: "gambatte",
      displayName: "Gambatte",
      frameworkStem: "gambatte",
      systems: {"gb", "gb-hacks", "gbc", "gbc-hacks"},
      validExtensions: {"dmg", "gb", "gbc"},
    ),
    RetroArchCoreDescriptor(
      identifier: "sameboy",
      displayName: "SameBoy",
      frameworkStem: "sameboy",
      systems: {"gb", "gb-hacks", "gbc", "gbc-hacks"},
      validExtensions: {"gb", "gbc"},
    ),
    RetroArchCoreDescriptor(
      identifier: "mgba",
      displayName: "mGBA",
      frameworkStem: "mgba",
      systems: {"gb", "gb-hacks", "gba", "gba-hacks", "gbc", "gbc-hacks"},
      validExtensions: {"gb", "gba", "gbc"},
    ),
    RetroArchCoreDescriptor(
      identifier: "genesis_plus_gx",
      displayName: "Genesis Plus GX",
      frameworkStem: "genesis.plus.gx",
      systems: {
        "gen-hacks",
        "genesis",
        "gg",
        "gg-hacks",
        "mark3",
        "mcd",
        "md",
        "md-hacks",
        "pico",
        "scd",
        "sg1k",
        "sms",
      },
      validExtensions: {
        "68k",
        "bin",
        "bms",
        "chd",
        "cue",
        "gen",
        "gg",
        "iso",
        "m3u",
        "md",
        "mdx",
        "sg",
        "sgd",
        "smd",
        "sms",
      },
    ),
    RetroArchCoreDescriptor(
      identifier: "picodrive",
      displayName: "PicoDrive",
      frameworkStem: "picodrive",
      systems: {
        "32x",
        "gen-hacks",
        "genesis",
        "gg",
        "gg-hacks",
        "mark3",
        "mcd",
        "md",
        "md-hacks",
        "pico",
        "scd",
        "sms",
      },
      validExtensions: {
        "32x",
        "68k",
        "bin",
        "chd",
        "cue",
        "gen",
        "gg",
        "iso",
        "m3u",
        "md",
        "pco",
        "sc",
        "sg",
        "sgd",
        "smd",
        "sms",
      },
    ),
    RetroArchCoreDescriptor(
      identifier: "mednafen_pce_fast",
      displayName: "Beetle PCE Fast",
      frameworkStem: "mednafen.pce.fast",
      systems: {"pccd", "pce", "tg16", "tgcd"},
      validExtensions: {"ccd", "chd", "cue", "m3u", "pce", "toc"},
    ),
    RetroArchCoreDescriptor(
      identifier: "pcsx_rearmed",
      displayName: "PCSX ReARMed",
      frameworkStem: "pcsx.rearmed",
      systems: {"ps1"},
      validExtensions: {
        "bin",
        "cbn",
        "ccd",
        "chd",
        "cue",
        "exe",
        "img",
        "iso",
        "m3u",
        "mdf",
        "pbp",
        "toc",
      },
    ),
    RetroArchCoreDescriptor(
      identifier: "mednafen_psx",
      displayName: "Beetle PSX",
      frameworkStem: "mednafen.psx",
      systems: {"ps1"},
      validExtensions: {"bin", "ccd", "chd", "cue", "exe", "m3u", "pbp", "toc"},
    ),
    RetroArchCoreDescriptor(
      identifier: "DoubleCherryGB",
      displayName: "DoubleCherryGB",
      frameworkStem: "DoubleCherryGB",
      systems: {"gb", "gb-hacks", "gbc", "gbc-hacks"},
      validExtensions: {"cgb", "dmg", "gb", "gbc", "sgb"},
    ),
    RetroArchCoreDescriptor(
      identifier: "a5200",
      displayName: "a5200",
      frameworkStem: "a5200",
      systems: {"5200"},
      validExtensions: {"a52", "bin"},
    ),
    RetroArchCoreDescriptor(
      identifier: "amiarcadia",
      displayName: "AmiArcadia",
      frameworkStem: "amiarcadia",
      systems: {"a2001"},
      validExtensions: {"bin", "tvc"},
    ),
    RetroArchCoreDescriptor(
      identifier: "applewin",
      displayName: "applewin",
      frameworkStem: "applewin",
      systems: {"a2"},
      validExtensions: {
        "2img",
        "2mg",
        "apl",
        "bin",
        "do",
        "dsk",
        "gz",
        "hdv",
        "iie",
        "m3u",
        "nib",
        "po",
        "woz",
        "yaml",
        "zip",
      },
    ),
    RetroArchCoreDescriptor(
      identifier: "ardens",
      displayName: "Ardens",
      frameworkStem: "ardens",
      systems: {"ard"},
      validExtensions: {"arduboy", "hex"},
    ),
    RetroArchCoreDescriptor(
      identifier: "atari800",
      displayName: "Atari800",
      frameworkStem: "atari800",
      systems: {"5200"},
      validExtensions: {
        "a52",
        "atr",
        "atx",
        "bin",
        "car",
        "cas",
        "com",
        "dcm",
        "m3u",
        "rom",
        "xex",
        "xfd",
        "zip",
      },
    ),
    RetroArchCoreDescriptor(
      identifier: "bluemsx",
      displayName: "blueMSX",
      frameworkStem: "bluemsx",
      systems: {"cv", "msx", "sg1k"},
      validExtensions: {
        "cas",
        "col",
        "dsk",
        "m3u",
        "mx1",
        "mx2",
        "ri",
        "rom",
        "sc",
        "sf",
        "sg",
      },
    ),
    RetroArchCoreDescriptor(
      identifier: "bsnes",
      displayName: "bsnes",
      frameworkStem: "bsnes",
      systems: {
        "gb",
        "gbc",
        "satellaview",
        "sfc",
        "sfc-hacks",
        "snes",
        "snes-hacks",
      },
      validExtensions: {"bs", "fig", "gb", "gbc", "sfc", "smc", "swc"},
    ),
    RetroArchCoreDescriptor(
      identifier: "bsnes-jg",
      displayName: "bsnes-jg",
      frameworkStem: "bsnes-jg",
      systems: {"satellaview", "sfc", "sfc-hacks", "snes", "snes-hacks"},
      validExtensions: {"bs", "gb", "gbc", "sfc", "smc", "st"},
    ),
    RetroArchCoreDescriptor(
      identifier: "cap32",
      displayName: "Caprice32",
      frameworkStem: "cap32",
      systems: {"cpc"},
      validExtensions: {"cdt", "cpr", "dsk", "m3u", "sna", "tap", "voc", "zip"},
    ),
    RetroArchCoreDescriptor(
      identifier: "clownmdemu",
      displayName: "ClownMDEmu",
      frameworkStem: "clownmdemu",
      systems: {"gen-hacks", "genesis", "mcd", "md", "md-hacks", "scd"},
      validExtensions: {"bin", "chd", "cue", "gen", "iso", "md"},
    ),
    RetroArchCoreDescriptor(
      identifier: "crocods",
      displayName: "CrocoDS",
      frameworkStem: "crocods",
      systems: {"cpc"},
      validExtensions: {"dsk", "kcr", "sna"},
    ),
    RetroArchCoreDescriptor(
      identifier: "dosbox_pure",
      displayName: "DOSBox-pure",
      frameworkStem: "dosbox.pure",
      systems: {"dos"},
      validExtensions: {
        "/",
        "bat",
        "chd",
        "com",
        "conf",
        "cue",
        "dosz",
        "exe",
        "ima",
        "img",
        "ins",
        "iso",
        "jrc",
        "m3u",
        "m3u8",
        "tc",
        "vhd",
        "zip",
      },
    ),
    RetroArchCoreDescriptor(
      identifier: "easyrpg",
      displayName: "EasyRPG Player",
      frameworkStem: "easyrpg",
      systems: {"rpgmaker"},
      validExtensions: {"easyrpg", "ldb", "lzh", "zip"},
    ),
    RetroArchCoreDescriptor(
      identifier: "fbneo",
      displayName: "FinalBurn Neo",
      frameworkStem: "fbneo",
      systems: {
        "arc",
        "cps1",
        "cps2",
        "cps3",
        "cv",
        "fbneo",
        "fc",
        "gen-hacks",
        "genesis",
        "gg",
        "gg-hacks",
        "mark3",
        "md",
        "md-hacks",
        "msx",
        "neogeo",
        "nes",
        "nes-hacks",
        "ngcd",
        "ngp",
        "ngpc",
        "pce",
        "sfc",
        "sfc-hacks",
        "sg1k",
        "sms",
        "snes",
        "snes-hacks",
        "tg16",
        "zxspectrum",
      },
      validExtensions: {"7z", "ccd", "cue", "zip"},
    ),
    RetroArchCoreDescriptor(
      identifier: "freechaf",
      displayName: "FreeChaF",
      frameworkStem: "freechaf",
      systems: {"chf"},
      validExtensions: {"bin", "chf"},
    ),
    RetroArchCoreDescriptor(
      identifier: "freeintv",
      displayName: "FreeIntv",
      frameworkStem: "freeintv",
      systems: {"intv"},
      validExtensions: {"bin", "int", "rom"},
    ),
    RetroArchCoreDescriptor(
      identifier: "fuse",
      displayName: "Fuse",
      frameworkStem: "fuse",
      systems: {"zxspectrum"},
      validExtensions: {
        "dck",
        "dsk",
        "ipf",
        "rzx",
        "scl",
        "sna",
        "szx",
        "tap",
        "trd",
        "tzx",
        "z80",
        "zip",
      },
    ),
    RetroArchCoreDescriptor(
      identifier: "gearboy",
      displayName: "Gearboy",
      frameworkStem: "gearboy",
      systems: {"gb", "gb-hacks", "gbc", "gbc-hacks"},
      validExtensions: {"cgb", "dmg", "gb", "gbc", "sgb"},
    ),
    RetroArchCoreDescriptor(
      identifier: "gearcoleco",
      displayName: "Gearcoleco",
      frameworkStem: "gearcoleco",
      systems: {"cv"},
      validExtensions: {"bin", "col", "cv", "ddp", "dsk", "m3u", "rom", "zip"},
    ),
    RetroArchCoreDescriptor(
      identifier: "geargrafx",
      displayName: "Geargrafx",
      frameworkStem: "geargrafx",
      systems: {"pccd", "pce", "tg16", "tgcd"},
      validExtensions: {"chd", "cue", "hes", "mmi", "pce", "sgx"},
    ),
    RetroArchCoreDescriptor(
      identifier: "gearlynx",
      displayName: "Gearlynx",
      frameworkStem: "gearlynx",
      systems: {"lynx"},
      validExtensions: {"bin", "lnx", "lyx", "o"},
    ),
    RetroArchCoreDescriptor(
      identifier: "gearsystem",
      displayName: "Gearsystem",
      frameworkStem: "gearsystem",
      systems: {"gg", "gg-hacks", "mark3", "sg1k", "sms"},
      validExtensions: {"bin", "gg", "mv", "rom", "sg", "sms"},
    ),
    RetroArchCoreDescriptor(
      identifier: "genesis_plus_gx_wide",
      displayName: "Genesis Plus GX Wide",
      frameworkStem: "genesis.plus.gx.wide",
      systems: {
        "gen-hacks",
        "genesis",
        "gg",
        "gg-hacks",
        "mark3",
        "mcd",
        "md",
        "md-hacks",
        "pico",
        "scd",
        "sg1k",
        "sms",
      },
      validExtensions: {
        "68k",
        "bin",
        "bms",
        "chd",
        "cue",
        "gen",
        "gg",
        "iso",
        "m3u",
        "md",
        "mdx",
        "sg",
        "sgd",
        "smd",
        "sms",
      },
    ),
    RetroArchCoreDescriptor(
      identifier: "geolith",
      displayName: "Geolith",
      frameworkStem: "geolith",
      systems: {"neogeo"},
      validExtensions: {"chd", "cue", "neo"},
    ),
    RetroArchCoreDescriptor(
      identifier: "gpsp",
      displayName: "gpSP",
      frameworkStem: "gpsp",
      systems: {"gba", "gba-hacks"},
      validExtensions: {"bin", "gba"},
    ),
    RetroArchCoreDescriptor(
      identifier: "gw",
      displayName: "GW",
      frameworkStem: "gw",
      systems: {"gw"},
      validExtensions: {"mgw"},
    ),
    RetroArchCoreDescriptor(
      identifier: "handy",
      displayName: "Handy",
      frameworkStem: "handy",
      systems: {"lynx"},
      validExtensions: {"lnx", "lyx", "o"},
    ),
    RetroArchCoreDescriptor(
      identifier: "holani",
      displayName: "Holani",
      frameworkStem: "holani",
      systems: {"lynx"},
      validExtensions: {"lnx", "o"},
    ),
    RetroArchCoreDescriptor(
      identifier: "jollycv",
      displayName: "JollyCV",
      frameworkStem: "jollycv",
      systems: {"cv"},
      validExtensions: {"bin", "col", "myv", "rom"},
    ),
    RetroArchCoreDescriptor(
      identifier: "mednafen_ngp",
      displayName: "Beetle NeoPop",
      frameworkStem: "mednafen.ngp",
      systems: {"ngp", "ngpc"},
      validExtensions: {"ngc", "ngp", "ngpc", "npc"},
    ),
    RetroArchCoreDescriptor(
      identifier: "mednafen_pce",
      displayName: "Beetle PCE",
      frameworkStem: "mednafen.pce",
      systems: {"pccd", "pce", "tg16", "tgcd"},
      validExtensions: {"ccd", "chd", "cue", "m3u", "pce", "sgx", "toc"},
    ),
    RetroArchCoreDescriptor(
      identifier: "mednafen_pcfx",
      displayName: "Beetle PC-FX",
      frameworkStem: "mednafen.pcfx",
      systems: {"pcfx"},
      validExtensions: {"ccd", "chd", "cue", "toc"},
    ),
    RetroArchCoreDescriptor(
      identifier: "mednafen_saturn",
      displayName: "Beetle Saturn",
      frameworkStem: "mednafen.saturn",
      systems: {"sat"},
      validExtensions: {"ccd", "chd", "cue", "m3u", "toc", "zip"},
    ),
    RetroArchCoreDescriptor(
      identifier: "mednafen_supergrafx",
      displayName: "Beetle SuperGrafx",
      frameworkStem: "mednafen.supergrafx",
      systems: {"pccd", "pce", "tg16", "tgcd"},
      validExtensions: {"ccd", "chd", "cue", "pce", "sgx"},
    ),
    RetroArchCoreDescriptor(
      identifier: "mednafen_vb",
      displayName: "Beetle VB",
      frameworkStem: "mednafen.vb",
      systems: {"vb"},
      validExtensions: {"bin", "vb", "vboy"},
    ),
    RetroArchCoreDescriptor(
      identifier: "mednafen_wswan",
      displayName: "Beetle WonderSwan",
      frameworkStem: "mednafen.wswan",
      systems: {"ws", "wsc"},
      validExtensions: {"pc2", "pcv2", "ws", "wsc"},
    ),
    RetroArchCoreDescriptor(
      identifier: "mesen",
      displayName: "Mesen",
      frameworkStem: "mesen",
      systems: {"fc", "fds", "nes", "nes-hacks"},
      validExtensions: {"fds", "nes", "unf", "unif"},
    ),
    RetroArchCoreDescriptor(
      identifier: "mesen-s",
      displayName: "Mesen-S",
      frameworkStem: "mesen-s",
      systems: {
        "gb",
        "gb-hacks",
        "gbc",
        "gbc-hacks",
        "satellaview",
        "sfc",
        "sfc-hacks",
        "snes",
        "snes-hacks",
      },
      validExtensions: {"bs", "fig", "gb", "gbc", "sfc", "smc", "swc"},
    ),
    RetroArchCoreDescriptor(
      identifier: "mu",
      displayName: "Mu",
      frameworkStem: "mu",
      systems: {"palm"},
      validExtensions: {"img", "pdb", "pqa", "prc", "zip"},
    ),
    RetroArchCoreDescriptor(
      identifier: "neocd",
      displayName: "NeoCD",
      frameworkStem: "neocd",
      systems: {"ngcd"},
      validExtensions: {"chd", "cue"},
    ),
    RetroArchCoreDescriptor(
      identifier: "noods",
      displayName: "NooDS",
      frameworkStem: "noods",
      systems: {"ds"},
      validExtensions: {"gba", "nds"},
    ),
    RetroArchCoreDescriptor(
      identifier: "np2kai",
      displayName: "Neko Project II Kai",
      frameworkStem: "np2kai",
      systems: {"pc98"},
      validExtensions: {
        "2hd",
        "88d",
        "98d",
        "cmd",
        "d88",
        "d98",
        "dup",
        "fdd",
        "fdi",
        "hdd",
        "hdi",
        "hdm",
        "hdn",
        "nhd",
        "tfd",
        "thd",
        "xdf",
        "zip",
      },
    ),
    RetroArchCoreDescriptor(
      identifier: "o2em",
      displayName: "O2EM",
      frameworkStem: "o2em",
      systems: {"mo2"},
      validExtensions: {"bin"},
    ),
    RetroArchCoreDescriptor(
      identifier: "opera",
      displayName: "Opera",
      frameworkStem: "opera",
      systems: {"3do"},
      validExtensions: {"bin", "chd", "cue", "iso"},
    ),
    RetroArchCoreDescriptor(
      identifier: "pokemini",
      displayName: "PokeMini",
      frameworkStem: "pokemini",
      systems: {"mini"},
      validExtensions: {"min"},
    ),
    RetroArchCoreDescriptor(
      identifier: "potator",
      displayName: "Potator",
      frameworkStem: "potator",
      systems: {"wsv"},
      validExtensions: {"bin", "sv"},
    ),
    RetroArchCoreDescriptor(
      identifier: "prosystem",
      displayName: "ProSystem",
      frameworkStem: "prosystem",
      systems: {"7800"},
      validExtensions: {"a78", "bin", "cdf"},
    ),
    RetroArchCoreDescriptor(
      identifier: "puae",
      displayName: "PUAE",
      frameworkStem: "puae",
      systems: {"amiga"},
      validExtensions: {
        "/",
        "7z",
        "adf",
        "adz",
        "ccd",
        "chd",
        "cue",
        "dms",
        "fdi",
        "hdf",
        "hdz",
        "info",
        "ipf",
        "iso",
        "lha",
        "m3u",
        "mds",
        "nrg",
        "rp9",
        "slave",
        "uae",
        "zip",
      },
    ),
    RetroArchCoreDescriptor(
      identifier: "px68k",
      displayName: "PX68k",
      frameworkStem: "px68k",
      systems: {"sharpx68000"},
      validExtensions: {
        "2hd",
        "88d",
        "cmd",
        "d88",
        "dim",
        "dup",
        "hdf",
        "hdm",
        "img",
        "m3u",
        "xdf",
      },
    ),
    RetroArchCoreDescriptor(
      identifier: "quicknes",
      displayName: "QuickNES",
      frameworkStem: "quicknes",
      systems: {"fc", "nes", "nes-hacks"},
      validExtensions: {"nes"},
    ),
    RetroArchCoreDescriptor(
      identifier: "race",
      displayName: "RACE",
      frameworkStem: "race",
      systems: {"ngp", "ngpc"},
      validExtensions: {"ngc", "ngp", "ngpc", "npc"},
    ),
    RetroArchCoreDescriptor(
      identifier: "rustynes",
      displayName: "RustyNES",
      frameworkStem: "rustynes",
      systems: {"fc", "fds", "nes", "nes-hacks"},
      validExtensions: {"fds", "nes"},
    ),
    RetroArchCoreDescriptor(
      identifier: "sameduck",
      displayName: "SameDuck",
      frameworkStem: "sameduck",
      systems: {"duck"},
      validExtensions: {"bin", "duck"},
    ),
    RetroArchCoreDescriptor(
      identifier: "scummvm",
      displayName: "ScummVM",
      frameworkStem: "scummvm",
      systems: {"scummvm"},
      validExtensions: {"scummvm"},
    ),
    RetroArchCoreDescriptor(
      identifier: "skyemu",
      displayName: "SkyEmu",
      frameworkStem: "skyemu",
      systems: {"ds", "gb", "gb-hacks", "gba", "gba-hacks"},
      validExtensions: {"gb", "gba", "gbx", "nds"},
    ),
    RetroArchCoreDescriptor(
      identifier: "smsplus",
      displayName: "SMS Plus GX",
      frameworkStem: "smsplus",
      systems: {"gg", "gg-hacks", "mark3", "sms"},
      validExtensions: {"bin", "col", "gg", "rom", "sg", "sms"},
    ),
    RetroArchCoreDescriptor(
      identifier: "snes9x2010",
      displayName: "Snes9x 2010",
      frameworkStem: "snes9x2010",
      systems: {"satellaview", "sfc", "sfc-hacks", "snes", "snes-hacks"},
      validExtensions: {"bsx", "dx2", "fig", "gd3", "gd7", "sfc", "smc", "swc"},
    ),
    RetroArchCoreDescriptor(
      identifier: "stella",
      displayName: "Stella",
      frameworkStem: "stella",
      systems: {"2600"},
      validExtensions: {"a26", "bin"},
    ),
    RetroArchCoreDescriptor(
      identifier: "stella2014",
      displayName: "Stella 2014",
      frameworkStem: "stella2014",
      systems: {"2600"},
      validExtensions: {"a26", "bin"},
    ),
    RetroArchCoreDescriptor(
      identifier: "stella2023",
      displayName: "Stella 2023",
      frameworkStem: "stella2023",
      systems: {"2600"},
      validExtensions: {"a26", "bin"},
    ),
    RetroArchCoreDescriptor(
      identifier: "tgbdual",
      displayName: "TGB Dual",
      frameworkStem: "tgbdual",
      systems: {"gb", "gb-hacks", "gbc", "gbc-hacks"},
      validExtensions: {"cgb", "dmg", "gb", "gbc", "sgb"},
    ),
    RetroArchCoreDescriptor(
      identifier: "tia",
      displayName: "Tia",
      frameworkStem: "tia",
      systems: {"2600"},
      validExtensions: {"a26", "bin"},
    ),
    RetroArchCoreDescriptor(
      identifier: "uzem",
      displayName: "uzem",
      frameworkStem: "uzem",
      systems: {"uze"},
      validExtensions: {"uze"},
    ),
    RetroArchCoreDescriptor(
      identifier: "vba_next",
      displayName: "VBA Next",
      frameworkStem: "vba.next",
      systems: {"gba", "gba-hacks"},
      validExtensions: {"gba"},
    ),
    RetroArchCoreDescriptor(
      identifier: "vbam",
      displayName: "VBA-M",
      frameworkStem: "vbam",
      systems: {"gb", "gb-hacks", "gba", "gba-hacks", "gbc", "gbc-hacks"},
      validExtensions: {"cgb", "dmg", "gb", "gba", "gbc", "sgb"},
    ),
    RetroArchCoreDescriptor(
      identifier: "vice_x64",
      displayName: "VICE x64",
      frameworkStem: "vice.x64",
      systems: {"c64"},
      validExtensions: {
        "/",
        "bin",
        "cmd",
        "crt",
        "d2m",
        "d4m",
        "d64",
        "d6z",
        "d71",
        "d7z",
        "d80",
        "d81",
        "d82",
        "d8z",
        "g41",
        "g4z",
        "g64",
        "g6z",
        "gz",
        "m3u",
        "nbz",
        "nib",
        "p00",
        "prg",
        "t64",
        "tap",
        "vfl",
        "vsf",
        "x64",
        "x6z",
        "zip",
      },
    ),
    RetroArchCoreDescriptor(
      identifier: "vice_x64sc",
      displayName: "VICE x64sc",
      frameworkStem: "vice.x64sc",
      systems: {"c64"},
      validExtensions: {
        "/",
        "bin",
        "cmd",
        "crt",
        "d2m",
        "d4m",
        "d64",
        "d6z",
        "d71",
        "d7z",
        "d80",
        "d81",
        "d82",
        "d8z",
        "g41",
        "g4z",
        "g64",
        "g6z",
        "gz",
        "m3u",
        "nbz",
        "nib",
        "p00",
        "prg",
        "t64",
        "tap",
        "vfl",
        "vsf",
        "x64",
        "x6z",
        "zip",
      },
    ),
    RetroArchCoreDescriptor(
      identifier: "vice_xpet",
      displayName: "VICE xpet",
      frameworkStem: "vice.xpet",
      systems: {"pet"},
      validExtensions: {
        "/",
        "bin",
        "cmd",
        "crt",
        "d2m",
        "d4m",
        "d64",
        "d6z",
        "d71",
        "d7z",
        "d80",
        "d81",
        "d82",
        "d8z",
        "g41",
        "g4z",
        "g64",
        "g6z",
        "gz",
        "m3u",
        "nbz",
        "nib",
        "p00",
        "prg",
        "t64",
        "tap",
        "vfl",
        "vsf",
        "x64",
        "x6z",
        "zip",
      },
    ),
    RetroArchCoreDescriptor(
      identifier: "vice_xplus4",
      displayName: "VICE xplus4",
      frameworkStem: "vice.xplus4",
      systems: {"plus4"},
      validExtensions: {
        "/",
        "bin",
        "cmd",
        "crt",
        "d2m",
        "d4m",
        "d64",
        "d6z",
        "d71",
        "d7z",
        "d80",
        "d81",
        "d82",
        "d8z",
        "g41",
        "g4z",
        "g64",
        "g6z",
        "gz",
        "m3u",
        "nbz",
        "nib",
        "p00",
        "prg",
        "t64",
        "tap",
        "vfl",
        "vsf",
        "x64",
        "x6z",
        "zip",
      },
    ),
    RetroArchCoreDescriptor(
      identifier: "vice_xvic",
      displayName: "VICE xvic",
      frameworkStem: "vice.xvic",
      systems: {"vic20"},
      validExtensions: {
        "/",
        "20",
        "40",
        "60",
        "a0",
        "b0",
        "bin",
        "cmd",
        "crt",
        "d2m",
        "d4m",
        "d64",
        "d6z",
        "d71",
        "d7z",
        "d80",
        "d81",
        "d82",
        "d8z",
        "g41",
        "g4z",
        "g64",
        "g6z",
        "gz",
        "m3u",
        "nbz",
        "nib",
        "p00",
        "prg",
        "rom",
        "t64",
        "tap",
        "vfl",
        "vsf",
        "x64",
        "x6z",
        "zip",
      },
    ),
    RetroArchCoreDescriptor(
      identifier: "virtualjaguar",
      displayName: "Virtual Jaguar",
      frameworkStem: "virtualjaguar",
      systems: {"jag"},
      validExtensions: {
        "abs",
        "bin",
        "cdi",
        "chd",
        "cof",
        "cue",
        "j64",
        "jag",
        "prg",
        "rom",
      },
    ),
    RetroArchCoreDescriptor(
      identifier: "wasm4",
      displayName: "WASM-4",
      frameworkStem: "wasm4",
      systems: {"wasm4"},
      validExtensions: {"wasm"},
    ),
    RetroArchCoreDescriptor(
      identifier: "yabause",
      displayName: "Yabause",
      frameworkStem: "yabause",
      systems: {"sat"},
      validExtensions: {"bin", "ccd", "chd", "cue", "iso", "m3u", "mds", "zip"},
    ),
    RetroArchCoreDescriptor(
      identifier: 'ppsspp',
      displayName: 'PPSSPP',
      frameworkStem: 'ppsspp',
      systems: {'psp', 'pspminis'},
      validExtensions: {'elf', 'iso', 'cso', 'prx', 'pbp', 'chd'},
    ),
    RetroArchCoreDescriptor(
      identifier: 'mupen64plus_next',
      displayName: 'Mupen64Plus-Next',
      frameworkStem: 'mupen64plus.next',
      systems: {'n64'},
      validExtensions: {'n64', 'v64', 'z64', 'ndd', 'bin', 'u1'},
    ),
  ];

  /// Importable game formats plus companion disc files and supported archives.
  /// These are file extensions, so cores' directory marker '/' is excluded.
  static Set<String> get recognizedGameExtensions => {
    for (final core in cores)
      for (final extension in core.validExtensions)
        if (extension != '/') extension.toLowerCase(),
    'zip',
    '7z',
    'cue',
    'm3u',
    'sub',
    'sbi',
  };

  static String normalizeSystem(String folder) => folder.trim().toLowerCase();
  static bool supportsSystem(String folder) =>
      supportedSystems.contains(normalizeSystem(folder));

  static List<RetroArchCoreDescriptor> coresForSystem(String folder) => cores
      .where((core) => core.systems.contains(normalizeSystem(folder)))
      .toList(growable: false);

  static RetroArchCoreDescriptor? findCore(String folder, String? identifier) {
    if (identifier == null || identifier.trim().isEmpty) return null;
    final requested = identifier.trim();
    for (final core in coresForSystem(folder)) {
      if (core.matchesIdentifier(requested)) return core;
    }
    return null;
  }

  static RetroArchCoreDescriptor defaultCore(String folder) {
    final available = coresForSystem(folder);
    if (available.isEmpty) throw ArgumentError.value(folder, 'folder');
    return available.first;
  }
}
