// SPDX-License-Identifier: GPL-3.0-or-later
#pragma once
#import <Foundation/Foundation.h>
static inline NSString* DOLPhoneShakeText(NSString* key,NSString* locale) {
 static NSDictionary* labels;static dispatch_once_t once;dispatch_once(&once,^{labels=@{
@"en": @{@"title": @"Shake device — Wii Remote",@"help": @"First Wii Remote, with or without Nunchuk. Phone shakes also work with a gamepad and preserve its bindings. Disabled in menus and with Classic Controller.",@"usage": @"NeoStation uses device motion to simulate Wii Remote shakes while you play.",@"routeFailed": @"Wii shake input could not be connected. Turn this option off and on to retry.",@"sensorUnavailable": @"Device motion is unavailable. Check motion access and turn this option off and on to retry."},
@"fr": @{@"title": @"Secouer l’appareil — Wiimote",@"help": @"Première Wiimote, avec ou sans Nunchuk. Les secousses du téléphone fonctionnent aussi avec une manette et conservent ses commandes. Désactivé dans les menus et avec la manette classique.",@"usage": @"NeoStation utilise les mouvements de l’appareil pour simuler les secousses de la Wiimote pendant le jeu.",@"routeFailed": @"Impossible de relier la secousse à la Wiimote. Désactivez puis réactivez cette option pour réessayer.",@"sensorUnavailable": @"Les mouvements de l’appareil sont indisponibles. Vérifiez leur autorisation, puis désactivez et réactivez cette option."},
@"de": @{@"title": @"Gerät schütteln — Wii-Fernbedienung",@"help": @"Erste Wii-Fernbedienung, mit oder ohne Nunchuk. Das Schütteln des Telefons funktioniert auch mit einem Gamepad; dessen Belegung bleibt erhalten. In Menüs und mit Classic Controller deaktiviert.",@"usage": @"NeoStation nutzt Gerätebewegungen, um beim Spielen das Schütteln der Wii-Fernbedienung zu simulieren.",@"routeFailed": @"Die Schüttelsteuerung konnte nicht verbunden werden. Zum Wiederholen die Option aus- und einschalten.",@"sensorUnavailable": @"Gerätebewegung ist nicht verfügbar. Bewegungszugriff prüfen und die Option aus- und einschalten."},
@"es": @{@"title": @"Agitar el dispositivo — mando de Wii",@"help": @"Primer mando de Wii, con o sin Nunchuk. Agitar el teléfono también funciona con un mando físico y conserva sus asignaciones. Desactivado en menús y con el mando clásico.",@"usage": @"NeoStation usa el movimiento del dispositivo para simular sacudidas del mando de Wii durante el juego.",@"routeFailed": @"No se pudo conectar la sacudida al mando de Wii. Desactiva y activa esta opción para reintentar.",@"sensorUnavailable": @"El movimiento del dispositivo no está disponible. Revisa su permiso y desactiva y activa esta opción."},
@"it": @{@"title": @"Scuoti il dispositivo — telecomando Wii",@"help": @"Primo telecomando Wii, con o senza Nunchuk. Scuotere il telefono funziona anche con un gamepad e mantiene i suoi comandi. Disattivato nei menu e con il controller classico.",@"usage": @"NeoStation usa il movimento del dispositivo per simulare le scosse del telecomando Wii durante il gioco.",@"routeFailed": @"Impossibile collegare la scossa al telecomando Wii. Disattiva e riattiva questa opzione per riprovare.",@"sensorUnavailable": @"Movimento del dispositivo non disponibile. Controlla il permesso e disattiva e riattiva questa opzione."},
@"pt": @{@"title": @"Sacudir o aparelho — Wii Remote",@"help": @"Primeiro Wii Remote, com ou sem Nunchuk. Sacudir o telefone também funciona com um controle físico e mantém os seus comandos. Desativado nos menus e com o controle clássico.",@"usage": @"O NeoStation usa os movimentos do aparelho para simular sacudidas do Wii Remote durante o jogo.",@"routeFailed": @"Não foi possível conectar a sacudida ao Wii Remote. Desative e ative esta opção para tentar novamente.",@"sensorUnavailable": @"O movimento do aparelho está indisponível. Verifique a permissão e desative e ative esta opção."},
@"ru": @{@"title": @"Встряхивание устройства — Wii Remote",@"help": @"Первый Wii Remote, с Nunchuk или без него. Встряхивание телефона работает и с геймпадом, сохраняя его назначения. Отключено в меню и с Classic Controller.",@"usage": @"NeoStation использует движение устройства для имитации встряхивания Wii Remote во время игры.",@"routeFailed": @"Не удалось подключить встряхивание к Wii Remote. Выключите и включите эту опцию для повтора.",@"sensorUnavailable": @"Движение устройства недоступно. Проверьте разрешение и выключите и включите эту опцию."},
@"id": @{@"title": @"Goyangkan perangkat — Wii Remote",@"help": @"Wii Remote pertama, dengan atau tanpa Nunchuk. Goyangan ponsel juga berfungsi dengan gamepad tanpa mengganti pemetaan tombolnya. Nonaktif di menu dan dengan Classic Controller.",@"usage": @"NeoStation memakai gerakan perangkat untuk menyimulasikan goyangan Wii Remote saat bermain.",@"routeFailed": @"Goyangan tidak dapat dihubungkan ke Wii Remote. Matikan dan hidupkan opsi ini untuk mencoba lagi.",@"sensorUnavailable": @"Gerakan perangkat tidak tersedia. Periksa izinnya, lalu matikan dan hidupkan opsi ini."},
@"ja": @{@"title": @"本体を振る — Wiiリモコン",@"help": @"1番目のWiiリモコン用です。ヌンチャクの有無は問いません。ゲームパッド使用中も本体を振る操作が使え、ボタン設定を保持します。メニューとクラシックコントローラ使用時は無効です。",@"usage": @"NeoStationは本体の動きを使用して、プレイ中にWiiリモコンを振る操作を再現します。",@"routeFailed": @"振る操作をWiiリモコンに接続できませんでした。この設定をオフにしてからオンにすると再試行します。",@"sensorUnavailable": @"本体の動きを利用できません。モーションの許可を確認し、この設定をオフにしてからオンにしてください。"},
@"ko": @{@"title": @"기기 흔들기 — Wii 리모컨",@"help": @"첫 번째 Wii 리모컨에서 사용하며 눈차크는 선택 사항입니다. 게임패드 사용 중에도 휴대폰 흔들기가 작동하고 기존 버튼 설정을 유지합니다. 메뉴와 클래식 컨트롤러 사용 중에는 비활성화됩니다.",@"usage": @"NeoStation은 기기의 움직임으로 게임 중 Wii 리모컨을 흔드는 동작을 재현합니다.",@"routeFailed": @"흔들기를 Wii 리모컨에 연결할 수 없습니다. 이 옵션을 껐다가 켜서 다시 시도하세요.",@"sensorUnavailable": @"기기의 움직임을 사용할 수 없습니다. 동작 접근 권한을 확인하고 이 옵션을 껐다가 켜세요."},
@"zh": @{@"title": @"摇动设备 — Wii遥控器",@"help": @"用于第一个Wii遥控器，可搭配或不搭配双截棍。连接实体手柄时也可摇动手机，并保留手柄按键设置。菜单中和使用经典手柄时禁用。",@"usage": @"NeoStation使用设备运动来模拟游戏中的Wii遥控器摇动操作。",@"routeFailed": @"无法将摇动操作连接到Wii遥控器。关闭后重新开启此选项以重试。",@"sensorUnavailable": @"设备运动不可用。请检查运动权限，然后关闭并重新开启此选项。"},
@"zh_Hant": @{@"title": @"搖動裝置 — Wii遙控器",@"help": @"適用於第一個Wii遙控器，可搭配或不搭配雙節棍。連接實體控制器時也可搖動手機，並保留控制器按鍵設定。在選單中和使用傳統控制器時停用。",@"usage": @"NeoStation使用裝置動作來模擬遊戲中的Wii遙控器搖動操作。",@"routeFailed": @"無法將搖動操作連接至Wii遙控器。關閉後重新開啟此選項以重試。",@"sensorUnavailable": @"裝置動作無法使用。請檢查動作權限，然後關閉並重新開啟此選項。"},
};});
 NSString* s=[locale.lowercaseString stringByReplacingOccurrencesOfString:@"-" withString:@"_"];
 NSString* lang=[s componentsSeparatedByString:@"_"].firstObject;
 if([lang isEqual:@"zh"] && ([s containsString:@"hant"] || [s hasSuffix:@"_tw"] || [s hasSuffix:@"_hk"]))lang=@"zh_Hant";
 return labels[lang][key]?:labels[@"en"][key]?:key;
}
