name: stikjit_bridge
resolution: workspace
description: Experimental NeoStation iOS bridge for independent StikJIT emulator targets.
version: 0.0.2
publish_to: none

environment:
  sdk: '>=3.9.2'
  flutter: '>=3.35.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: NeoStationStikjitBridgePluginV2
