// SPDX-License-Identifier: GPL-3.0-or-later
#import "RPCS3InGameLocalization.h"

namespace {
NSDictionary<NSString*, NSDictionary<NSString*, NSString*>*>* Translations() {
  static NSDictionary<NSString*, NSDictionary<NSString*, NSString*>*>* values;
  static dispatch_once_t once;
  dispatch_once(&once, ^{
    values = @{
      @"en": @{
        @"stateDone": @"Save state created and restored.", @"stateFailed": @"Save-state operation failed.",
        @"menu": @"RPCS3 Menu", @"performance": @"RPCS3 Performance",
        @"enabled": @"Enabled", @"disabled": @"Disabled", @"ok": @"OK",
        @"cancel": @"Cancel", @"language": @"Language",
        @"upscale": @"Upscale / Resolution", @"upscaleTitle": @"Resolution scale",
        @"upscaleRestart": @"The game will restart to apply this setting only to the current Game ID.",
        @"languageTitle": @"PS3 Language",
        @"languageRestart": @"The game will restart to apply the language.",
        @"createState": @"Create save state", @"loadState": @"Load save state",
        @"quitGame": @"Quit game", @"state": @"Save state", @"states": @"Save states",
        @"stateStarted": @"Save-state creation started. RPCS3 will resume the game automatically after writing it.",
        @"noStates": @"No save state is available for this game.",
        @"unknownDate": @"unknown date", @"incompatible": @"incompatible",
        @"incompatibleState": @"This save state is not compatible with this RPCS3 core.",
        @"memory": @"Memory", @"frameTime": @"Frame time (ms)",
      },
      @"fr": @{
        @"stateDone": @"Savestate créée et rechargée.", @"stateFailed": @"Échec de l’opération de savestate.",
        @"menu": @"Menu RPCS3", @"performance": @"Performances RPCS3",
        @"enabled": @"Activé", @"disabled": @"Désactivé", @"ok": @"OK",
        @"cancel": @"Annuler", @"language": @"Langue",
        @"upscale": @"Upscale / Résolution", @"upscaleTitle": @"Échelle de résolution",
        @"upscaleRestart": @"Le jeu redémarrera pour appliquer ce réglage uniquement au Game ID actuel.",
        @"languageTitle": @"Langue PS3",
        @"languageRestart": @"Le jeu redémarre pour appliquer la langue.",
        @"createState": @"Créer une savestate", @"loadState": @"Charger une savestate",
        @"quitGame": @"Quitter le jeu", @"state": @"Savestate", @"states": @"Savestates",
        @"stateStarted": @"Création de la savestate lancée. RPCS3 reprend automatiquement la partie après l’écriture.",
        @"noStates": @"Aucune savestate disponible pour ce jeu.",
        @"unknownDate": @"date inconnue", @"incompatible": @"incompatible",
        @"incompatibleState": @"Cette savestate n’est pas compatible avec ce cœur RPCS3.",
        @"memory": @"Mémoire", @"frameTime": @"Temps par image (ms)",
      },
      @"de": @{
        @"stateDone": @"Spielstand erstellt und wiederhergestellt.", @"stateFailed": @"Spielstandvorgang fehlgeschlagen.",
        @"menu": @"RPCS3-Menü", @"performance": @"RPCS3-Leistung",
        @"enabled": @"Aktiviert", @"disabled": @"Deaktiviert", @"ok": @"OK",
        @"cancel": @"Abbrechen", @"language": @"Sprache",
        @"upscale": @"Upscaling / Auflösung", @"upscaleTitle": @"Auflösungsskalierung",
        @"upscaleRestart": @"Das Spiel wird neu gestartet, um diese Einstellung nur auf die aktuelle Game-ID anzuwenden.",
        @"languageTitle": @"PS3-Sprache",
        @"languageRestart": @"Das Spiel wird neu gestartet, um die Sprache anzuwenden.",
        @"createState": @"Spielstand erstellen", @"loadState": @"Spielstand laden",
        @"quitGame": @"Spiel beenden", @"state": @"Spielstand", @"states": @"Spielstände",
        @"stateStarted": @"Der Spielstand wird erstellt. RPCS3 setzt das Spiel danach automatisch fort.",
        @"noStates": @"Für dieses Spiel ist kein Spielstand verfügbar.",
        @"unknownDate": @"unbekanntes Datum", @"incompatible": @"inkompatibel",
        @"incompatibleState": @"Dieser Spielstand ist mit diesem RPCS3-Core nicht kompatibel.",
        @"memory": @"Speicher", @"frameTime": @"Bildzeit (ms)",
      },
      @"es": @{
        @"stateDone": @"Estado creado y restaurado.", @"stateFailed": @"Falló la operación del estado de guardado.",
        @"menu": @"Menú de RPCS3", @"performance": @"Rendimiento de RPCS3",
        @"enabled": @"Activado", @"disabled": @"Desactivado", @"ok": @"Aceptar",
        @"cancel": @"Cancelar", @"language": @"Idioma",
        @"upscale": @"Escalado / Resolución", @"upscaleTitle": @"Escala de resolución",
        @"upscaleRestart": @"El juego se reiniciará para aplicar este ajuste solo al Game ID actual.",
        @"languageTitle": @"Idioma de PS3",
        @"languageRestart": @"El juego se reiniciará para aplicar el idioma.",
        @"createState": @"Crear estado de guardado", @"loadState": @"Cargar estado de guardado",
        @"quitGame": @"Salir del juego", @"state": @"Estado de guardado", @"states": @"Estados de guardado",
        @"stateStarted": @"Se inició la creación del estado. RPCS3 reanudará el juego automáticamente al terminar.",
        @"noStates": @"No hay estados de guardado disponibles para este juego.",
        @"unknownDate": @"fecha desconocida", @"incompatible": @"incompatible",
        @"incompatibleState": @"Este estado no es compatible con este núcleo de RPCS3.",
        @"memory": @"Memoria", @"frameTime": @"Tiempo de fotograma (ms)",
      },
      @"it": @{
        @"stateDone": @"Stato creato e ripristinato.", @"stateFailed": @"Operazione sullo stato non riuscita.",
        @"menu": @"Menu RPCS3", @"performance": @"Prestazioni RPCS3",
        @"enabled": @"Attivato", @"disabled": @"Disattivato", @"ok": @"OK",
        @"cancel": @"Annulla", @"language": @"Lingua",
        @"upscale": @"Upscaling / Risoluzione", @"upscaleTitle": @"Scala di risoluzione",
        @"upscaleRestart": @"Il gioco verrà riavviato per applicare questa impostazione solo al Game ID attuale.",
        @"languageTitle": @"Lingua PS3",
        @"languageRestart": @"Il gioco verrà riavviato per applicare la lingua.",
        @"createState": @"Crea stato di salvataggio", @"loadState": @"Carica stato di salvataggio",
        @"quitGame": @"Esci dal gioco", @"state": @"Stato di salvataggio", @"states": @"Stati di salvataggio",
        @"stateStarted": @"Creazione dello stato avviata. RPCS3 riprenderà automaticamente il gioco al termine.",
        @"noStates": @"Nessuno stato di salvataggio disponibile per questo gioco.",
        @"unknownDate": @"data sconosciuta", @"incompatible": @"incompatibile",
        @"incompatibleState": @"Questo stato non è compatibile con questo core RPCS3.",
        @"memory": @"Memoria", @"frameTime": @"Tempo fotogramma (ms)",
      },
      @"pt": @{
        @"stateDone": @"Estado criado e restaurado.", @"stateFailed": @"A operação do estado falhou.",
        @"menu": @"Menu do RPCS3", @"performance": @"Desempenho do RPCS3",
        @"enabled": @"Ativado", @"disabled": @"Desativado", @"ok": @"OK",
        @"cancel": @"Cancelar", @"language": @"Idioma",
        @"upscale": @"Upscaling / Resolução", @"upscaleTitle": @"Escala de resolução",
        @"upscaleRestart": @"O jogo será reiniciado para aplicar esta definição apenas ao Game ID atual.",
        @"languageTitle": @"Idioma da PS3",
        @"languageRestart": @"O jogo será reiniciado para aplicar o idioma.",
        @"createState": @"Criar estado de gravação", @"loadState": @"Carregar estado de gravação",
        @"quitGame": @"Sair do jogo", @"state": @"Estado de gravação", @"states": @"Estados de gravação",
        @"stateStarted": @"A criação do estado foi iniciada. O RPCS3 retomará o jogo automaticamente ao terminar.",
        @"noStates": @"Não há estados de gravação disponíveis para este jogo.",
        @"unknownDate": @"data desconhecida", @"incompatible": @"incompatível",
        @"incompatibleState": @"Este estado não é compatível com este núcleo do RPCS3.",
        @"memory": @"Memória", @"frameTime": @"Tempo de fotograma (ms)",
      },
      @"id": @{
        @"stateDone": @"Status permainan dibuat dan dipulihkan.", @"stateFailed": @"Operasi status permainan gagal.",
        @"menu": @"Menu RPCS3", @"performance": @"Performa RPCS3",
        @"enabled": @"Aktif", @"disabled": @"Nonaktif", @"ok": @"OK",
        @"cancel": @"Batal", @"language": @"Bahasa",
        @"upscale": @"Upscale / Resolusi", @"upscaleTitle": @"Skala resolusi",
        @"upscaleRestart": @"Game akan dimulai ulang untuk menerapkan pengaturan ini hanya pada Game ID saat ini.",
        @"languageTitle": @"Bahasa PS3",
        @"languageRestart": @"Game akan dimulai ulang untuk menerapkan bahasa.",
        @"createState": @"Buat status simpan", @"loadState": @"Muat status simpan",
        @"quitGame": @"Keluar dari game", @"state": @"Status simpan", @"states": @"Status simpan",
        @"stateStarted": @"Pembuatan status simpan dimulai. RPCS3 akan melanjutkan game secara otomatis setelah selesai.",
        @"noStates": @"Tidak ada status simpan untuk game ini.",
        @"unknownDate": @"tanggal tidak diketahui", @"incompatible": @"tidak kompatibel",
        @"incompatibleState": @"Status simpan ini tidak kompatibel dengan inti RPCS3 ini.",
        @"memory": @"Memori", @"frameTime": @"Waktu frame (ms)",
      },
      @"ru": @{
        @"stateDone": @"Состояние сохранено и восстановлено.", @"stateFailed": @"Операция с сохранением состояния не удалась.",
        @"menu": @"Меню RPCS3", @"performance": @"Производительность RPCS3",
        @"enabled": @"Включено", @"disabled": @"Выключено", @"ok": @"ОК",
        @"cancel": @"Отмена", @"language": @"Язык",
        @"upscale": @"Масштабирование / Разрешение", @"upscaleTitle": @"Масштаб разрешения",
        @"upscaleRestart": @"Игра будет перезапущена, чтобы применить эту настройку только к текущему Game ID.",
        @"languageTitle": @"Язык PS3",
        @"languageRestart": @"Игра будет перезапущена для применения языка.",
        @"createState": @"Создать сохранение состояния", @"loadState": @"Загрузить сохранение состояния",
        @"quitGame": @"Выйти из игры", @"state": @"Сохранение состояния", @"states": @"Сохранения состояния",
        @"stateStarted": @"Создание сохранения начато. RPCS3 автоматически продолжит игру после записи.",
        @"noStates": @"Для этой игры нет сохранений состояния.",
        @"unknownDate": @"дата неизвестна", @"incompatible": @"несовместимо",
        @"incompatibleState": @"Это сохранение несовместимо с данным ядром RPCS3.",
        @"memory": @"Память", @"frameTime": @"Время кадра (мс)",
      },
      @"ja": @{
        @"stateDone": @"ステートを保存して復元しました。", @"stateFailed": @"ステート操作に失敗しました。",
        @"menu": @"RPCS3メニュー", @"performance": @"RPCS3パフォーマンス",
        @"enabled": @"オン", @"disabled": @"オフ", @"ok": @"OK",
        @"cancel": @"キャンセル", @"language": @"言語",
        @"upscale": @"アップスケール / 解像度", @"upscaleTitle": @"解像度スケール",
        @"upscaleRestart": @"現在のゲームIDだけにこの設定を適用するため、ゲームを再起動します。",
        @"languageTitle": @"PS3の言語",
        @"languageRestart": @"言語を適用するためゲームを再起動します。",
        @"createState": @"ステートを保存", @"loadState": @"ステートを読み込む",
        @"quitGame": @"ゲームを終了", @"state": @"セーブステート", @"states": @"セーブステート",
        @"stateStarted": @"セーブステートの作成を開始しました。完了後、RPCS3が自動的にゲームを再開します。",
        @"noStates": @"このゲームで利用できるセーブステートはありません。",
        @"unknownDate": @"日付不明", @"incompatible": @"非互換",
        @"incompatibleState": @"このセーブステートは現在のRPCS3コアと互換性がありません。",
        @"memory": @"メモリ", @"frameTime": @"フレーム時間 (ms)",
      },
      @"ko": @{
        @"stateDone": @"상태를 저장하고 복원했습니다.", @"stateFailed": @"상태 저장 작업에 실패했습니다.",
        @"menu": @"RPCS3 메뉴", @"performance": @"RPCS3 성능",
        @"enabled": @"켜짐", @"disabled": @"꺼짐", @"ok": @"확인",
        @"cancel": @"취소", @"language": @"언어",
        @"upscale": @"업스케일 / 해상도", @"upscaleTitle": @"해상도 배율",
        @"upscaleRestart": @"현재 게임 ID에만 이 설정을 적용하기 위해 게임을 다시 시작합니다.",
        @"languageTitle": @"PS3 언어",
        @"languageRestart": @"언어를 적용하기 위해 게임을 다시 시작합니다.",
        @"createState": @"상태 저장", @"loadState": @"상태 불러오기",
        @"quitGame": @"게임 종료", @"state": @"저장 상태", @"states": @"저장 상태",
        @"stateStarted": @"상태 저장을 시작했습니다. 완료되면 RPCS3가 자동으로 게임을 재개합니다.",
        @"noStates": @"이 게임에 사용할 수 있는 저장 상태가 없습니다.",
        @"unknownDate": @"날짜 알 수 없음", @"incompatible": @"호환되지 않음",
        @"incompatibleState": @"이 저장 상태는 현재 RPCS3 코어와 호환되지 않습니다.",
        @"memory": @"메모리", @"frameTime": @"프레임 시간 (ms)",
      },
      @"zh": @{
        @"stateDone": @"即时存档已创建并恢复。", @"stateFailed": @"即时存档操作失败。",
        @"menu": @"RPCS3 菜单", @"performance": @"RPCS3 性能",
        @"enabled": @"已开启", @"disabled": @"已关闭", @"ok": @"确定",
        @"cancel": @"取消", @"language": @"语言",
        @"upscale": @"升频 / 分辨率", @"upscaleTitle": @"分辨率缩放",
        @"upscaleRestart": @"游戏将重新启动，并仅为当前游戏 ID 应用此设置。",
        @"languageTitle": @"PS3 语言",
        @"languageRestart": @"游戏将重新启动以应用语言。",
        @"createState": @"创建即时存档", @"loadState": @"加载即时存档",
        @"quitGame": @"退出游戏", @"state": @"即时存档", @"states": @"即时存档",
        @"stateStarted": @"已开始创建即时存档。写入完成后 RPCS3 将自动继续游戏。",
        @"noStates": @"此游戏没有可用的即时存档。",
        @"unknownDate": @"未知日期", @"incompatible": @"不兼容",
        @"incompatibleState": @"此即时存档与当前 RPCS3 核心不兼容。",
        @"memory": @"内存", @"frameTime": @"帧时间 (ms)",
      },
      @"zh_Hant": @{
        @"stateDone": @"即時存檔已建立並還原。", @"stateFailed": @"即時存檔操作失敗。",
        @"menu": @"RPCS3 選單", @"performance": @"RPCS3 效能",
        @"enabled": @"已開啟", @"disabled": @"已關閉", @"ok": @"確定",
        @"cancel": @"取消", @"language": @"語言",
        @"upscale": @"升頻 / 解析度", @"upscaleTitle": @"解析度縮放",
        @"upscaleRestart": @"遊戲將重新啟動，並僅為目前的遊戲 ID 套用此設定。",
        @"languageTitle": @"PS3 語言",
        @"languageRestart": @"遊戲將重新啟動以套用語言。",
        @"createState": @"建立即時存檔", @"loadState": @"載入即時存檔",
        @"quitGame": @"離開遊戲", @"state": @"即時存檔", @"states": @"即時存檔",
        @"stateStarted": @"已開始建立即時存檔。寫入完成後 RPCS3 將自動繼續遊戲。",
        @"noStates": @"此遊戲沒有可用的即時存檔。",
        @"unknownDate": @"未知日期", @"incompatible": @"不相容",
        @"incompatibleState": @"此即時存檔與目前的 RPCS3 核心不相容。",
        @"memory": @"記憶體", @"frameTime": @"影格時間 (ms)",
      },
    };
  });
  return values;
}

NSDictionary<NSString*, NSDictionary<NSString*, NSString*>*>* Build256Translations() {
  // NEOSTATION_RPCS3_BUILD256_HOST_V1: every new in-game string is available in NeoStation's 12 locales.
  static NSDictionary<NSString*, NSDictionary<NSString*, NSString*>*>* values;
  static dispatch_once_t once;
  dispatch_once(&once, ^{
    values = @{
      @"en": @{
        @"state": @"Save state", @"states": @"Save states",
        @"slot": @"Slot", @"emptySlot": @"Empty",
        @"overwrite": @"Overwrite", @"overwriteTitle": @"Overwrite save state?",
        @"overwriteMessage": @"Slot %ld already contains a save state. The previous file will be replaced atomically.",
        @"stretch": @"Screen format", @"stretchTitle": @"Screen format",
        @"stretchMessage": @"The game will restart to apply this setting only to the current Game ID.",
        @"normal": @"Original aspect ratio", @"stretched": @"Stretch to fill screen",
        @"stateSafePoint": @"SPU threads could not reach a safe point. Retry outside active cutscenes.",
        @"stateVideoActive": @"A video cutscene is active and cannot be captured safely. Finish or skip it, then retry.",
        @"stateInvalid": @"This save state is invalid or is not compatible with this RPCS3 core.",
        @"stateMissing": @"The selected save state could not be found.",
        @"stateWriteFailed": @"RPCS3 could not write the save state. The previous slot was preserved.",
        @"stateBusy": @"Another save-state operation is already in progress.",
        @"stateUnknown": @"RPCS3 could not complete the save-state operation.",
        @"stateFreshRestart": @"The save state could not be loaded; the game was restarted normally.",
      },
      @"fr": @{
        @"state": @"État de sauvegarde", @"states": @"États de sauvegarde",
        @"slot": @"Emplacement", @"emptySlot": @"Vide",
        @"overwrite": @"Écraser", @"overwriteTitle": @"Écraser l’état de sauvegarde ?",
        @"overwriteMessage": @"L’emplacement %ld contient déjà un état. L’ancien fichier sera remplacé de façon atomique.",
        @"stretch": @"Format de l’écran", @"stretchTitle": @"Format de l’écran",
        @"stretchMessage": @"Le jeu redémarrera pour appliquer ce réglage uniquement au Game ID actuel.",
        @"normal": @"Format d’origine", @"stretched": @"Étirer pour remplir l’écran",
        @"stateSafePoint": @"Les threads SPU n’ont pas atteint un point sûr. Réessayez hors d’une cinématique active.",
        @"stateVideoActive": @"Une cinématique vidéo active ne peut pas être capturée sans risque. Terminez-la ou passez-la, puis réessayez.",
        @"stateInvalid": @"Cet état de sauvegarde est invalide ou incompatible avec ce cœur RPCS3.",
        @"stateMissing": @"L’état de sauvegarde sélectionné est introuvable.",
        @"stateWriteFailed": @"RPCS3 n’a pas pu écrire l’état. L’ancien emplacement a été conservé.",
        @"stateBusy": @"Une autre opération d’état de sauvegarde est déjà en cours.",
        @"stateUnknown": @"RPCS3 n’a pas pu terminer l’opération d’état de sauvegarde.",
        @"stateFreshRestart": @"L’état n’a pas pu être chargé ; le jeu a redémarré normalement.",
      },
      @"de": @{
        @"state": @"Speicherstand", @"states": @"Speicherstände",
        @"slot": @"Platz", @"emptySlot": @"Leer", @"overwrite": @"Überschreiben",
        @"overwriteTitle": @"Speicherstand überschreiben?",
        @"overwriteMessage": @"Platz %ld enthält bereits einen Speicherstand. Die vorherige Datei wird atomar ersetzt.",
        @"stretch": @"Bildformat", @"stretchTitle": @"Bildformat",
        @"stretchMessage": @"Das Spiel wird neu gestartet; die Einstellung gilt nur für die aktuelle Game-ID.",
        @"normal": @"Originales Seitenverhältnis", @"stretched": @"Auf Bildschirmgröße strecken",
        @"stateSafePoint": @"Die SPU-Threads erreichten keinen sicheren Punkt. Außerhalb aktiver Zwischensequenzen erneut versuchen.",
        @"stateVideoActive": @"Eine aktive Videosequenz kann nicht sicher gespeichert werden. Erst beenden oder überspringen.",
        @"stateInvalid": @"Dieser Speicherstand ist ungültig oder mit diesem RPCS3-Core nicht kompatibel.",
        @"stateMissing": @"Der gewählte Speicherstand wurde nicht gefunden.",
        @"stateWriteFailed": @"RPCS3 konnte nicht speichern. Der vorherige Platz blieb erhalten.",
        @"stateBusy": @"Ein anderer Speichervorgang läuft bereits.", @"stateUnknown": @"RPCS3 konnte den Speichervorgang nicht abschließen.",
        @"stateFreshRestart": @"Der Speicherstand konnte nicht geladen werden; das Spiel wurde normal neu gestartet.",
      },
      @"es": @{
        @"state": @"Estado de guardado", @"states": @"Estados de guardado",
        @"slot": @"Ranura", @"emptySlot": @"Vacía", @"overwrite": @"Sobrescribir",
        @"overwriteTitle": @"¿Sobrescribir el estado?",
        @"overwriteMessage": @"La ranura %ld ya contiene un estado. El archivo anterior se sustituirá de forma atómica.",
        @"stretch": @"Formato de pantalla", @"stretchTitle": @"Formato de pantalla",
        @"stretchMessage": @"El juego se reiniciará y el ajuste solo se aplicará al Game ID actual.",
        @"normal": @"Relación de aspecto original", @"stretched": @"Estirar para llenar la pantalla",
        @"stateSafePoint": @"Los hilos SPU no alcanzaron un punto seguro. Inténtalo fuera de una cinemática activa.",
        @"stateVideoActive": @"No se puede capturar una cinemática activa de forma segura. Termínala u omítela.",
        @"stateInvalid": @"Este estado no es válido o no es compatible con este núcleo RPCS3.",
        @"stateMissing": @"No se encontró el estado seleccionado.", @"stateWriteFailed": @"RPCS3 no pudo escribir el estado. Se conservó la ranura anterior.",
        @"stateBusy": @"Ya hay otra operación de estado en curso.", @"stateUnknown": @"RPCS3 no pudo completar la operación del estado.",
        @"stateFreshRestart": @"No se pudo cargar el estado; el juego se reinició normalmente.",
      },
      @"it": @{
        @"state": @"Stato di salvataggio", @"states": @"Stati di salvataggio",
        @"slot": @"Slot", @"emptySlot": @"Vuoto", @"overwrite": @"Sovrascrivi",
        @"overwriteTitle": @"Sovrascrivere lo stato?",
        @"overwriteMessage": @"Lo slot %ld contiene già uno stato. Il file precedente verrà sostituito in modo atomico.",
        @"stretch": @"Formato schermo", @"stretchTitle": @"Formato schermo",
        @"stretchMessage": @"Il gioco verrà riavviato e l’impostazione si applicherà solo al Game ID corrente.",
        @"normal": @"Proporzioni originali", @"stretched": @"Estendi a schermo intero",
        @"stateSafePoint": @"I thread SPU non hanno raggiunto un punto sicuro. Riprova fuori dalle scene filmate.",
        @"stateVideoActive": @"Una scena video attiva non può essere acquisita in sicurezza. Terminala o saltala.",
        @"stateInvalid": @"Questo stato non è valido o compatibile con questo core RPCS3.",
        @"stateMissing": @"Lo stato selezionato non è stato trovato.", @"stateWriteFailed": @"RPCS3 non ha potuto scrivere lo stato. Lo slot precedente è stato conservato.",
        @"stateBusy": @"È già in corso un’altra operazione di salvataggio.", @"stateUnknown": @"RPCS3 non ha potuto completare l’operazione.",
        @"stateFreshRestart": @"Impossibile caricare lo stato; il gioco è stato riavviato normalmente.",
      },
      @"pt": @{
        @"state": @"Estado de gravação", @"states": @"Estados de gravação",
        @"slot": @"Espaço", @"emptySlot": @"Vazio", @"overwrite": @"Substituir",
        @"overwriteTitle": @"Substituir o estado?", @"overwriteMessage": @"O espaço %ld já contém um estado. O ficheiro anterior será substituído de forma atómica.",
        @"stretch": @"Formato do ecrã", @"stretchTitle": @"Formato do ecrã",
        @"stretchMessage": @"O jogo será reiniciado e a definição só será aplicada ao Game ID atual.",
        @"normal": @"Proporção original", @"stretched": @"Esticar para preencher o ecrã",
        @"stateSafePoint": @"Os threads SPU não atingiram um ponto seguro. Tente fora de uma cena ativa.",
        @"stateVideoActive": @"Uma cena de vídeo ativa não pode ser capturada em segurança. Termine-a ou ignore-a.",
        @"stateInvalid": @"Este estado é inválido ou incompatível com este núcleo RPCS3.", @"stateMissing": @"O estado selecionado não foi encontrado.",
        @"stateWriteFailed": @"O RPCS3 não conseguiu gravar o estado. O espaço anterior foi preservado.",
        @"stateBusy": @"Já existe outra operação de estado em curso.", @"stateUnknown": @"O RPCS3 não conseguiu concluir a operação.",
        @"stateFreshRestart": @"Não foi possível carregar o estado; o jogo foi reiniciado normalmente.",
      },
      @"id": @{
        @"state": @"Status simpan", @"states": @"Status simpan",
        @"slot": @"Slot", @"emptySlot": @"Kosong", @"overwrite": @"Timpa",
        @"overwriteTitle": @"Timpa status simpan?", @"overwriteMessage": @"Slot %ld sudah berisi status. Berkas sebelumnya akan diganti secara atomik.",
        @"stretch": @"Format layar", @"stretchTitle": @"Format layar",
        @"stretchMessage": @"Game akan dimulai ulang dan setelan hanya berlaku untuk Game ID saat ini.",
        @"normal": @"Rasio aspek asli", @"stretched": @"Regangkan memenuhi layar",
        @"stateSafePoint": @"Thread SPU tidak mencapai titik aman. Coba lagi di luar adegan sinematik aktif.",
        @"stateVideoActive": @"Adegan video aktif tidak dapat disimpan dengan aman. Selesaikan atau lewati dahulu.",
        @"stateInvalid": @"Status ini tidak valid atau tidak kompatibel dengan inti RPCS3 ini.", @"stateMissing": @"Status yang dipilih tidak ditemukan.",
        @"stateWriteFailed": @"RPCS3 tidak dapat menulis status. Slot sebelumnya dipertahankan.",
        @"stateBusy": @"Operasi status lain sedang berjalan.", @"stateUnknown": @"RPCS3 tidak dapat menyelesaikan operasi status.",
        @"stateFreshRestart": @"Status tidak dapat dimuat; game dimulai ulang secara normal.",
      },
      @"ru": @{
        @"state": @"Сохранение состояния", @"states": @"Сохранения состояния",
        @"slot": @"Ячейка", @"emptySlot": @"Пусто", @"overwrite": @"Перезаписать",
        @"overwriteTitle": @"Перезаписать состояние?", @"overwriteMessage": @"Ячейка %ld уже содержит состояние. Предыдущий файл будет заменён атомарно.",
        @"stretch": @"Формат экрана", @"stretchTitle": @"Формат экрана",
        @"stretchMessage": @"Игра перезапустится; настройка применяется только к текущему Game ID.",
        @"normal": @"Исходное соотношение сторон", @"stretched": @"Растянуть на весь экран",
        @"stateSafePoint": @"Потоки SPU не достигли безопасной точки. Повторите вне активной заставки.",
        @"stateVideoActive": @"Активную видеозаставку нельзя безопасно сохранить. Завершите или пропустите её.",
        @"stateInvalid": @"Это состояние повреждено или несовместимо с данным ядром RPCS3.", @"stateMissing": @"Выбранное состояние не найдено.",
        @"stateWriteFailed": @"RPCS3 не удалось записать состояние. Предыдущая ячейка сохранена.",
        @"stateBusy": @"Другая операция сохранения уже выполняется.", @"stateUnknown": @"RPCS3 не удалось завершить операцию.",
        @"stateFreshRestart": @"Состояние не загрузилось; игра была запущена заново.",
      },
      @"ja": @{
        @"state": @"セーブステート", @"states": @"セーブステート",
        @"slot": @"スロット", @"emptySlot": @"空", @"overwrite": @"上書き",
        @"overwriteTitle": @"セーブステートを上書きしますか？", @"overwriteMessage": @"スロット%ldには既存のステートがあります。以前のファイルを安全に置き換えます。",
        @"stretch": @"画面形式", @"stretchTitle": @"画面形式",
        @"stretchMessage": @"現在のゲームIDのみに適用するため、ゲームを再起動します。",
        @"normal": @"元のアスペクト比", @"stretched": @"画面全体に引き伸ばす",
        @"stateSafePoint": @"SPUスレッドが安全な地点に到達しませんでした。ムービー中を避けて再試行してください。",
        @"stateVideoActive": @"再生中のムービーは安全に保存できません。終了またはスキップして再試行してください。",
        @"stateInvalid": @"このステートは無効か、このRPCS3コアと互換性がありません。", @"stateMissing": @"選択したステートが見つかりません。",
        @"stateWriteFailed": @"RPCS3はステートを書き込めませんでした。以前のスロットは保持されています。",
        @"stateBusy": @"別のステート操作が実行中です。", @"stateUnknown": @"RPCS3はステート操作を完了できませんでした。",
        @"stateFreshRestart": @"ステートを読み込めなかったため、ゲームを通常起動しました。",
      },
      @"ko": @{
        @"state": @"저장 상태", @"states": @"저장 상태",
        @"slot": @"슬롯", @"emptySlot": @"비어 있음", @"overwrite": @"덮어쓰기",
        @"overwriteTitle": @"저장 상태를 덮어쓸까요?", @"overwriteMessage": @"슬롯 %ld에 상태가 있습니다. 이전 파일을 원자적으로 교체합니다.",
        @"stretch": @"화면 형식", @"stretchTitle": @"화면 형식",
        @"stretchMessage": @"현재 게임 ID에만 적용하기 위해 게임을 다시 시작합니다.",
        @"normal": @"원래 화면 비율", @"stretched": @"화면에 맞게 늘리기",
        @"stateSafePoint": @"SPU 스레드가 안전 지점에 도달하지 못했습니다. 영상 장면 밖에서 다시 시도하세요.",
        @"stateVideoActive": @"재생 중인 영상은 안전하게 저장할 수 없습니다. 끝내거나 건너뛴 뒤 다시 시도하세요.",
        @"stateInvalid": @"이 상태는 잘못되었거나 현재 RPCS3 코어와 호환되지 않습니다.", @"stateMissing": @"선택한 상태를 찾을 수 없습니다.",
        @"stateWriteFailed": @"RPCS3가 상태를 쓰지 못했습니다. 이전 슬롯은 보존되었습니다.",
        @"stateBusy": @"다른 상태 작업이 이미 진행 중입니다.", @"stateUnknown": @"RPCS3가 상태 작업을 완료하지 못했습니다.",
        @"stateFreshRestart": @"상태를 불러오지 못해 게임을 정상적으로 다시 시작했습니다.",
      },
      @"zh": @{
        @"state": @"即时存档", @"states": @"即时存档",
        @"slot": @"槽位", @"emptySlot": @"空", @"overwrite": @"覆盖",
        @"overwriteTitle": @"覆盖即时存档？", @"overwriteMessage": @"槽位 %ld 已有存档。旧文件将以原子方式替换。",
        @"stretch": @"屏幕格式", @"stretchTitle": @"屏幕格式",
        @"stretchMessage": @"游戏将重启，此设置仅应用于当前游戏 ID。",
        @"normal": @"原始宽高比", @"stretched": @"拉伸至全屏",
        @"stateSafePoint": @"SPU 线程未到达安全点。请在非过场动画期间重试。",
        @"stateVideoActive": @"无法安全保存正在播放的视频过场。请结束或跳过后重试。",
        @"stateInvalid": @"此存档无效或与当前 RPCS3 核心不兼容。", @"stateMissing": @"找不到所选存档。",
        @"stateWriteFailed": @"RPCS3 无法写入存档。原槽位已保留。", @"stateBusy": @"已有其他存档操作正在进行。",
        @"stateUnknown": @"RPCS3 无法完成存档操作。", @"stateFreshRestart": @"无法加载存档；游戏已正常重启。",
      },
      @"zh_Hant": @{
        @"state": @"即時存檔", @"states": @"即時存檔",
        @"slot": @"欄位", @"emptySlot": @"空白", @"overwrite": @"覆寫",
        @"overwriteTitle": @"覆寫即時存檔？", @"overwriteMessage": @"欄位 %ld 已有存檔。舊檔案將以不可分割方式取代。",
        @"stretch": @"螢幕格式", @"stretchTitle": @"螢幕格式",
        @"stretchMessage": @"遊戲將重新啟動，此設定只套用於目前的遊戲 ID。",
        @"normal": @"原始長寬比", @"stretched": @"拉伸至全螢幕",
        @"stateSafePoint": @"SPU 執行緒未到達安全點。請在非過場動畫期間重試。",
        @"stateVideoActive": @"無法安全儲存正在播放的影片過場。請結束或略過後再試。",
        @"stateInvalid": @"此存檔無效或與目前的 RPCS3 核心不相容。", @"stateMissing": @"找不到所選存檔。",
        @"stateWriteFailed": @"RPCS3 無法寫入存檔。原欄位已保留。", @"stateBusy": @"已有其他存檔操作正在進行。",
        @"stateUnknown": @"RPCS3 無法完成存檔操作。", @"stateFreshRestart": @"無法載入存檔；遊戲已正常重新啟動。",
      },
    };
  });
  return values;
}

NSDictionary<NSString*, NSDictionary<NSString*, NSString*>*>* Build297Translations() {
  static NSDictionary<NSString*, NSDictionary<NSString*, NSString*>*>* values;
  static dispatch_once_t once;
  dispatch_once(&once, ^{
    values = @{
      @"en": @{
        @"graphicsMenu": @"Graphics", @"systemMenu": @"System / Game",
        @"controlsMenu": @"Controls", @"resumeGame": @"Resume Game",
        @"back": @"Back", @"performanceOverlay": @"Performance Overlay",
        @"touchControls": @"Touch Controls",
        @"graphicsHelp": @"Per-game display settings. Resolution and screen format restart only the current title.",
        @"systemHelp": @"System settings are stored for the current Game ID.",
        @"controlsHelp": @"Touch controls are used only when no physical controller is active.",
        @"perGameRestart": @"Per-game · restarts the current title",
        @"quitConfirm": @"Return to NeoStation?",
        @"settingsFailed": @"RPCS3 could not apply this setting.",
        @"stateLoaded": @"Save state loaded.",
      },
      @"fr": @{
        @"graphicsMenu": @"Graphismes", @"systemMenu": @"Système / Jeu",
        @"controlsMenu": @"Commandes", @"resumeGame": @"Reprendre le jeu",
        @"back": @"Retour", @"performanceOverlay": @"Overlay de performances",
        @"touchControls": @"Commandes tactiles",
        @"graphicsHelp": @"Réglages d’affichage par jeu. La résolution et le format d’écran redémarrent uniquement le titre actuel.",
        @"systemHelp": @"Les réglages système sont enregistrés pour le Game ID actuel.",
        @"controlsHelp": @"Les commandes tactiles sont utilisées uniquement lorsqu’aucune manette physique n’est active.",
        @"perGameRestart": @"Par jeu · redémarre le titre actuel",
        @"quitConfirm": @"Revenir à NeoStation ?",
        @"settingsFailed": @"RPCS3 n’a pas pu appliquer ce réglage.",
        @"stateLoaded": @"État de sauvegarde chargé.",
      },
      @"de": @{
        @"graphicsMenu": @"Grafik", @"systemMenu": @"System / Spiel",
        @"controlsMenu": @"Steuerung", @"resumeGame": @"Spiel fortsetzen",
        @"back": @"Zurück", @"performanceOverlay": @"Leistungsanzeige",
        @"touchControls": @"Touch-Steuerung",
        @"graphicsHelp": @"Anzeigeeinstellungen pro Spiel. Auflösung und Bildformat starten nur den aktuellen Titel neu.",
        @"systemHelp": @"Systemeinstellungen werden für die aktuelle Game-ID gespeichert.",
        @"controlsHelp": @"Touch-Steuerung wird nur verwendet, wenn kein physischer Controller aktiv ist.",
        @"perGameRestart": @"Pro Spiel · startet den aktuellen Titel neu",
        @"quitConfirm": @"Zu NeoStation zurückkehren?",
        @"settingsFailed": @"RPCS3 konnte diese Einstellung nicht anwenden.",
        @"stateLoaded": @"Speicherstand geladen.",
      },
      @"es": @{
        @"graphicsMenu": @"Gráficos", @"systemMenu": @"Sistema / Juego",
        @"controlsMenu": @"Controles", @"resumeGame": @"Reanudar juego",
        @"back": @"Atrás", @"performanceOverlay": @"Superposición de rendimiento",
        @"touchControls": @"Controles táctiles",
        @"graphicsHelp": @"Ajustes de pantalla por juego. La resolución y el formato reinician solo el título actual.",
        @"systemHelp": @"Los ajustes del sistema se guardan para el Game ID actual.",
        @"controlsHelp": @"Los controles táctiles solo se usan cuando no hay un mando físico activo.",
        @"perGameRestart": @"Por juego · reinicia el título actual",
        @"quitConfirm": @"¿Volver a NeoStation?",
        @"settingsFailed": @"RPCS3 no pudo aplicar este ajuste.",
        @"stateLoaded": @"Estado de guardado cargado.",
      },
      @"it": @{
        @"graphicsMenu": @"Grafica", @"systemMenu": @"Sistema / Gioco",
        @"controlsMenu": @"Controlli", @"resumeGame": @"Riprendi gioco",
        @"back": @"Indietro", @"performanceOverlay": @"Overlay prestazioni",
        @"touchControls": @"Controlli touch",
        @"graphicsHelp": @"Impostazioni video per gioco. Risoluzione e formato riavviano solo il titolo corrente.",
        @"systemHelp": @"Le impostazioni di sistema vengono salvate per il Game ID corrente.",
        @"controlsHelp": @"I controlli touch vengono usati solo quando non è attivo un controller fisico.",
        @"perGameRestart": @"Per gioco · riavvia il titolo corrente",
        @"quitConfirm": @"Tornare a NeoStation?",
        @"settingsFailed": @"RPCS3 non ha potuto applicare questa impostazione.",
        @"stateLoaded": @"Stato di salvataggio caricato.",
      },
      @"pt": @{
        @"graphicsMenu": @"Gráficos", @"systemMenu": @"Sistema / Jogo",
        @"controlsMenu": @"Controlos", @"resumeGame": @"Retomar jogo",
        @"back": @"Voltar", @"performanceOverlay": @"Sobreposição de desempenho",
        @"touchControls": @"Controlos tácteis",
        @"graphicsHelp": @"Definições de ecrã por jogo. A resolução e o formato reiniciam apenas o título atual.",
        @"systemHelp": @"As definições do sistema são guardadas para o Game ID atual.",
        @"controlsHelp": @"Os controlos tácteis são usados apenas quando não há um comando físico ativo.",
        @"perGameRestart": @"Por jogo · reinicia o título atual",
        @"quitConfirm": @"Voltar ao NeoStation?",
        @"settingsFailed": @"O RPCS3 não conseguiu aplicar esta definição.",
        @"stateLoaded": @"Estado de gravação carregado.",
      },
      @"id": @{
        @"graphicsMenu": @"Grafis", @"systemMenu": @"Sistem / Game",
        @"controlsMenu": @"Kontrol", @"resumeGame": @"Lanjutkan game",
        @"back": @"Kembali", @"performanceOverlay": @"Overlay performa",
        @"touchControls": @"Kontrol sentuh",
        @"graphicsHelp": @"Pengaturan tampilan per game. Resolusi dan format layar hanya memulai ulang judul saat ini.",
        @"systemHelp": @"Pengaturan sistem disimpan untuk Game ID saat ini.",
        @"controlsHelp": @"Kontrol sentuh hanya digunakan saat tidak ada kontroler fisik aktif.",
        @"perGameRestart": @"Per game · mulai ulang judul saat ini",
        @"quitConfirm": @"Kembali ke NeoStation?",
        @"settingsFailed": @"RPCS3 tidak dapat menerapkan pengaturan ini.",
        @"stateLoaded": @"Status simpan dimuat.",
      },
      @"ru": @{
        @"graphicsMenu": @"Графика", @"systemMenu": @"Система / Игра",
        @"controlsMenu": @"Управление", @"resumeGame": @"Продолжить игру",
        @"back": @"Назад", @"performanceOverlay": @"Панель производительности",
        @"touchControls": @"Сенсорное управление",
        @"graphicsHelp": @"Настройки экрана для игры. Разрешение и формат перезапускают только текущую игру.",
        @"systemHelp": @"Системные настройки сохраняются для текущего Game ID.",
        @"controlsHelp": @"Сенсорное управление используется только без активного физического контроллера.",
        @"perGameRestart": @"Для игры · перезапускает текущий титул",
        @"quitConfirm": @"Вернуться в NeoStation?",
        @"settingsFailed": @"RPCS3 не удалось применить эту настройку.",
        @"stateLoaded": @"Сохранение состояния загружено.",
      },
      @"ja": @{
        @"graphicsMenu": @"グラフィック", @"systemMenu": @"システム / ゲーム",
        @"controlsMenu": @"コントロール", @"resumeGame": @"ゲームを再開",
        @"back": @"戻る", @"performanceOverlay": @"パフォーマンス表示",
        @"touchControls": @"タッチ操作",
        @"graphicsHelp": @"ゲーム別の表示設定です。解像度と画面形式は現在のタイトルだけを再起動します。",
        @"systemHelp": @"システム設定は現在のゲームIDごとに保存されます。",
        @"controlsHelp": @"タッチ操作は物理コントローラーが接続されていない場合のみ使用されます。",
        @"perGameRestart": @"ゲーム別 · 現在のタイトルを再起動",
        @"quitConfirm": @"NeoStationに戻りますか？",
        @"settingsFailed": @"RPCS3はこの設定を適用できませんでした。",
        @"stateLoaded": @"セーブステートを読み込みました。",
      },
      @"ko": @{
        @"graphicsMenu": @"그래픽", @"systemMenu": @"시스템 / 게임",
        @"controlsMenu": @"컨트롤", @"resumeGame": @"게임 계속",
        @"back": @"뒤로", @"performanceOverlay": @"성능 오버레이",
        @"touchControls": @"터치 컨트롤",
        @"graphicsHelp": @"게임별 화면 설정입니다. 해상도와 화면 형식은 현재 타이틀만 다시 시작합니다.",
        @"systemHelp": @"시스템 설정은 현재 게임 ID에 저장됩니다.",
        @"controlsHelp": @"터치 컨트롤은 물리 컨트롤러가 활성화되지 않았을 때만 사용됩니다.",
        @"perGameRestart": @"게임별 · 현재 타이틀 다시 시작",
        @"quitConfirm": @"NeoStation으로 돌아갈까요?",
        @"settingsFailed": @"RPCS3가 이 설정을 적용하지 못했습니다.",
        @"stateLoaded": @"저장 상태를 불러왔습니다.",
      },
      @"zh": @{
        @"graphicsMenu": @"图形", @"systemMenu": @"系统 / 游戏",
        @"controlsMenu": @"控制", @"resumeGame": @"继续游戏",
        @"back": @"返回", @"performanceOverlay": @"性能叠加层",
        @"touchControls": @"触控操作",
        @"graphicsHelp": @"按游戏保存的显示设置。分辨率和屏幕格式只会重启当前游戏。",
        @"systemHelp": @"系统设置会保存到当前游戏 ID。",
        @"controlsHelp": @"仅在没有物理控制器时使用触控操作。",
        @"perGameRestart": @"按游戏 · 重启当前游戏",
        @"quitConfirm": @"返回 NeoStation？",
        @"settingsFailed": @"RPCS3 无法应用此设置。",
        @"stateLoaded": @"即时存档已加载。",
      },
      @"zh_Hant": @{
        @"graphicsMenu": @"圖形", @"systemMenu": @"系統 / 遊戲",
        @"controlsMenu": @"控制", @"resumeGame": @"繼續遊戲",
        @"back": @"返回", @"performanceOverlay": @"效能疊加層",
        @"touchControls": @"觸控操作",
        @"graphicsHelp": @"每遊戲顯示設定。解析度與螢幕格式只會重新啟動目前的遊戲。",
        @"systemHelp": @"系統設定會儲存到目前的遊戲 ID。",
        @"controlsHelp": @"只有在沒有實體控制器時才使用觸控操作。",
        @"perGameRestart": @"每遊戲 · 重新啟動目前遊戲",
        @"quitConfirm": @"返回 NeoStation？",
        @"settingsFailed": @"RPCS3 無法套用此設定。",
        @"stateLoaded": @"即時存檔已載入。",
      },
    };
  });
  return values;
}
}

NSString* RPCS3CanonicalLocale(NSString* identifier) {
  NSString* normalized = [[identifier ?: @"en"
      stringByReplacingOccurrencesOfString:@"-" withString:@"_"] lowercaseString];
  if ([normalized hasPrefix:@"zh_hant"] || [normalized hasPrefix:@"zh_tw"] ||
      [normalized hasPrefix:@"zh_hk"] || [normalized hasPrefix:@"zh_mo"]) {
    return @"zh_Hant";
  }
  NSString* language = [normalized componentsSeparatedByString:@"_"].firstObject ?: @"en";
  static NSSet<NSString*>* supported;
  static dispatch_once_t once;
  dispatch_once(&once, ^{
    supported = [NSSet setWithArray:@[@"de", @"en", @"es", @"fr", @"id", @"it",
                                      @"ja", @"ko", @"pt", @"ru", @"zh"]];
  });
  return [supported containsObject:language] ? language : @"en";
}

NSString* RPCS3LocalizedString(NSString* key, NSString* localeIdentifier) {
  NSDictionary* all = Translations();
  NSDictionary* build256 = Build256Translations();
  NSDictionary* build297 = Build297Translations();
  NSString* locale = RPCS3CanonicalLocale(localeIdentifier);
  return build297[locale][key] ?: build297[@"en"][key] ?:
      build256[locale][key] ?: build256[@"en"][key] ?:
      all[locale][key] ?: all[@"en"][key] ?: key;
}
