#import "ARMSX2InGameLocalization.h"

namespace {
NSDictionary<NSString*, NSDictionary<NSString*, NSString*>*>* ARMSX2Translations() {
  static NSDictionary<NSString*, NSDictionary<NSString*, NSString*>*>* values;
  static dispatch_once_t once;
  dispatch_once(&once, ^{
    values = @{
      @"de": @{
        @"Standard": @"Standard",
        @"Per-game graphics settings are applied live. Advanced hacks keep ARMSX2/GameDB automatic behavior unless explicitly overridden.": @"Grafikeinstellungen pro Spiel werden sofort angewendet. Erweiterte Hacks behalten die ARMSX2/GameDB-Automatik bei, sofern sie nicht ausdrücklich überschrieben wird.",
        @"Automatic removes this game's override and returns control to ARMSX2/GameDB.": @"Automatisch entfernt die Spiel-Überschreibung und gibt die Kontrolle an ARMSX2/GameDB zurück.",
        @"Hardcore RetroAchievements can disable cheats and save-state features.": @"RetroAchievements-Hardcore kann Cheats und Speicherstände einschränken.",
        @"Choose whether NeoStation's PS2 touch overlay is visible.": @"Legt fest, ob die PS2-Touch-Steuerung von NeoStation sichtbar ist.",
        @"RetroAchievements setting updated.": @"RetroAchievements-Einstellung aktualisiert.",
        @"RetroAchievements account linked.": @"RetroAchievements-Konto verbunden.",
        @"RetroAchievements account unlinked.": @"RetroAchievements-Konto getrennt.",
        @"Graphics hack updated for this game.": @"Grafik-Hack für dieses Spiel aktualisiert.",
        @"Enter your username and password.": @"Benutzername und Passwort eingeben.",
        @"Connect the RetroAchievements account used by ARMSX2. The password is sent to the native ARMSX2 login flow and is never stored by NeoStation.": @"Verbinde das von ARMSX2 verwendete RetroAchievements-Konto. Das Passwort wird an die native ARMSX2-Anmeldung übergeben und von NeoStation nicht gespeichert.",
        @"ARMSX2 applies these options through its native PCSX2 RetroAchievements implementation. Hardcore can restrict cheats and save-state features.": @"ARMSX2 wendet diese Optionen über die native PCSX2-RetroAchievements-Implementierung an. Hardcore kann Cheats und Speicherstände einschränken.",
        @"Auto": @"Automatisch", @"Stretch": @"Strecken",
        @"Back": @"Zurück", @"Resume Game": @"Spiel fortsetzen", @"Graphics": @"Grafik",
        @"Compatibility / Cheats": @"Kompatibilität / Cheats", @"Controls": @"Steuerung",
        @"Save State": @"Spielstand speichern", @"Load State": @"Spielstand laden",
        @"Quit Game": @"Spiel beenden", @"Internal Resolution": @"Interne Auflösung",
        @"Screen Format": @"Bildformat", @"Graphics Hacks": @"Grafik-Hacks",
        @"Per-game advanced GS options": @"Erweiterte GS-Optionen pro Spiel",
        @"Automatic": @"Automatisch", @"Automatic (ARMSX2/GameDB)": @"Automatisch (ARMSX2/GameDB)",
        @"On": @"Ein", @"Off": @"Aus", @"Enable Cheats": @"Cheats aktivieren",
        @"Reload Cheats / Patches": @"Cheats / Patches neu laden", @"Touch Controls": @"Touch-Steuerung",
        @"Slot": @"Platz", @"Saved state available": @"Spielstand verfügbar", @"Empty": @"Leer",
        @"Return to NeoStation?": @"Zu NeoStation zurückkehren?", @"Cancel": @"Abbrechen", @"Quit": @"Beenden",
        @"ARMSX2 setting failed": @"ARMSX2-Einstellung fehlgeschlagen",
        @"RetroAchievements error": @"RetroAchievements-Fehler", @"Account": @"Konto",
        @"Username": @"Benutzername", @"Password": @"Passwort", @"Link account": @"Konto verbinden",
        @"Unlink account": @"Konto trennen", @"Account linked.": @"Konto verbunden.",
        @"No account linked.": @"Kein Konto verbunden.", @"Done.": @"Fertig.",
        @"Operation failed.": @"Vorgang fehlgeschlagen.", @"Connecting…": @"Verbindung wird hergestellt…",
        @"Disconnecting…": @"Verbindung wird getrennt…", @"Done": @"Fertig", @"Active": @"Aktiv",
        @"Login saved": @"Anmeldung gespeichert", @"Enabled": @"Aktiviert", @"Disabled": @"Deaktiviert",
        @"Not connected": @"Nicht verbunden", @"Status": @"Status", @"Mode": @"Modus",
        @"Notifications": @"Benachrichtigungen", @"Leaderboard notifications": @"Bestenlisten-Benachrichtigungen",
        @"Overlays": @"Einblendungen", @"ARMSX2 game menu": @"ARMSX2-Spielmenü",
        @"Touch controls updated.": @"Touch-Steuerung aktualisiert.", @"Screen format updated.": @"Bildformat aktualisiert.",
        @"Cheats enabled.": @"Cheats aktiviert.", @"Cheats disabled.": @"Cheats deaktiviert.",
        @"Cheats and patches reloaded.": @"Cheats und Patches neu geladen.",
        @"State loaded.": @"Spielstand geladen.", @"State saved.": @"Spielstand gespeichert.",
        @"PS2 BIOS": @"PS2-BIOS", @"ARMSX2 ready.": @"ARMSX2 bereit.",
        @"Internal resolution: %.0f×": @"Interne Auflösung: %.0f×",
        @"State saved in slot %u.": @"Spielstand in Platz %u gespeichert.",
        @"State loaded from slot %u.": @"Spielstand aus Platz %u geladen.",
        @"Manual graphics hacks": @"Manuelle Grafik-Hacks", @"GPU palette conversion": @"GPU-Palettenkonvertierung",
        @"CPU framebuffer conversion": @"CPU-Framebuffer-Konvertierung", @"Read targets when closing": @"Ziele beim Schließen lesen",
        @"Disable depth emulation": @"Tiefenemulation deaktivieren", @"Disable partial invalidation": @"Teilinvalidierung deaktivieren",
        @"Preload frame data": @"Bilddaten vorladen", @"Estimate texture region": @"Texturbereich schätzen",
        @"Draw buffering": @"Zeichenpufferung", @"Unscaled palette draw": @"Palettenzeichnung ohne Skalierung",
        @"Align sprites": @"Sprites ausrichten", @"Merge sprites": @"Sprites zusammenführen",
        @"Force even sprite position": @"Gerade Sprite-Position erzwingen"
      },
      @"es": @{
        @"Standard": @"Estándar",
        @"Per-game graphics settings are applied live. Advanced hacks keep ARMSX2/GameDB automatic behavior unless explicitly overridden.": @"Los ajustes gráficos por juego se aplican al instante. Los ajustes avanzados mantienen el comportamiento automático de ARMSX2/GameDB salvo que se reemplacen explícitamente.",
        @"Automatic removes this game's override and returns control to ARMSX2/GameDB.": @"Automático elimina la modificación de este juego y devuelve el control a ARMSX2/GameDB.",
        @"Hardcore RetroAchievements can disable cheats and save-state features.": @"El modo Hardcore de RetroAchievements puede restringir trucos y estados guardados.",
        @"Choose whether NeoStation's PS2 touch overlay is visible.": @"Elige si se muestran los controles táctiles de PS2 de NeoStation.",
        @"RetroAchievements setting updated.": @"Ajuste de RetroAchievements actualizado.",
        @"RetroAchievements account linked.": @"Cuenta de RetroAchievements vinculada.",
        @"RetroAchievements account unlinked.": @"Cuenta de RetroAchievements desvinculada.",
        @"Graphics hack updated for this game.": @"Ajuste gráfico actualizado para este juego.",
        @"Enter your username and password.": @"Introduce tu usuario y contraseña.",
        @"Connect the RetroAchievements account used by ARMSX2. The password is sent to the native ARMSX2 login flow and is never stored by NeoStation.": @"Conecta la cuenta de RetroAchievements usada por ARMSX2. La contraseña se envía al inicio de sesión nativo de ARMSX2 y NeoStation nunca la guarda.",
        @"ARMSX2 applies these options through its native PCSX2 RetroAchievements implementation. Hardcore can restrict cheats and save-state features.": @"ARMSX2 aplica estas opciones mediante su implementación nativa de RetroAchievements de PCSX2. Hardcore puede limitar trucos y estados guardados.",
        @"Auto": @"Auto", @"Stretch": @"Estirar",
        @"Back": @"Atrás", @"Resume Game": @"Reanudar juego", @"Graphics": @"Gráficos",
        @"Compatibility / Cheats": @"Compatibilidad / Trucos", @"Controls": @"Controles",
        @"Save State": @"Guardar estado", @"Load State": @"Cargar estado", @"Quit Game": @"Salir del juego",
        @"Internal Resolution": @"Resolución interna", @"Screen Format": @"Formato de pantalla",
        @"Graphics Hacks": @"Ajustes gráficos avanzados", @"Per-game advanced GS options": @"Opciones GS avanzadas por juego",
        @"Automatic": @"Automático", @"Automatic (ARMSX2/GameDB)": @"Automático (ARMSX2/GameDB)",
        @"On": @"Activado", @"Off": @"Desactivado", @"Enable Cheats": @"Activar trucos",
        @"Reload Cheats / Patches": @"Recargar trucos / parches", @"Touch Controls": @"Controles táctiles",
        @"Slot": @"Ranura", @"Saved state available": @"Estado guardado disponible", @"Empty": @"Vacío",
        @"Return to NeoStation?": @"¿Volver a NeoStation?", @"Cancel": @"Cancelar", @"Quit": @"Salir",
        @"ARMSX2 setting failed": @"Error al aplicar el ajuste de ARMSX2",
        @"RetroAchievements error": @"Error de RetroAchievements", @"Account": @"Cuenta",
        @"Username": @"Usuario", @"Password": @"Contraseña", @"Link account": @"Vincular cuenta",
        @"Unlink account": @"Desvincular cuenta", @"Account linked.": @"Cuenta vinculada.",
        @"No account linked.": @"No hay ninguna cuenta vinculada.", @"Done.": @"Hecho.",
        @"Operation failed.": @"La operación ha fallado.", @"Connecting…": @"Conectando…",
        @"Disconnecting…": @"Desconectando…", @"Done": @"Hecho", @"Active": @"Activo",
        @"Login saved": @"Inicio de sesión guardado", @"Enabled": @"Activado", @"Disabled": @"Desactivado",
        @"Not connected": @"No conectado", @"Status": @"Estado", @"Mode": @"Modo",
        @"Notifications": @"Notificaciones", @"Leaderboard notifications": @"Notificaciones de clasificaciones",
        @"Overlays": @"Superposiciones", @"ARMSX2 game menu": @"Menú de juego de ARMSX2",
        @"Touch controls updated.": @"Controles táctiles actualizados.", @"Screen format updated.": @"Formato de pantalla actualizado.",
        @"Cheats enabled.": @"Trucos activados.", @"Cheats disabled.": @"Trucos desactivados.",
        @"Cheats and patches reloaded.": @"Trucos y parches recargados.", @"State loaded.": @"Estado cargado.",
        @"State saved.": @"Estado guardado.", @"PS2 BIOS": @"BIOS de PS2", @"ARMSX2 ready.": @"ARMSX2 listo.",
        @"Internal resolution: %.0f×": @"Resolución interna: %.0f×",
        @"State saved in slot %u.": @"Estado guardado en la ranura %u.",
        @"State loaded from slot %u.": @"Estado cargado desde la ranura %u.",
        @"Manual graphics hacks": @"Ajustes gráficos manuales", @"GPU palette conversion": @"Conversión de paleta por GPU",
        @"CPU framebuffer conversion": @"Conversión de framebuffer por CPU", @"Read targets when closing": @"Leer destinos al cerrar",
        @"Disable depth emulation": @"Desactivar emulación de profundidad", @"Disable partial invalidation": @"Desactivar invalidación parcial",
        @"Preload frame data": @"Precargar datos de fotograma", @"Estimate texture region": @"Estimar región de textura",
        @"Draw buffering": @"Búfer de dibujo", @"Unscaled palette draw": @"Dibujo de paleta sin escalado",
        @"Align sprites": @"Alinear sprites", @"Merge sprites": @"Combinar sprites",
        @"Force even sprite position": @"Forzar posición par de sprites"
      },
      @"pt": @{
        @"Standard": @"Padrão",
        @"Per-game graphics settings are applied live. Advanced hacks keep ARMSX2/GameDB automatic behavior unless explicitly overridden.": @"As definições gráficas por jogo são aplicadas imediatamente. Os ajustes avançados mantêm o comportamento automático do ARMSX2/GameDB salvo substituição explícita.",
        @"Automatic removes this game's override and returns control to ARMSX2/GameDB.": @"Automático remove a substituição deste jogo e devolve o controlo ao ARMSX2/GameDB.",
        @"Hardcore RetroAchievements can disable cheats and save-state features.": @"O modo Hardcore do RetroAchievements pode limitar cheats e estados de gravação.",
        @"Choose whether NeoStation's PS2 touch overlay is visible.": @"Escolha se os controlos tácteis PS2 do NeoStation ficam visíveis.",
        @"RetroAchievements setting updated.": @"Definição do RetroAchievements atualizada.",
        @"RetroAchievements account linked.": @"Conta RetroAchievements associada.",
        @"RetroAchievements account unlinked.": @"Conta RetroAchievements desassociada.",
        @"Graphics hack updated for this game.": @"Ajuste gráfico atualizado para este jogo.",
        @"Enter your username and password.": @"Introduza o nome de utilizador e a palavra-passe.",
        @"Connect the RetroAchievements account used by ARMSX2. The password is sent to the native ARMSX2 login flow and is never stored by NeoStation.": @"Associe a conta RetroAchievements usada pelo ARMSX2. A palavra-passe é enviada ao início de sessão nativo do ARMSX2 e nunca é guardada pelo NeoStation.",
        @"ARMSX2 applies these options through its native PCSX2 RetroAchievements implementation. Hardcore can restrict cheats and save-state features.": @"O ARMSX2 aplica estas opções através da implementação nativa de RetroAchievements do PCSX2. O modo Hardcore pode limitar cheats e estados de gravação.",
        @"Auto": @"Auto", @"Stretch": @"Esticar",
        @"Back": @"Voltar", @"Resume Game": @"Retomar jogo", @"Graphics": @"Gráficos",
        @"Compatibility / Cheats": @"Compatibilidade / Cheats", @"Controls": @"Controlos",
        @"Save State": @"Guardar estado", @"Load State": @"Carregar estado", @"Quit Game": @"Sair do jogo",
        @"Internal Resolution": @"Resolução interna", @"Screen Format": @"Formato do ecrã",
        @"Graphics Hacks": @"Ajustes gráficos avançados", @"Per-game advanced GS options": @"Opções GS avançadas por jogo",
        @"Automatic": @"Automático", @"Automatic (ARMSX2/GameDB)": @"Automático (ARMSX2/GameDB)",
        @"On": @"Ativado", @"Off": @"Desativado", @"Enable Cheats": @"Ativar cheats",
        @"Reload Cheats / Patches": @"Recarregar cheats / patches", @"Touch Controls": @"Controlos tácteis",
        @"Slot": @"Espaço", @"Saved state available": @"Estado guardado disponível", @"Empty": @"Vazio",
        @"Return to NeoStation?": @"Voltar ao NeoStation?", @"Cancel": @"Cancelar", @"Quit": @"Sair",
        @"ARMSX2 setting failed": @"Falha na definição do ARMSX2", @"RetroAchievements error": @"Erro do RetroAchievements",
        @"Account": @"Conta", @"Username": @"Nome de utilizador", @"Password": @"Palavra-passe",
        @"Link account": @"Associar conta", @"Unlink account": @"Desassociar conta",
        @"Account linked.": @"Conta associada.", @"No account linked.": @"Nenhuma conta associada.",
        @"Done.": @"Concluído.", @"Operation failed.": @"A operação falhou.", @"Connecting…": @"A ligar…",
        @"Disconnecting…": @"A desligar…", @"Done": @"Concluído", @"Active": @"Ativo",
        @"Login saved": @"Início de sessão guardado", @"Enabled": @"Ativado", @"Disabled": @"Desativado",
        @"Not connected": @"Não ligado", @"Status": @"Estado", @"Mode": @"Modo",
        @"Notifications": @"Notificações", @"Leaderboard notifications": @"Notificações de classificações",
        @"Overlays": @"Sobreposições", @"ARMSX2 game menu": @"Menu de jogo do ARMSX2",
        @"Touch controls updated.": @"Controlos tácteis atualizados.", @"Screen format updated.": @"Formato do ecrã atualizado.",
        @"Cheats enabled.": @"Cheats ativados.", @"Cheats disabled.": @"Cheats desativados.",
        @"Cheats and patches reloaded.": @"Cheats e patches recarregados.", @"State loaded.": @"Estado carregado.",
        @"State saved.": @"Estado guardado.", @"PS2 BIOS": @"BIOS da PS2", @"ARMSX2 ready.": @"ARMSX2 pronto.",
        @"Internal resolution: %.0f×": @"Resolução interna: %.0f×",
        @"State saved in slot %u.": @"Estado guardado no espaço %u.", @"State loaded from slot %u.": @"Estado carregado do espaço %u.",
        @"Manual graphics hacks": @"Ajustes gráficos manuais", @"GPU palette conversion": @"Conversão de paleta pela GPU",
        @"CPU framebuffer conversion": @"Conversão do framebuffer pela CPU", @"Read targets when closing": @"Ler alvos ao fechar",
        @"Disable depth emulation": @"Desativar emulação de profundidade", @"Disable partial invalidation": @"Desativar invalidação parcial",
        @"Preload frame data": @"Pré-carregar dados da imagem", @"Estimate texture region": @"Estimar região da textura",
        @"Draw buffering": @"Buffer de desenho", @"Unscaled palette draw": @"Desenho de paleta sem escala",
        @"Align sprites": @"Alinhar sprites", @"Merge sprites": @"Combinar sprites",
        @"Force even sprite position": @"Forçar posição par dos sprites"
      },
      @"ru": @{
        @"Standard": @"Стандартный",
        @"Per-game graphics settings are applied live. Advanced hacks keep ARMSX2/GameDB automatic behavior unless explicitly overridden.": @"Графические настройки для игры применяются сразу. Расширенные хаки сохраняют автоматическое поведение ARMSX2/GameDB, пока не задано явное значение.",
        @"Automatic removes this game's override and returns control to ARMSX2/GameDB.": @"Автоматически удаляет переопределение для игры и возвращает управление ARMSX2/GameDB.",
        @"Hardcore RetroAchievements can disable cheats and save-state features.": @"Режим Hardcore RetroAchievements может ограничивать читы и сохранение состояний.",
        @"Choose whether NeoStation's PS2 touch overlay is visible.": @"Выберите, показывать ли сенсорное управление PS2 NeoStation.",
        @"RetroAchievements setting updated.": @"Настройка RetroAchievements обновлена.",
        @"RetroAchievements account linked.": @"Учётная запись RetroAchievements подключена.",
        @"RetroAchievements account unlinked.": @"Учётная запись RetroAchievements отключена.",
        @"Graphics hack updated for this game.": @"Графический хак для этой игры обновлён.",
        @"Enter your username and password.": @"Введите имя пользователя и пароль.",
        @"Connect the RetroAchievements account used by ARMSX2. The password is sent to the native ARMSX2 login flow and is never stored by NeoStation.": @"Подключите учётную запись RetroAchievements, используемую ARMSX2. Пароль передаётся во встроенный вход ARMSX2 и не сохраняется NeoStation.",
        @"ARMSX2 applies these options through its native PCSX2 RetroAchievements implementation. Hardcore can restrict cheats and save-state features.": @"ARMSX2 применяет эти параметры через встроенную реализацию RetroAchievements PCSX2. Hardcore может ограничивать читы и сохранение состояний.",
        @"Auto": @"Авто", @"Stretch": @"Растянуть",
        @"Back": @"Назад", @"Resume Game": @"Продолжить игру", @"Graphics": @"Графика",
        @"Compatibility / Cheats": @"Совместимость / Читы", @"Controls": @"Управление",
        @"Save State": @"Сохранить состояние", @"Load State": @"Загрузить состояние", @"Quit Game": @"Выйти из игры",
        @"Internal Resolution": @"Внутреннее разрешение", @"Screen Format": @"Формат экрана",
        @"Graphics Hacks": @"Графические хаки", @"Per-game advanced GS options": @"Расширенные параметры GS для игры",
        @"Automatic": @"Автоматически", @"Automatic (ARMSX2/GameDB)": @"Автоматически (ARMSX2/GameDB)",
        @"On": @"Вкл.", @"Off": @"Выкл.", @"Enable Cheats": @"Включить читы",
        @"Reload Cheats / Patches": @"Перезагрузить читы / патчи", @"Touch Controls": @"Сенсорное управление",
        @"Slot": @"Ячейка", @"Saved state available": @"Сохранение доступно", @"Empty": @"Пусто",
        @"Return to NeoStation?": @"Вернуться в NeoStation?", @"Cancel": @"Отмена", @"Quit": @"Выйти",
        @"ARMSX2 setting failed": @"Не удалось применить настройку ARMSX2", @"RetroAchievements error": @"Ошибка RetroAchievements",
        @"Account": @"Учётная запись", @"Username": @"Имя пользователя", @"Password": @"Пароль",
        @"Link account": @"Подключить учётную запись", @"Unlink account": @"Отключить учётную запись",
        @"Account linked.": @"Учётная запись подключена.", @"No account linked.": @"Учётная запись не подключена.",
        @"Done.": @"Готово.", @"Operation failed.": @"Операция не выполнена.", @"Connecting…": @"Подключение…",
        @"Disconnecting…": @"Отключение…", @"Done": @"Готово", @"Active": @"Активно",
        @"Login saved": @"Вход сохранён", @"Enabled": @"Включено", @"Disabled": @"Выключено",
        @"Not connected": @"Не подключено", @"Status": @"Статус", @"Mode": @"Режим",
        @"Notifications": @"Уведомления", @"Leaderboard notifications": @"Уведомления таблиц лидеров",
        @"Overlays": @"Оверлеи", @"ARMSX2 game menu": @"Игровое меню ARMSX2",
        @"Touch controls updated.": @"Сенсорное управление обновлено.", @"Screen format updated.": @"Формат экрана обновлён.",
        @"Cheats enabled.": @"Читы включены.", @"Cheats disabled.": @"Читы выключены.",
        @"Cheats and patches reloaded.": @"Читы и патчи перезагружены.", @"State loaded.": @"Состояние загружено.",
        @"State saved.": @"Состояние сохранено.", @"PS2 BIOS": @"BIOS PS2", @"ARMSX2 ready.": @"ARMSX2 готов.",
        @"Internal resolution: %.0f×": @"Внутреннее разрешение: %.0f×",
        @"State saved in slot %u.": @"Состояние сохранено в ячейку %u.", @"State loaded from slot %u.": @"Состояние загружено из ячейки %u.",
        @"Manual graphics hacks": @"Ручные графические хаки", @"GPU palette conversion": @"Преобразование палитры на GPU",
        @"CPU framebuffer conversion": @"Преобразование кадрового буфера на CPU", @"Read targets when closing": @"Читать цели при закрытии",
        @"Disable depth emulation": @"Отключить эмуляцию глубины", @"Disable partial invalidation": @"Отключить частичную инвалидацию",
        @"Preload frame data": @"Предзагрузка данных кадра", @"Estimate texture region": @"Оценивать область текстуры",
        @"Draw buffering": @"Буферизация отрисовки", @"Unscaled palette draw": @"Палитра без масштабирования",
        @"Align sprites": @"Выравнивать спрайты", @"Merge sprites": @"Объединять спрайты",
        @"Force even sprite position": @"Принудительно чётная позиция спрайта"
      },
      @"ja": @{
        @"Standard": @"標準",
        @"Per-game graphics settings are applied live. Advanced hacks keep ARMSX2/GameDB automatic behavior unless explicitly overridden.": @"ゲーム別のグラフィック設定は即時反映されます。高度なハックは明示的に変更しない限りARMSX2/GameDBの自動設定を維持します。",
        @"Automatic removes this game's override and returns control to ARMSX2/GameDB.": @"自動を選ぶとこのゲーム固有の上書きを削除し、ARMSX2/GameDBに制御を戻します。",
        @"Hardcore RetroAchievements can disable cheats and save-state features.": @"RetroAchievementsのHardcoreモードではチートやステート保存機能が制限される場合があります。",
        @"Choose whether NeoStation's PS2 touch overlay is visible.": @"NeoStationのPS2タッチ操作を表示するか選択します。",
        @"RetroAchievements setting updated.": @"RetroAchievements設定を更新しました。",
        @"RetroAchievements account linked.": @"RetroAchievementsアカウントを連携しました。",
        @"RetroAchievements account unlinked.": @"RetroAchievementsアカウントの連携を解除しました。",
        @"Graphics hack updated for this game.": @"このゲームのグラフィックハックを更新しました。",
        @"Enter your username and password.": @"ユーザー名とパスワードを入力してください。",
        @"Connect the RetroAchievements account used by ARMSX2. The password is sent to the native ARMSX2 login flow and is never stored by NeoStation.": @"ARMSX2で使用するRetroAchievementsアカウントを接続します。パスワードはARMSX2のネイティブログイン処理に送られ、NeoStationには保存されません。",
        @"ARMSX2 applies these options through its native PCSX2 RetroAchievements implementation. Hardcore can restrict cheats and save-state features.": @"ARMSX2はPCSX2のネイティブRetroAchievements実装を通じてこれらの設定を適用します。Hardcoreではチートやステート保存機能が制限される場合があります。",
        @"Auto": @"自動", @"Stretch": @"引き伸ばす",
        @"Back": @"戻る", @"Resume Game": @"ゲームを再開", @"Graphics": @"グラフィック",
        @"Compatibility / Cheats": @"互換性 / チート", @"Controls": @"操作",
        @"Save State": @"ステートを保存", @"Load State": @"ステートを読み込む", @"Quit Game": @"ゲームを終了",
        @"Internal Resolution": @"内部解像度", @"Screen Format": @"画面形式", @"Graphics Hacks": @"グラフィックハック",
        @"Per-game advanced GS options": @"ゲーム別の高度なGSオプション", @"Automatic": @"自動",
        @"Automatic (ARMSX2/GameDB)": @"自動 (ARMSX2/GameDB)", @"On": @"オン", @"Off": @"オフ",
        @"Enable Cheats": @"チートを有効化", @"Reload Cheats / Patches": @"チート / パッチを再読み込み",
        @"Touch Controls": @"タッチ操作", @"Slot": @"スロット", @"Saved state available": @"保存ステートあり",
        @"Empty": @"空", @"Return to NeoStation?": @"NeoStationに戻りますか？", @"Cancel": @"キャンセル", @"Quit": @"終了",
        @"ARMSX2 setting failed": @"ARMSX2設定の適用に失敗しました", @"RetroAchievements error": @"RetroAchievementsエラー",
        @"Account": @"アカウント", @"Username": @"ユーザー名", @"Password": @"パスワード",
        @"Link account": @"アカウントを連携", @"Unlink account": @"アカウント連携を解除",
        @"Account linked.": @"アカウントを連携しました。", @"No account linked.": @"連携されたアカウントはありません。",
        @"Done.": @"完了しました。", @"Operation failed.": @"操作に失敗しました。", @"Connecting…": @"接続中…",
        @"Disconnecting…": @"切断中…", @"Done": @"完了", @"Active": @"有効",
        @"Login saved": @"ログイン保存済み", @"Enabled": @"有効", @"Disabled": @"無効",
        @"Not connected": @"未接続", @"Status": @"状態", @"Mode": @"モード",
        @"Notifications": @"通知", @"Leaderboard notifications": @"ランキング通知", @"Overlays": @"オーバーレイ",
        @"ARMSX2 game menu": @"ARMSX2ゲームメニュー", @"Touch controls updated.": @"タッチ操作を更新しました。",
        @"Screen format updated.": @"画面形式を更新しました。", @"Cheats enabled.": @"チートを有効にしました。",
        @"Cheats disabled.": @"チートを無効にしました。", @"Cheats and patches reloaded.": @"チートとパッチを再読み込みしました。",
        @"State loaded.": @"ステートを読み込みました。", @"State saved.": @"ステートを保存しました。",
        @"PS2 BIOS": @"PS2 BIOS", @"ARMSX2 ready.": @"ARMSX2の準備ができました。",
        @"Internal resolution: %.0f×": @"内部解像度: %.0f×", @"State saved in slot %u.": @"スロット%uに保存しました。",
        @"State loaded from slot %u.": @"スロット%uから読み込みました。",
        @"Manual graphics hacks": @"手動グラフィックハック", @"GPU palette conversion": @"GPUパレット変換",
        @"CPU framebuffer conversion": @"CPUフレームバッファ変換", @"Read targets when closing": @"終了時にターゲットを読み取る",
        @"Disable depth emulation": @"深度エミュレーションを無効化", @"Disable partial invalidation": @"部分無効化を無効化",
        @"Preload frame data": @"フレームデータを事前読み込み", @"Estimate texture region": @"テクスチャ領域を推定",
        @"Draw buffering": @"描画バッファリング", @"Unscaled palette draw": @"パレット描画を拡大しない",
        @"Align sprites": @"スプライトを整列", @"Merge sprites": @"スプライトを結合",
        @"Force even sprite position": @"スプライト位置を偶数に固定"
      },
      @"ko": @{
        @"Standard": @"표준",
        @"Per-game graphics settings are applied live. Advanced hacks keep ARMSX2/GameDB automatic behavior unless explicitly overridden.": @"게임별 그래픽 설정은 즉시 적용됩니다. 고급 해킹은 명시적으로 변경하지 않는 한 ARMSX2/GameDB 자동 동작을 유지합니다.",
        @"Automatic removes this game's override and returns control to ARMSX2/GameDB.": @"자동은 이 게임의 재정의를 제거하고 ARMSX2/GameDB에 제어를 돌려줍니다.",
        @"Hardcore RetroAchievements can disable cheats and save-state features.": @"RetroAchievements Hardcore 모드는 치트와 상태 저장 기능을 제한할 수 있습니다.",
        @"Choose whether NeoStation's PS2 touch overlay is visible.": @"NeoStation의 PS2 터치 컨트롤 표시 여부를 선택합니다.",
        @"RetroAchievements setting updated.": @"RetroAchievements 설정이 업데이트되었습니다.",
        @"RetroAchievements account linked.": @"RetroAchievements 계정이 연결되었습니다.",
        @"RetroAchievements account unlinked.": @"RetroAchievements 계정 연결이 해제되었습니다.",
        @"Graphics hack updated for this game.": @"이 게임의 그래픽 해킹이 업데이트되었습니다.",
        @"Enter your username and password.": @"사용자 이름과 비밀번호를 입력하세요.",
        @"Connect the RetroAchievements account used by ARMSX2. The password is sent to the native ARMSX2 login flow and is never stored by NeoStation.": @"ARMSX2에서 사용하는 RetroAchievements 계정을 연결합니다. 비밀번호는 ARMSX2 기본 로그인 흐름으로 전달되며 NeoStation에 저장되지 않습니다.",
        @"ARMSX2 applies these options through its native PCSX2 RetroAchievements implementation. Hardcore can restrict cheats and save-state features.": @"ARMSX2는 PCSX2의 기본 RetroAchievements 구현을 통해 이 옵션을 적용합니다. Hardcore는 치트와 상태 저장 기능을 제한할 수 있습니다.",
        @"Auto": @"자동", @"Stretch": @"늘이기",
        @"Back": @"뒤로", @"Resume Game": @"게임 계속", @"Graphics": @"그래픽",
        @"Compatibility / Cheats": @"호환성 / 치트", @"Controls": @"컨트롤",
        @"Save State": @"상태 저장", @"Load State": @"상태 불러오기", @"Quit Game": @"게임 종료",
        @"Internal Resolution": @"내부 해상도", @"Screen Format": @"화면 형식", @"Graphics Hacks": @"그래픽 해킹",
        @"Per-game advanced GS options": @"게임별 고급 GS 옵션", @"Automatic": @"자동",
        @"Automatic (ARMSX2/GameDB)": @"자동 (ARMSX2/GameDB)", @"On": @"켜짐", @"Off": @"꺼짐",
        @"Enable Cheats": @"치트 사용", @"Reload Cheats / Patches": @"치트 / 패치 다시 불러오기",
        @"Touch Controls": @"터치 컨트롤", @"Slot": @"슬롯", @"Saved state available": @"저장 상태 있음",
        @"Empty": @"비어 있음", @"Return to NeoStation?": @"NeoStation으로 돌아갈까요?", @"Cancel": @"취소", @"Quit": @"종료",
        @"ARMSX2 setting failed": @"ARMSX2 설정 적용 실패", @"RetroAchievements error": @"RetroAchievements 오류",
        @"Account": @"계정", @"Username": @"사용자 이름", @"Password": @"비밀번호",
        @"Link account": @"계정 연결", @"Unlink account": @"계정 연결 해제", @"Account linked.": @"계정이 연결되었습니다.",
        @"No account linked.": @"연결된 계정이 없습니다.", @"Done.": @"완료.", @"Operation failed.": @"작업에 실패했습니다.",
        @"Connecting…": @"연결 중…", @"Disconnecting…": @"연결 해제 중…", @"Done": @"완료", @"Active": @"활성",
        @"Login saved": @"로그인 저장됨", @"Enabled": @"활성화됨", @"Disabled": @"비활성화됨",
        @"Not connected": @"연결되지 않음", @"Status": @"상태", @"Mode": @"모드",
        @"Notifications": @"알림", @"Leaderboard notifications": @"리더보드 알림", @"Overlays": @"오버레이",
        @"ARMSX2 game menu": @"ARMSX2 게임 메뉴", @"Touch controls updated.": @"터치 컨트롤이 업데이트되었습니다.",
        @"Screen format updated.": @"화면 형식이 업데이트되었습니다.", @"Cheats enabled.": @"치트가 활성화되었습니다.",
        @"Cheats disabled.": @"치트가 비활성화되었습니다.", @"Cheats and patches reloaded.": @"치트와 패치를 다시 불러왔습니다.",
        @"State loaded.": @"상태를 불러왔습니다.", @"State saved.": @"상태를 저장했습니다.",
        @"PS2 BIOS": @"PS2 BIOS", @"ARMSX2 ready.": @"ARMSX2 준비 완료.",
        @"Internal resolution: %.0f×": @"내부 해상도: %.0f×", @"State saved in slot %u.": @"슬롯 %u에 상태를 저장했습니다.",
        @"State loaded from slot %u.": @"슬롯 %u에서 상태를 불러왔습니다.",
        @"Manual graphics hacks": @"수동 그래픽 해킹", @"GPU palette conversion": @"GPU 팔레트 변환",
        @"CPU framebuffer conversion": @"CPU 프레임버퍼 변환", @"Read targets when closing": @"닫을 때 대상 읽기",
        @"Disable depth emulation": @"깊이 에뮬레이션 비활성화", @"Disable partial invalidation": @"부분 무효화 비활성화",
        @"Preload frame data": @"프레임 데이터 미리 로드", @"Estimate texture region": @"텍스처 영역 추정",
        @"Draw buffering": @"그리기 버퍼링", @"Unscaled palette draw": @"팔레트 그리기 크기 유지",
        @"Align sprites": @"스프라이트 정렬", @"Merge sprites": @"스프라이트 병합",
        @"Force even sprite position": @"스프라이트 위치를 짝수로 강제"
      },
      @"zh": @{
        @"Standard": @"标准",
        @"Per-game graphics settings are applied live. Advanced hacks keep ARMSX2/GameDB automatic behavior unless explicitly overridden.": @"每个游戏的图形设置会即时生效。除非明确覆盖，高级修正会继续使用 ARMSX2/GameDB 的自动行为。",
        @"Automatic removes this game's override and returns control to ARMSX2/GameDB.": @"自动会移除此游戏的覆盖设置，并将控制权交还给 ARMSX2/GameDB。",
        @"Hardcore RetroAchievements can disable cheats and save-state features.": @"RetroAchievements 硬核模式可能限制金手指和即时存档功能。",
        @"Choose whether NeoStation's PS2 touch overlay is visible.": @"选择是否显示 NeoStation 的 PS2 触控界面。",
        @"RetroAchievements setting updated.": @"RetroAchievements 设置已更新。",
        @"RetroAchievements account linked.": @"RetroAchievements 账户已关联。",
        @"RetroAchievements account unlinked.": @"RetroAchievements 账户已取消关联。",
        @"Graphics hack updated for this game.": @"此游戏的图形修正已更新。",
        @"Enter your username and password.": @"请输入用户名和密码。",
        @"Connect the RetroAchievements account used by ARMSX2. The password is sent to the native ARMSX2 login flow and is never stored by NeoStation.": @"连接 ARMSX2 使用的 RetroAchievements 账户。密码会发送到 ARMSX2 原生登录流程，NeoStation 不会保存密码。",
        @"ARMSX2 applies these options through its native PCSX2 RetroAchievements implementation. Hardcore can restrict cheats and save-state features.": @"ARMSX2 通过 PCSX2 原生 RetroAchievements 实现应用这些选项。硬核模式可能限制金手指和即时存档功能。",
        @"Auto": @"自动", @"Stretch": @"拉伸",
        @"Back": @"返回", @"Resume Game": @"继续游戏", @"Graphics": @"图形",
        @"Compatibility / Cheats": @"兼容性 / 金手指", @"Controls": @"控制",
        @"Save State": @"保存即时存档", @"Load State": @"加载即时存档", @"Quit Game": @"退出游戏",
        @"Internal Resolution": @"内部分辨率", @"Screen Format": @"屏幕格式", @"Graphics Hacks": @"图形修正",
        @"Per-game advanced GS options": @"每个游戏的高级 GS 选项", @"Automatic": @"自动",
        @"Automatic (ARMSX2/GameDB)": @"自动 (ARMSX2/GameDB)", @"On": @"开启", @"Off": @"关闭",
        @"Enable Cheats": @"启用金手指", @"Reload Cheats / Patches": @"重新加载金手指 / 补丁",
        @"Touch Controls": @"触控操作", @"Slot": @"槽位", @"Saved state available": @"已有即时存档",
        @"Empty": @"空", @"Return to NeoStation?": @"返回 NeoStation？", @"Cancel": @"取消", @"Quit": @"退出",
        @"ARMSX2 setting failed": @"ARMSX2 设置失败", @"RetroAchievements error": @"RetroAchievements 错误",
        @"Account": @"账户", @"Username": @"用户名", @"Password": @"密码", @"Link account": @"关联账户",
        @"Unlink account": @"取消关联账户", @"Account linked.": @"账户已关联。", @"No account linked.": @"未关联账户。",
        @"Done.": @"完成。", @"Operation failed.": @"操作失败。", @"Connecting…": @"正在连接…",
        @"Disconnecting…": @"正在断开…", @"Done": @"完成", @"Active": @"活动",
        @"Login saved": @"登录已保存", @"Enabled": @"已启用", @"Disabled": @"已禁用",
        @"Not connected": @"未连接", @"Status": @"状态", @"Mode": @"模式",
        @"Notifications": @"通知", @"Leaderboard notifications": @"排行榜通知", @"Overlays": @"叠加层",
        @"ARMSX2 game menu": @"ARMSX2 游戏菜单", @"Touch controls updated.": @"触控操作已更新。",
        @"Screen format updated.": @"屏幕格式已更新。", @"Cheats enabled.": @"金手指已启用。",
        @"Cheats disabled.": @"金手指已禁用。", @"Cheats and patches reloaded.": @"金手指和补丁已重新加载。",
        @"State loaded.": @"即时存档已加载。", @"State saved.": @"即时存档已保存。",
        @"PS2 BIOS": @"PS2 BIOS", @"ARMSX2 ready.": @"ARMSX2 已就绪。",
        @"Internal resolution: %.0f×": @"内部分辨率：%.0f×", @"State saved in slot %u.": @"即时存档已保存到槽位 %u。",
        @"State loaded from slot %u.": @"已从槽位 %u 加载即时存档。",
        @"Manual graphics hacks": @"手动图形修正", @"GPU palette conversion": @"GPU 调色板转换",
        @"CPU framebuffer conversion": @"CPU 帧缓冲转换", @"Read targets when closing": @"关闭时读取目标",
        @"Disable depth emulation": @"禁用深度模拟", @"Disable partial invalidation": @"禁用部分失效",
        @"Preload frame data": @"预加载帧数据", @"Estimate texture region": @"估算纹理区域",
        @"Draw buffering": @"绘制缓冲", @"Unscaled palette draw": @"不缩放调色板绘制",
        @"Align sprites": @"对齐精灵", @"Merge sprites": @"合并精灵", @"Force even sprite position": @"强制精灵偶数位置"
      },
      @"zh_Hant": @{
        @"Standard": @"標準",
        @"Per-game graphics settings are applied live. Advanced hacks keep ARMSX2/GameDB automatic behavior unless explicitly overridden.": @"每個遊戲的圖形設定會即時套用。除非明確覆寫，進階修正會繼續使用 ARMSX2/GameDB 的自動行為。",
        @"Automatic removes this game's override and returns control to ARMSX2/GameDB.": @"自動會移除此遊戲的覆寫設定，並將控制權交還給 ARMSX2/GameDB。",
        @"Hardcore RetroAchievements can disable cheats and save-state features.": @"RetroAchievements Hardcore 模式可能限制金手指與即時存檔功能。",
        @"Choose whether NeoStation's PS2 touch overlay is visible.": @"選擇是否顯示 NeoStation 的 PS2 觸控介面。",
        @"RetroAchievements setting updated.": @"RetroAchievements 設定已更新。",
        @"RetroAchievements account linked.": @"RetroAchievements 帳戶已連結。",
        @"RetroAchievements account unlinked.": @"RetroAchievements 帳戶已取消連結。",
        @"Graphics hack updated for this game.": @"此遊戲的圖形修正已更新。",
        @"Enter your username and password.": @"請輸入使用者名稱與密碼。",
        @"Connect the RetroAchievements account used by ARMSX2. The password is sent to the native ARMSX2 login flow and is never stored by NeoStation.": @"連結 ARMSX2 使用的 RetroAchievements 帳戶。密碼會傳送到 ARMSX2 原生登入流程，NeoStation 不會儲存密碼。",
        @"ARMSX2 applies these options through its native PCSX2 RetroAchievements implementation. Hardcore can restrict cheats and save-state features.": @"ARMSX2 透過 PCSX2 原生 RetroAchievements 實作套用這些選項。Hardcore 可能限制金手指與即時存檔功能。",
        @"Auto": @"自動", @"Stretch": @"拉伸",
        @"Back": @"返回", @"Resume Game": @"繼續遊戲", @"Graphics": @"圖形",
        @"Compatibility / Cheats": @"相容性 / 金手指", @"Controls": @"控制",
        @"Save State": @"儲存即時存檔", @"Load State": @"載入即時存檔", @"Quit Game": @"離開遊戲",
        @"Internal Resolution": @"內部解析度", @"Screen Format": @"螢幕格式", @"Graphics Hacks": @"圖形修正",
        @"Per-game advanced GS options": @"每個遊戲的進階 GS 選項", @"Automatic": @"自動",
        @"Automatic (ARMSX2/GameDB)": @"自動 (ARMSX2/GameDB)", @"On": @"開啟", @"Off": @"關閉",
        @"Enable Cheats": @"啟用金手指", @"Reload Cheats / Patches": @"重新載入金手指 / 修補程式",
        @"Touch Controls": @"觸控操作", @"Slot": @"欄位", @"Saved state available": @"已有即時存檔",
        @"Empty": @"空白", @"Return to NeoStation?": @"返回 NeoStation？", @"Cancel": @"取消", @"Quit": @"離開",
        @"ARMSX2 setting failed": @"ARMSX2 設定失敗", @"RetroAchievements error": @"RetroAchievements 錯誤",
        @"Account": @"帳戶", @"Username": @"使用者名稱", @"Password": @"密碼", @"Link account": @"連結帳戶",
        @"Unlink account": @"取消連結帳戶", @"Account linked.": @"帳戶已連結。", @"No account linked.": @"未連結帳戶。",
        @"Done.": @"完成。", @"Operation failed.": @"操作失敗。", @"Connecting…": @"正在連線…",
        @"Disconnecting…": @"正在中斷連線…", @"Done": @"完成", @"Active": @"啟用",
        @"Login saved": @"登入已儲存", @"Enabled": @"已啟用", @"Disabled": @"已停用",
        @"Not connected": @"未連線", @"Status": @"狀態", @"Mode": @"模式",
        @"Notifications": @"通知", @"Leaderboard notifications": @"排行榜通知", @"Overlays": @"疊加層",
        @"ARMSX2 game menu": @"ARMSX2 遊戲選單", @"Touch controls updated.": @"觸控操作已更新。",
        @"Screen format updated.": @"螢幕格式已更新。", @"Cheats enabled.": @"金手指已啟用。",
        @"Cheats disabled.": @"金手指已停用。", @"Cheats and patches reloaded.": @"金手指與修補程式已重新載入。",
        @"State loaded.": @"即時存檔已載入。", @"State saved.": @"即時存檔已儲存。",
        @"PS2 BIOS": @"PS2 BIOS", @"ARMSX2 ready.": @"ARMSX2 已就緒。",
        @"Internal resolution: %.0f×": @"內部解析度：%.0f×", @"State saved in slot %u.": @"即時存檔已儲存至欄位 %u。",
        @"State loaded from slot %u.": @"已從欄位 %u 載入即時存檔。",
        @"Manual graphics hacks": @"手動圖形修正", @"GPU palette conversion": @"GPU 調色盤轉換",
        @"CPU framebuffer conversion": @"CPU 畫面緩衝轉換", @"Read targets when closing": @"關閉時讀取目標",
        @"Disable depth emulation": @"停用深度模擬", @"Disable partial invalidation": @"停用部分失效",
        @"Preload frame data": @"預載畫面資料", @"Estimate texture region": @"估算紋理區域",
        @"Draw buffering": @"繪製緩衝", @"Unscaled palette draw": @"不縮放調色盤繪製",
        @"Align sprites": @"對齊精靈", @"Merge sprites": @"合併精靈", @"Force even sprite position": @"強制精靈偶數位置"
      },
      @"it": @{
        @"Standard": @"Standard",
        @"Per-game graphics settings are applied live. Advanced hacks keep ARMSX2/GameDB automatic behavior unless explicitly overridden.": @"Le impostazioni grafiche per gioco vengono applicate subito. Gli hack avanzati mantengono il comportamento automatico ARMSX2/GameDB salvo modifica esplicita.",
        @"Automatic removes this game's override and returns control to ARMSX2/GameDB.": @"Automatico rimuove la modifica di questo gioco e restituisce il controllo ad ARMSX2/GameDB.",
        @"Hardcore RetroAchievements can disable cheats and save-state features.": @"La modalità Hardcore di RetroAchievements può limitare trucchi e salvataggi di stato.",
        @"Choose whether NeoStation's PS2 touch overlay is visible.": @"Scegli se mostrare i controlli touch PS2 di NeoStation.",
        @"RetroAchievements setting updated.": @"Impostazione RetroAchievements aggiornata.",
        @"RetroAchievements account linked.": @"Account RetroAchievements collegato.",
        @"RetroAchievements account unlinked.": @"Account RetroAchievements scollegato.",
        @"Graphics hack updated for this game.": @"Hack grafico aggiornato per questo gioco.",
        @"Enter your username and password.": @"Inserisci nome utente e password.",
        @"Connect the RetroAchievements account used by ARMSX2. The password is sent to the native ARMSX2 login flow and is never stored by NeoStation.": @"Collega l’account RetroAchievements usato da ARMSX2. La password viene inviata al login nativo di ARMSX2 e non viene mai memorizzata da NeoStation.",
        @"ARMSX2 applies these options through its native PCSX2 RetroAchievements implementation. Hardcore can restrict cheats and save-state features.": @"ARMSX2 applica queste opzioni tramite l’implementazione RetroAchievements nativa di PCSX2. Hardcore può limitare trucchi e salvataggi di stato.",
        @"Auto": @"Auto", @"Stretch": @"Estendi",
        @"Back": @"Indietro", @"Resume Game": @"Riprendi gioco", @"Graphics": @"Grafica",
        @"Compatibility / Cheats": @"Compatibilità / Trucchi", @"Controls": @"Controlli",
        @"Save State": @"Salva stato", @"Load State": @"Carica stato", @"Quit Game": @"Esci dal gioco",
        @"Internal Resolution": @"Risoluzione interna", @"Screen Format": @"Formato schermo", @"Graphics Hacks": @"Hack grafici",
        @"Per-game advanced GS options": @"Opzioni GS avanzate per gioco", @"Automatic": @"Automatico",
        @"Automatic (ARMSX2/GameDB)": @"Automatico (ARMSX2/GameDB)", @"On": @"Attivo", @"Off": @"Disattivo",
        @"Enable Cheats": @"Abilita trucchi", @"Reload Cheats / Patches": @"Ricarica trucchi / patch",
        @"Touch Controls": @"Controlli touch", @"Slot": @"Slot", @"Saved state available": @"Stato salvato disponibile",
        @"Empty": @"Vuoto", @"Return to NeoStation?": @"Tornare a NeoStation?", @"Cancel": @"Annulla", @"Quit": @"Esci",
        @"ARMSX2 setting failed": @"Impostazione ARMSX2 non riuscita", @"RetroAchievements error": @"Errore RetroAchievements",
        @"Account": @"Account", @"Username": @"Nome utente", @"Password": @"Password",
        @"Link account": @"Collega account", @"Unlink account": @"Scollega account", @"Account linked.": @"Account collegato.",
        @"No account linked.": @"Nessun account collegato.", @"Done.": @"Fatto.", @"Operation failed.": @"Operazione non riuscita.",
        @"Connecting…": @"Connessione…", @"Disconnecting…": @"Disconnessione…", @"Done": @"Fatto", @"Active": @"Attivo",
        @"Login saved": @"Accesso salvato", @"Enabled": @"Attivato", @"Disabled": @"Disattivato",
        @"Not connected": @"Non connesso", @"Status": @"Stato", @"Mode": @"Modalità",
        @"Notifications": @"Notifiche", @"Leaderboard notifications": @"Notifiche classifiche", @"Overlays": @"Sovrapposizioni",
        @"ARMSX2 game menu": @"Menu di gioco ARMSX2", @"Touch controls updated.": @"Controlli touch aggiornati.",
        @"Screen format updated.": @"Formato schermo aggiornato.", @"Cheats enabled.": @"Trucchi attivati.",
        @"Cheats disabled.": @"Trucchi disattivati.", @"Cheats and patches reloaded.": @"Trucchi e patch ricaricati.",
        @"State loaded.": @"Stato caricato.", @"State saved.": @"Stato salvato.", @"PS2 BIOS": @"BIOS PS2",
        @"ARMSX2 ready.": @"ARMSX2 pronto.", @"Internal resolution: %.0f×": @"Risoluzione interna: %.0f×",
        @"State saved in slot %u.": @"Stato salvato nello slot %u.", @"State loaded from slot %u.": @"Stato caricato dallo slot %u.",
        @"Manual graphics hacks": @"Hack grafici manuali", @"GPU palette conversion": @"Conversione palette GPU",
        @"CPU framebuffer conversion": @"Conversione framebuffer CPU", @"Read targets when closing": @"Leggi destinazioni alla chiusura",
        @"Disable depth emulation": @"Disattiva emulazione profondità", @"Disable partial invalidation": @"Disattiva invalidazione parziale",
        @"Preload frame data": @"Precarica dati frame", @"Estimate texture region": @"Stima regione texture",
        @"Draw buffering": @"Buffering disegno", @"Unscaled palette draw": @"Disegno palette non scalato",
        @"Align sprites": @"Allinea sprite", @"Merge sprites": @"Unisci sprite", @"Force even sprite position": @"Forza posizione pari sprite"
      },
      @"id": @{
        @"Standard": @"Standar",
        @"Per-game graphics settings are applied live. Advanced hacks keep ARMSX2/GameDB automatic behavior unless explicitly overridden.": @"Pengaturan grafis per game diterapkan langsung. Hack lanjutan tetap mengikuti perilaku otomatis ARMSX2/GameDB kecuali diubah secara eksplisit.",
        @"Automatic removes this game's override and returns control to ARMSX2/GameDB.": @"Otomatis menghapus pengaturan khusus game ini dan mengembalikan kontrol ke ARMSX2/GameDB.",
        @"Hardcore RetroAchievements can disable cheats and save-state features.": @"Mode Hardcore RetroAchievements dapat membatasi cheat dan fitur status simpan.",
        @"Choose whether NeoStation's PS2 touch overlay is visible.": @"Pilih apakah kontrol sentuh PS2 NeoStation ditampilkan.",
        @"RetroAchievements setting updated.": @"Pengaturan RetroAchievements diperbarui.",
        @"RetroAchievements account linked.": @"Akun RetroAchievements ditautkan.",
        @"RetroAchievements account unlinked.": @"Akun RetroAchievements dilepas.",
        @"Graphics hack updated for this game.": @"Hack grafis untuk game ini diperbarui.",
        @"Enter your username and password.": @"Masukkan nama pengguna dan kata sandi.",
        @"Connect the RetroAchievements account used by ARMSX2. The password is sent to the native ARMSX2 login flow and is never stored by NeoStation.": @"Tautkan akun RetroAchievements yang digunakan ARMSX2. Kata sandi dikirim ke proses login native ARMSX2 dan tidak pernah disimpan oleh NeoStation.",
        @"ARMSX2 applies these options through its native PCSX2 RetroAchievements implementation. Hardcore can restrict cheats and save-state features.": @"ARMSX2 menerapkan opsi ini melalui implementasi RetroAchievements native PCSX2. Hardcore dapat membatasi cheat dan fitur status simpan.",
        @"Auto": @"Otomatis", @"Stretch": @"Regangkan",
        @"Back": @"Kembali", @"Resume Game": @"Lanjutkan game", @"Graphics": @"Grafis",
        @"Compatibility / Cheats": @"Kompatibilitas / Cheat", @"Controls": @"Kontrol",
        @"Save State": @"Simpan status", @"Load State": @"Muat status", @"Quit Game": @"Keluar dari game",
        @"Internal Resolution": @"Resolusi internal", @"Screen Format": @"Format layar", @"Graphics Hacks": @"Hack grafis",
        @"Per-game advanced GS options": @"Opsi GS lanjutan per game", @"Automatic": @"Otomatis",
        @"Automatic (ARMSX2/GameDB)": @"Otomatis (ARMSX2/GameDB)", @"On": @"Aktif", @"Off": @"Nonaktif",
        @"Enable Cheats": @"Aktifkan cheat", @"Reload Cheats / Patches": @"Muat ulang cheat / patch",
        @"Touch Controls": @"Kontrol sentuh", @"Slot": @"Slot", @"Saved state available": @"Status simpan tersedia",
        @"Empty": @"Kosong", @"Return to NeoStation?": @"Kembali ke NeoStation?", @"Cancel": @"Batal", @"Quit": @"Keluar",
        @"ARMSX2 setting failed": @"Pengaturan ARMSX2 gagal", @"RetroAchievements error": @"Kesalahan RetroAchievements",
        @"Account": @"Akun", @"Username": @"Nama pengguna", @"Password": @"Kata sandi",
        @"Link account": @"Tautkan akun", @"Unlink account": @"Putuskan akun", @"Account linked.": @"Akun tertaut.",
        @"No account linked.": @"Tidak ada akun tertaut.", @"Done.": @"Selesai.", @"Operation failed.": @"Operasi gagal.",
        @"Connecting…": @"Menghubungkan…", @"Disconnecting…": @"Memutuskan…", @"Done": @"Selesai", @"Active": @"Aktif",
        @"Login saved": @"Login tersimpan", @"Enabled": @"Aktif", @"Disabled": @"Nonaktif",
        @"Not connected": @"Tidak terhubung", @"Status": @"Status", @"Mode": @"Mode",
        @"Notifications": @"Notifikasi", @"Leaderboard notifications": @"Notifikasi papan peringkat", @"Overlays": @"Overlay",
        @"ARMSX2 game menu": @"Menu game ARMSX2", @"Touch controls updated.": @"Kontrol sentuh diperbarui.",
        @"Screen format updated.": @"Format layar diperbarui.", @"Cheats enabled.": @"Cheat diaktifkan.",
        @"Cheats disabled.": @"Cheat dinonaktifkan.", @"Cheats and patches reloaded.": @"Cheat dan patch dimuat ulang.",
        @"State loaded.": @"Status dimuat.", @"State saved.": @"Status disimpan.", @"PS2 BIOS": @"BIOS PS2",
        @"ARMSX2 ready.": @"ARMSX2 siap.", @"Internal resolution: %.0f×": @"Resolusi internal: %.0f×",
        @"State saved in slot %u.": @"Status disimpan di slot %u.", @"State loaded from slot %u.": @"Status dimuat dari slot %u.",
        @"Manual graphics hacks": @"Hack grafis manual", @"GPU palette conversion": @"Konversi palet GPU",
        @"CPU framebuffer conversion": @"Konversi framebuffer CPU", @"Read targets when closing": @"Baca target saat menutup",
        @"Disable depth emulation": @"Nonaktifkan emulasi kedalaman", @"Disable partial invalidation": @"Nonaktifkan invalidasi parsial",
        @"Preload frame data": @"Pramuat data frame", @"Estimate texture region": @"Perkirakan wilayah tekstur",
        @"Draw buffering": @"Buffer gambar", @"Unscaled palette draw": @"Gambar palet tanpa skala",
        @"Align sprites": @"Sejajarkan sprite", @"Merge sprites": @"Gabungkan sprite", @"Force even sprite position": @"Paksa posisi sprite genap"
      },
      @"fr": @{
        @"Standard": @"Standard",
        @"Per-game graphics settings are applied live. Advanced hacks keep ARMSX2/GameDB automatic behavior unless explicitly overridden.": @"Les réglages graphiques par jeu sont appliqués en direct. Les hacks avancés conservent le comportement automatique ARMSX2/GameDB sauf remplacement explicite.",
        @"Automatic removes this game's override and returns control to ARMSX2/GameDB.": @"Automatique supprime le réglage propre à ce jeu et rend le contrôle à ARMSX2/GameDB.",
        @"Hardcore RetroAchievements can disable cheats and save-state features.": @"Le mode Hardcore de RetroAchievements peut désactiver les cheats et certaines fonctions de save state.",
        @"Choose whether NeoStation's PS2 touch overlay is visible.": @"Choisissez si les commandes tactiles PS2 de NeoStation sont visibles.",
        @"RetroAchievements setting updated.": @"Réglage RetroAchievements mis à jour.",
        @"RetroAchievements account linked.": @"Compte RetroAchievements lié.",
        @"RetroAchievements account unlinked.": @"Compte RetroAchievements déconnecté.",
        @"Graphics hack updated for this game.": @"Hack graphique mis à jour pour ce jeu.",
        @"Enter your username and password.": @"Saisissez votre nom d’utilisateur et votre mot de passe.",
        @"Connect the RetroAchievements account used by ARMSX2. The password is sent to the native ARMSX2 login flow and is never stored by NeoStation.": @"Connectez le compte RetroAchievements utilisé par ARMSX2. Le mot de passe est transmis au flux de connexion natif ARMSX2 et n’est jamais enregistré par NeoStation.",
        @"ARMSX2 applies these options through its native PCSX2 RetroAchievements implementation. Hardcore can restrict cheats and save-state features.": @"ARMSX2 applique ces options via son implémentation RetroAchievements native PCSX2. Le mode Hardcore peut limiter les cheats et les fonctions de save state.",
        @"Auto": @"Auto", @"Stretch": @"Étendre",
        @"Back": @"Retour", @"Resume Game": @"Reprendre le jeu", @"Graphics": @"Graphismes",
        @"Compatibility / Cheats": @"Hacks / Cheats", @"Controls": @"Commandes",
        @"Save State": @"Sauvegarder un état", @"Load State": @"Charger un état", @"Quit Game": @"Quitter le jeu",
        @"Internal Resolution": @"Résolution interne", @"Screen Format": @"Format d’écran", @"Graphics Hacks": @"Hacks graphiques",
        @"Per-game advanced GS options": @"Options GS avancées par jeu", @"Automatic": @"Automatique",
        @"Automatic (ARMSX2/GameDB)": @"Automatique (ARMSX2/GameDB)", @"On": @"Activé", @"Off": @"Désactivé",
        @"Enable Cheats": @"Activer les cheats", @"Reload Cheats / Patches": @"Recharger cheats / patches",
        @"Touch Controls": @"Commandes tactiles", @"Slot": @"Slot", @"Saved state available": @"État sauvegardé disponible",
        @"Empty": @"Vide", @"Return to NeoStation?": @"Revenir à NeoStation ?", @"Cancel": @"Annuler", @"Quit": @"Quitter",
        @"ARMSX2 setting failed": @"Échec du réglage ARMSX2", @"RetroAchievements error": @"Erreur RetroAchievements",
        @"Account": @"Compte", @"Username": @"Nom d’utilisateur", @"Password": @"Mot de passe",
        @"Link account": @"Lier le compte", @"Unlink account": @"Déconnecter le compte", @"Account linked.": @"Compte lié.",
        @"No account linked.": @"Aucun compte lié.", @"Done.": @"Terminé.", @"Operation failed.": @"L’opération a échoué.",
        @"Connecting…": @"Connexion…", @"Disconnecting…": @"Déconnexion…", @"Done": @"Terminé", @"Active": @"Actif",
        @"Login saved": @"Connexion enregistrée", @"Enabled": @"Activé", @"Disabled": @"Désactivé",
        @"Not connected": @"Non connecté", @"Status": @"Statut", @"Mode": @"Mode",
        @"Notifications": @"Notifications", @"Leaderboard notifications": @"Notifications des classements", @"Overlays": @"Superpositions",
        @"ARMSX2 game menu": @"Menu du jeu ARMSX2", @"Touch controls updated.": @"Commandes tactiles mises à jour.",
        @"Screen format updated.": @"Format d’écran mis à jour.", @"Cheats enabled.": @"Cheats activés.",
        @"Cheats disabled.": @"Cheats désactivés.", @"Cheats and patches reloaded.": @"Cheats et patches rechargés.",
        @"State loaded.": @"État chargé.", @"State saved.": @"État sauvegardé.", @"PS2 BIOS": @"BIOS PS2",
        @"ARMSX2 ready.": @"ARMSX2 prêt.", @"Internal resolution: %.0f×": @"Résolution interne : %.0f×",
        @"State saved in slot %u.": @"État sauvegardé dans le slot %u.", @"State loaded from slot %u.": @"État chargé depuis le slot %u.",
        @"Manual graphics hacks": @"Hacks graphiques manuels", @"GPU palette conversion": @"Conversion des palettes par le GPU",
        @"CPU framebuffer conversion": @"Conversion du framebuffer par le CPU", @"Read targets when closing": @"Lire les cibles à la fermeture",
        @"Disable depth emulation": @"Désactiver l’émulation de profondeur", @"Disable partial invalidation": @"Désactiver l’invalidation partielle",
        @"Preload frame data": @"Précharger les données d’image", @"Estimate texture region": @"Estimer la région des textures",
        @"Draw buffering": @"Mise en tampon du rendu", @"Unscaled palette draw": @"Palettes à la résolution native",
        @"Align sprites": @"Aligner les sprites", @"Merge sprites": @"Fusionner les sprites", @"Force even sprite position": @"Forcer la position paire des sprites"
      }
    };
  });
  return values;
}
}

NSString* ARMSX2CanonicalLocale(NSString* identifier) {
  NSString* normalized = [[identifier ?: @"en"
      stringByReplacingOccurrencesOfString:@"-" withString:@"_"] lowercaseString];
  if ([normalized hasPrefix:@"zh_hant"] || [normalized hasPrefix:@"zh_tw"] ||
      [normalized hasPrefix:@"zh_hk"] || [normalized hasPrefix:@"zh_mo"]) {
    return @"zh_Hant";
  }
  NSString* language = [normalized componentsSeparatedByString:@"_"].firstObject ?: @"en";
  static NSSet<NSString*>* supported;
  static dispatch_once_t once;
  dispatch_once(&once, ^{
    supported = [NSSet setWithArray:@[@"de", @"en", @"es", @"fr", @"id", @"it",
                                      @"ja", @"ko", @"pt", @"ru", @"zh"]];
  });
  return [supported containsObject:language] ? language : @"en";
}

NSString* ARMSX2LocalizedText(NSString* english, NSString* french, NSString* localeIdentifier) {
  NSString* locale = ARMSX2CanonicalLocale(localeIdentifier);
  if ([locale isEqualToString:@"en"]) return english ?: @"";
  NSDictionary* translations = ARMSX2Translations()[locale];
  NSString* translated = translations[english ?: @""];
  if (translated.length) return translated;
  if ([locale isEqualToString:@"fr"] && french.length) return french;
  return english ?: @"";
}
