import 'package:flutter/widgets.dart';

class NeoPlayLocale {
  static String get(BuildContext context, String key) {
    final locale = Localizations.localeOf(context);
    final traditional = locale.languageCode == 'zh' && (locale.scriptCode?.toLowerCase() == 'hant' || const ['TW', 'HK', 'MO'].contains(locale.countryCode?.toUpperCase()));
    final language = traditional ? 'zh_Hant' : locale.languageCode;
    return (values[language] ?? values['en']!)[key]!;
  }
  static const values = <String, Map<String, String>>{
    'en': {'subtitle':'Play on another screen', 'description':'Share the NeoStation screen and game audio on your trusted local network. Menus are included; the microphone stays off.', 'discover':'Find screens', 'empty':'No receiver found. Use the same Wi-Fi and allow local network access.', 'windows':'Windows requires the free NeoPlay Receiver and Edge or Chrome.', 'cast':'Chromecast uses Google Cast. Its video buffer can add several seconds of delay.', 'pin':'Code shown on the PC', 'connect':'Connect', 'disconnect':'Stop sharing', 'close':'Close', 'idle':'Not sharing', 'connecting':'Connecting…', 'capturing':'Sending — waiting for receiver playback…', 'streaming':'Receiver reports playback', 'failed':'Sharing stopped', 'error':'Check permissions, the receiver and its code, then retry. Your game has not been stopped by NeoPlay.', 'prototype':'Experimental: Windows and Chromecast still require separate real-device validation.'},
    'fr': {'subtitle':'Jouer sur un autre écran', 'description':'Partagez l’écran de NeoStation et le son du jeu sur votre réseau local de confiance. Les menus sont inclus ; le microphone reste désactivé.', 'discover':'Rechercher les écrans', 'empty':'Aucun récepteur détecté. Utilisez le même Wi-Fi et autorisez l’accès au réseau local.', 'windows':'Windows nécessite NeoPlay Receiver, gratuit, et Edge ou Chrome.', 'cast':'Chromecast utilise Google Cast. Sa mémoire tampon vidéo peut ajouter plusieurs secondes de délai.', 'pin':'Code affiché sur le PC', 'connect':'Connecter', 'disconnect':'Arrêter la diffusion', 'close':'Fermer', 'idle':'Aucune diffusion', 'connecting':'Connexion…', 'capturing':'Envoi — attente de lecture sur le récepteur…', 'streaming':'Lecture signalée par le récepteur', 'failed':'Diffusion arrêtée', 'error':'Vérifiez les autorisations, le récepteur et son code, puis réessayez. NeoPlay n’a pas arrêté votre jeu.', 'prototype':'Expérimental : Windows et Chromecast doivent encore être validés séparément sur appareils réels.'},
    'de': {'subtitle':'Auf einem anderen Bildschirm spielen', 'description':'Teile den NeoStation-Bildschirm und den Spielton im vertrauenswürdigen lokalen Netzwerk. Menüs werden übertragen; das Mikrofon bleibt aus.', 'discover':'Bildschirme suchen', 'empty':'Kein Empfänger gefunden. Verwende dasselbe WLAN und erlaube den lokalen Netzwerkzugriff.', 'windows':'Windows benötigt den kostenlosen NeoPlay Receiver und Edge oder Chrome.', 'cast':'Chromecast nutzt Google Cast. Der Videopuffer kann mehrere Sekunden Verzögerung verursachen.', 'pin':'Auf dem PC angezeigter Code', 'connect':'Verbinden', 'disconnect':'Übertragung beenden', 'close':'Schließen', 'idle':'Keine Übertragung', 'connecting':'Verbindung wird hergestellt…', 'capturing':'Übertragung — warte auf Wiedergabe am Empfänger…', 'streaming':'Empfänger meldet Wiedergabe', 'failed':'Übertragung beendet', 'error':'Prüfe Berechtigungen, Empfänger und Code und versuche es erneut. NeoPlay hat dein Spiel nicht beendet.', 'prototype':'Experimentell: Windows und Chromecast müssen noch getrennt auf echten Geräten geprüft werden.'},
    'es': {'subtitle':'Jugar en otra pantalla', 'description':'Comparte la pantalla de NeoStation y el audio del juego en tu red local de confianza. Se incluyen los menús; el micrófono permanece apagado.', 'discover':'Buscar pantallas', 'empty':'No se encontró ningún receptor. Usa la misma red Wi-Fi y permite el acceso a la red local.', 'windows':'Windows requiere NeoPlay Receiver, gratuito, y Edge o Chrome.', 'cast':'Chromecast usa Google Cast. Su búfer de vídeo puede añadir varios segundos de retraso.', 'pin':'Código mostrado en el PC', 'connect':'Conectar', 'disconnect':'Detener transmisión', 'close':'Cerrar', 'idle':'Sin transmisión', 'connecting':'Conectando…', 'capturing':'Enviando — esperando la reproducción en el receptor…', 'streaming':'El receptor indica reproducción', 'failed':'Transmisión detenida', 'error':'Comprueba los permisos, el receptor y su código e inténtalo de nuevo. NeoPlay no ha detenido tu juego.', 'prototype':'Experimental: Windows y Chromecast aún requieren pruebas independientes en dispositivos reales.'},
    'it': {'subtitle':'Gioca su un altro schermo', 'description':'Condividi lo schermo di NeoStation e l’audio del gioco sulla tua rete locale fidata. Sono inclusi i menu; il microfono resta spento.', 'discover':'Cerca schermi', 'empty':'Nessun ricevitore trovato. Usa la stessa rete Wi-Fi e consenti l’accesso alla rete locale.', 'windows':'Windows richiede NeoPlay Receiver, gratuito, ed Edge o Chrome.', 'cast':'Chromecast usa Google Cast. Il buffer video può aggiungere diversi secondi di ritardo.', 'pin':'Codice mostrato sul PC', 'connect':'Connetti', 'disconnect':'Interrompi condivisione', 'close':'Chiudi', 'idle':'Nessuna condivisione', 'connecting':'Connessione…', 'capturing':'Invio — in attesa della riproduzione sul ricevitore…', 'streaming':'Il ricevitore segnala la riproduzione', 'failed':'Condivisione interrotta', 'error':'Controlla le autorizzazioni, il ricevitore e il codice, poi riprova. NeoPlay non ha interrotto il gioco.', 'prototype':'Sperimentale: Windows e Chromecast richiedono ancora verifiche separate su dispositivi reali.'},
    'pt': {'subtitle':'Jogar noutra tela', 'description':'Partilhe a tela do NeoStation e o áudio do jogo na sua rede local de confiança. Os menus são incluídos; o microfone fica desligado.', 'discover':'Procurar telas', 'empty':'Nenhum recetor encontrado. Use a mesma rede Wi-Fi e permita acesso à rede local.', 'windows':'O Windows requer o NeoPlay Receiver, gratuito, e o Edge ou Chrome.', 'cast':'O Chromecast usa Google Cast. O buffer de vídeo pode acrescentar vários segundos de atraso.', 'pin':'Código apresentado no PC', 'connect':'Ligar', 'disconnect':'Parar transmissão', 'close':'Fechar', 'idle':'Sem transmissão', 'connecting':'A ligar…', 'capturing':'A enviar — a aguardar reprodução no recetor…', 'streaming':'O recetor indica reprodução', 'failed':'Transmissão parada', 'error':'Verifique as permissões, o recetor e o código e tente novamente. O NeoPlay não parou o jogo.', 'prototype':'Experimental: Windows e Chromecast ainda precisam de validação separada em dispositivos reais.'},
    'ru': {'subtitle':'Играть на другом экране', 'description':'Передавайте экран NeoStation и звук игры по доверенной локальной сети. Меню также передаются; микрофон остаётся выключенным.', 'discover':'Найти экраны', 'empty':'Приёмники не найдены. Подключитесь к той же сети Wi-Fi и разрешите доступ к локальной сети.', 'windows':'Для Windows нужны бесплатный NeoPlay Receiver и Edge или Chrome.', 'cast':'Chromecast использует Google Cast. Видеобуфер может добавлять задержку в несколько секунд.', 'pin':'Код на экране ПК', 'connect':'Подключить', 'disconnect':'Остановить трансляцию', 'close':'Закрыть', 'idle':'Трансляция не идёт', 'connecting':'Подключение…', 'capturing':'Передача — ожидание воспроизведения на приёмнике…', 'streaming':'Приёмник сообщает о воспроизведении', 'failed':'Трансляция остановлена', 'error':'Проверьте разрешения, приёмник и код и повторите попытку. NeoPlay не останавливал игру.', 'prototype':'Экспериментальная функция: Windows и Chromecast ещё требуют отдельных проверок на реальных устройствах.'},
    'zh': {'subtitle':'在另一块屏幕上游玩', 'description':'在可信的局域网中共享 NeoStation 画面和游戏声音。菜单也会共享；麦克风保持关闭。', 'discover':'查找屏幕', 'empty':'未发现接收端。请连接同一 Wi-Fi 并允许访问本地网络。', 'windows':'Windows 需要免费的 NeoPlay Receiver 以及 Edge 或 Chrome。', 'cast':'Chromecast 使用 Google Cast，视频缓冲可能增加数秒延迟。', 'pin':'电脑上显示的代码', 'connect':'连接', 'disconnect':'停止投屏', 'close':'关闭', 'idle':'未投屏', 'connecting':'正在连接…', 'capturing':'正在发送，等待接收端播放…', 'streaming':'接收端报告正在播放', 'failed':'投屏已停止', 'error':'请检查权限、接收端及代码后重试。NeoPlay 未停止您的游戏。', 'prototype':'实验性功能：Windows 与 Chromecast 仍需分别在真实设备上验证。'},
    'zh_Hant': {'subtitle':'在另一個螢幕上遊玩', 'description':'在可信任的區域網路中分享 NeoStation 畫面和遊戲聲音。選單也會分享；麥克風保持關閉。', 'discover':'搜尋螢幕', 'empty':'找不到接收端。請連接相同 Wi-Fi 並允許存取區域網路。', 'windows':'Windows 需要免費的 NeoPlay Receiver 以及 Edge 或 Chrome。', 'cast':'Chromecast 使用 Google Cast，影片緩衝可能增加數秒延遲。', 'pin':'電腦上顯示的代碼', 'connect':'連接', 'disconnect':'停止投放', 'close':'關閉', 'idle':'未投放', 'connecting':'正在連接…', 'capturing':'正在傳送，等待接收端播放…', 'streaming':'接收端回報正在播放', 'failed':'投放已停止', 'error':'請檢查權限、接收端及代碼後重試。NeoPlay 並未停止您的遊戲。', 'prototype':'實驗性功能：Windows 與 Chromecast 仍需分別在真實裝置上驗證。'},
    'id': {'subtitle':'Main di layar lain', 'description':'Bagikan layar NeoStation dan audio gim di jaringan lokal tepercaya. Menu ikut dibagikan; mikrofon tetap mati.', 'discover':'Cari layar', 'empty':'Penerima tidak ditemukan. Gunakan Wi-Fi yang sama dan izinkan akses jaringan lokal.', 'windows':'Windows memerlukan NeoPlay Receiver gratis serta Edge atau Chrome.', 'cast':'Chromecast menggunakan Google Cast. Buffer video dapat menambah jeda beberapa detik.', 'pin':'Kode yang tampil di PC', 'connect':'Hubungkan', 'disconnect':'Hentikan siaran', 'close':'Tutup', 'idle':'Tidak menyiarkan', 'connecting':'Menghubungkan…', 'capturing':'Mengirim — menunggu pemutaran di penerima…', 'streaming':'Penerima melaporkan pemutaran', 'failed':'Siaran dihentikan', 'error':'Periksa izin, penerima, dan kodenya, lalu coba lagi. NeoPlay tidak menghentikan gim Anda.', 'prototype':'Eksperimental: Windows dan Chromecast masih perlu divalidasi secara terpisah pada perangkat nyata.'},
    'ja': {'subtitle':'別の画面でプレイ', 'description':'信頼できるローカルネットワークで NeoStation の画面とゲーム音声を共有します。メニューも含まれます。マイクはオフのままです。', 'discover':'画面を検索', 'empty':'受信機が見つかりません。同じ Wi-Fi に接続し、ローカルネットワークへのアクセスを許可してください。', 'windows':'Windows には無料の NeoPlay Receiver と Edge または Chrome が必要です。', 'cast':'Chromecast は Google Cast を使います。動画バッファーにより数秒の遅延が加わる場合があります。', 'pin':'PC に表示されたコード', 'connect':'接続', 'disconnect':'共有を停止', 'close':'閉じる', 'idle':'共有していません', 'connecting':'接続中…', 'capturing':'送信中 — 受信機での再生を待機しています…', 'streaming':'受信機から再生の報告があります', 'failed':'共有が停止しました', 'error':'権限、受信機、コードを確認して再試行してください。NeoPlay はゲームを停止していません。', 'prototype':'実験段階：Windows と Chromecast は実機での個別検証がまだ必要です。'},
    'ko': {'subtitle':'다른 화면에서 플레이', 'description':'신뢰할 수 있는 로컬 네트워크에서 NeoStation 화면과 게임 소리를 공유합니다. 메뉴도 포함되며 마이크는 꺼진 상태로 유지됩니다.', 'discover':'화면 찾기', 'empty':'수신기를 찾을 수 없습니다. 같은 Wi-Fi에 연결하고 로컬 네트워크 접근을 허용하세요.', 'windows':'Windows에는 무료 NeoPlay Receiver와 Edge 또는 Chrome이 필요합니다.', 'cast':'Chromecast는 Google Cast를 사용합니다. 영상 버퍼로 인해 몇 초의 지연이 발생할 수 있습니다.', 'pin':'PC에 표시된 코드', 'connect':'연결', 'disconnect':'공유 중지', 'close':'닫기', 'idle':'공유하지 않음', 'connecting':'연결 중…', 'capturing':'전송 중 — 수신기 재생을 기다리는 중…', 'streaming':'수신기가 재생 중이라고 보고함', 'failed':'공유 중지됨', 'error':'권한, 수신기 및 코드를 확인한 후 다시 시도하세요. NeoPlay는 게임을 중지하지 않았습니다.', 'prototype':'실험적 기능: Windows와 Chromecast는 실제 기기에서 별도로 검증해야 합니다.'},
  };
}
