import 'package:flutter/widgets.dart';

abstract final class PortsLocale {
  static const values = <String, Map<String, String>>{
    'en': {'import':'Import','dusklight':'DuskLight','kartpad':'Mario Kart Pad','kartpadImported':'Mario Kart Wii imported.','kartpadImportFailed':'Mario Kart Pad import failed. Check the file and available storage.','kartpadUnsupportedDisc':'Select a PAL Mario Kart Wii disc with ID RMCP01.','kartpadUnsupportedRevision':'Mario Kart Pad currently requires RMCP01, disc 0, revision 0.','kartpadFormatUnsupported':'KartPad import currently accepts a raw ISO. WBFS and extracted DATA support will follow with the embedded Core.','kartpadCorePending':'Mario Kart Pad is imported, but its embedded native Core is still being integrated.'},
    'fr': {'import':'Importer','dusklight':'DuskLight','kartpad':'Mario Kart Pad','kartpadImported':'Mario Kart Wii a été importé.','kartpadImportFailed':'Échec de l’import Mario Kart Pad. Vérifiez le fichier et l’espace disponible.','kartpadUnsupportedDisc':'Sélectionnez un disque PAL de Mario Kart Wii avec l’ID RMCP01.','kartpadUnsupportedRevision':'Mario Kart Pad requiert actuellement RMCP01, disque 0, révision 0.','kartpadFormatUnsupported':'L’import KartPad accepte actuellement un ISO brut. Le WBFS et le dossier DATA seront ajoutés avec le Core embarqué.','kartpadCorePending':'Mario Kart Pad est importé, mais son Core natif embarqué est encore en cours d’intégration.'},
    'es': {'import':'Importar','dusklight':'DuskLight','kartpad':'Mario Kart Pad','kartpadImported':'Mario Kart Wii importado.','kartpadImportFailed':'Error al importar Mario Kart Pad. Comprueba el archivo y el espacio disponible.','kartpadUnsupportedDisc':'Selecciona un disco PAL de Mario Kart Wii con ID RMCP01.','kartpadUnsupportedRevision':'Mario Kart Pad requiere RMCP01, disco 0, revisión 0.','kartpadFormatUnsupported':'La importación de KartPad acepta por ahora un ISO sin comprimir. WBFS y DATA llegarán con el Core integrado.','kartpadCorePending':'Mario Kart Pad está importado, pero su Core nativo integrado aún se está incorporando.'},
    'pt': {'import':'Importar','dusklight':'DuskLight','kartpad':'Mario Kart Pad','kartpadImported':'Mario Kart Wii importado.','kartpadImportFailed':'Falha ao importar Mario Kart Pad. Verifique o arquivo e o espaço disponível.','kartpadUnsupportedDisc':'Selecione um disco PAL do Mario Kart Wii com ID RMCP01.','kartpadUnsupportedRevision':'Mario Kart Pad requer RMCP01, disco 0, revisão 0.','kartpadFormatUnsupported':'A importação do KartPad aceita por enquanto ISO bruto. WBFS e DATA serão adicionados com o Core integrado.','kartpadCorePending':'Mario Kart Pad foi importado, mas o Core nativo integrado ainda está em desenvolvimento.'},
    'de': {'import':'Importieren','dusklight':'DuskLight','kartpad':'Mario Kart Pad','kartpadImported':'Mario Kart Wii wurde importiert.','kartpadImportFailed':'Mario Kart Pad konnte nicht importiert werden. Prüfe Datei und freien Speicher.','kartpadUnsupportedDisc':'Wähle eine PAL-Mario-Kart-Wii-Disc mit der ID RMCP01.','kartpadUnsupportedRevision':'Mario Kart Pad benötigt derzeit RMCP01, Disc 0, Revision 0.','kartpadFormatUnsupported':'KartPad akzeptiert derzeit ein rohes ISO. WBFS und DATA folgen mit dem eingebetteten Core.','kartpadCorePending':'Mario Kart Pad wurde importiert, der eingebettete native Core wird aber noch integriert.'},
    'it': {'import':'Importa','dusklight':'DuskLight','kartpad':'Mario Kart Pad','kartpadImported':'Mario Kart Wii importato.','kartpadImportFailed':'Importazione Mario Kart Pad non riuscita. Controlla il file e lo spazio disponibile.','kartpadUnsupportedDisc':'Seleziona un disco PAL di Mario Kart Wii con ID RMCP01.','kartpadUnsupportedRevision':'Mario Kart Pad richiede RMCP01, disco 0, revisione 0.','kartpadFormatUnsupported':'Per ora KartPad accetta un ISO grezzo. WBFS e DATA arriveranno con il Core integrato.','kartpadCorePending':'Mario Kart Pad è importato, ma il Core nativo integrato è ancora in fase di integrazione.'},
    'ru': {'import':'Импорт','dusklight':'DuskLight','kartpad':'Mario Kart Pad','kartpadImported':'Mario Kart Wii импортирована.','kartpadImportFailed':'Не удалось импортировать Mario Kart Pad. Проверьте файл и свободное место.','kartpadUnsupportedDisc':'Выберите PAL-диск Mario Kart Wii с ID RMCP01.','kartpadUnsupportedRevision':'Mario Kart Pad требует RMCP01, диск 0, ревизия 0.','kartpadFormatUnsupported':'Пока KartPad принимает только обычный ISO. WBFS и DATA будут добавлены вместе со встроенным Core.','kartpadCorePending':'Mario Kart Pad импортирован, но встроенный нативный Core ещё интегрируется.'},
    'zh': {'import':'导入','dusklight':'DuskLight','kartpad':'Mario Kart Pad','kartpadImported':'已导入 Mario Kart Wii。','kartpadImportFailed':'Mario Kart Pad 导入失败。请检查文件和可用空间。','kartpadUnsupportedDisc':'请选择游戏 ID 为 RMCP01 的 PAL 版 Mario Kart Wii 光盘。','kartpadUnsupportedRevision':'Mario Kart Pad 当前要求 RMCP01、光盘 0、修订版 0。','kartpadFormatUnsupported':'KartPad 当前仅接受原始 ISO。WBFS 和 DATA 将随内置 Core 集成加入。','kartpadCorePending':'Mario Kart Pad 已导入，但其内置原生 Core 仍在集成中。'},
    'zh_Hant': {'import':'匯入','dusklight':'DuskLight','kartpad':'Mario Kart Pad','kartpadImported':'已匯入 Mario Kart Wii。','kartpadImportFailed':'Mario Kart Pad 匯入失敗。請檢查檔案與可用空間。','kartpadUnsupportedDisc':'請選擇遊戲 ID 為 RMCP01 的 PAL 版 Mario Kart Wii 光碟。','kartpadUnsupportedRevision':'Mario Kart Pad 目前需要 RMCP01、光碟 0、修訂版 0。','kartpadFormatUnsupported':'KartPad 目前只接受原始 ISO。WBFS 與 DATA 將隨內建 Core 整合加入。','kartpadCorePending':'Mario Kart Pad 已匯入，但內建原生 Core 仍在整合中。'},
    'id': {'import':'Impor','dusklight':'DuskLight','kartpad':'Mario Kart Pad','kartpadImported':'Mario Kart Wii berhasil diimpor.','kartpadImportFailed':'Impor Mario Kart Pad gagal. Periksa file dan ruang penyimpanan.','kartpadUnsupportedDisc':'Pilih disc PAL Mario Kart Wii dengan ID RMCP01.','kartpadUnsupportedRevision':'Mario Kart Pad saat ini memerlukan RMCP01, disc 0, revisi 0.','kartpadFormatUnsupported':'Impor KartPad saat ini menerima ISO mentah. WBFS dan DATA akan ditambahkan bersama Core tertanam.','kartpadCorePending':'Mario Kart Pad sudah diimpor, tetapi Core native tertanam masih dalam proses integrasi.'},
    'ja': {'import':'インポート','dusklight':'DuskLight','kartpad':'Mario Kart Pad','kartpadImported':'Mario Kart Wii をインポートしました。','kartpadImportFailed':'Mario Kart Pad のインポートに失敗しました。ファイルと空き容量を確認してください。','kartpadUnsupportedDisc':'ゲーム ID が RMCP01 の PAL 版 Mario Kart Wii ディスクを選択してください。','kartpadUnsupportedRevision':'Mario Kart Pad は現在 RMCP01、ディスク 0、リビジョン 0 が必要です。','kartpadFormatUnsupported':'KartPad のインポートは現在 RAW ISO のみ対応しています。WBFS と DATA は組み込み Core とともに追加します。','kartpadCorePending':'Mario Kart Pad はインポート済みですが、組み込みネイティブ Core はまだ統合中です。'},
    'ko': {'import':'가져오기','dusklight':'DuskLight','kartpad':'Mario Kart Pad','kartpadImported':'Mario Kart Wii를 가져왔습니다.','kartpadImportFailed':'Mario Kart Pad 가져오기에 실패했습니다. 파일과 저장 공간을 확인하세요.','kartpadUnsupportedDisc':'게임 ID가 RMCP01인 PAL Mario Kart Wii 디스크를 선택하세요.','kartpadUnsupportedRevision':'Mario Kart Pad는 현재 RMCP01, 디스크 0, 리비전 0이 필요합니다.','kartpadFormatUnsupported':'KartPad 가져오기는 현재 RAW ISO만 지원합니다. WBFS와 DATA는 내장 Core와 함께 추가됩니다.','kartpadCorePending':'Mario Kart Pad는 가져왔지만 내장 네이티브 Core는 아직 통합 중입니다.'},
  };

  static String localeKey(Locale locale) => locale.languageCode == 'zh' &&
          (locale.scriptCode?.toLowerCase() == 'hant' ||
              ['TW', 'HK', 'MO'].contains(locale.countryCode?.toUpperCase()))
      ? 'zh_Hant'
      : locale.languageCode;

  static String forLocale(Locale locale, String key) {
    final table = values[localeKey(locale)] ?? values['en']!;
    return table[key] ?? values['en']![key] ?? key;
  }

  static String text(BuildContext context, String key) =>
      forLocale(Localizations.localeOf(context), key);
}
