import 'package:flutter/widgets.dart';

abstract final class PortsLocale {
  static const kartPadLaunchErrorKeys = <String, String>{
    'KARTPAD_CORE_NOT_READY': 'kartpadCorePending',
    'KARTPAD_CORE_LOAD_FAILED': 'kartpadLaunchFailed',
    'KARTPAD_ABI_MISMATCH': 'kartpadLaunchFailed',
    'KARTPAD_RUNTIME_PROFILE_MISMATCH': 'kartpadLaunchFailed',
    'KARTPAD_GAME_UNREADABLE': 'kartpadLaunchFailed',
    'KARTPAD_GAME_UNSUPPORTED': 'kartpadUnsupportedDisc',
    'KARTPAD_GAME_OUTSIDE_LIBRARY': 'kartpadUnsupportedDisc',
    'KARTPAD_SESSION_ACTIVE': 'kartpadBusy',
    'KARTPAD_RESTART_REQUIRED': 'kartpadRestartRequired',
    'KARTPAD_INITIALIZE_FAILED': 'kartpadLaunchFailed',
    'KARTPAD_HOST_VIEW_MISSING': 'kartpadLaunchFailed',
    'KARTPAD_START_FAILED': 'kartpadLaunchFailed',
    'KARTPAD_ENDED_BEFORE_FIRST_FRAME': 'kartpadLaunchFailed',
    'KARTPAD_FIRST_FRAME_TIMEOUT': 'kartpadLaunchFailed',
  };

  static const values = <String, Map<String, String>>{
    'en': {'import':'Import','dusklight':'DuskLight','kartpad':'Mario Kart Pad','kartpadImported':'Mario Kart Wii imported.','kartpadImportFailed':'Mario Kart Pad import failed. Check the file and available storage.','kartpadUnsupportedDisc':'Select a PAL Mario Kart Wii disc with ID RMCP01.','kartpadUnsupportedRevision':'Mario Kart Pad currently requires RMCP01, disc 0, revision 0.','kartpadFormatUnsupported':'KartPad accepts Mario Kart Wii as ISO, WBFS, or RVZ. Extracted DATA-folder import will be added separately.','kartpadCorePending':'The KartPad engine is not included in this NeoStation installation.','kartpadLaunchFailed':'Mario Kart Pad could not start. See the technical details.','kartpadBusy':'A Mario Kart Pad session is already running.','kartpadRestartRequired':'Mario Kart Pad encountered a terminal native error. Restart NeoStation before launching it again.','returnToLibrary':'Return to NeoStation','kartpadRvzPrepareFailed':'KartPad could not prepare this RVZ. Verify that it is Mario Kart Wii PAL RMCP01 revision 0.','settings':'KartPad Settings','gameLanguage':'Game Language','graphics':'Graphics','renderResolution':'Render Resolution','aspectRatio':'Aspect Ratio','aspectOriginal':'4:3','aspectWidescreen':'16:9','aspectFill':'Fill Screen','fpsCounter':'Show FPS Counter','settingsRestartHint':'Restart NeoStation to apply language and graphics changes.','languageEnglish':'English','languageGerman':'German','languageFrench':'French','languageSpanish':'Spanish','languageItalian':'Italian','languageDutch':'Dutch'},
    'fr': {'import':'Importer','dusklight':'DuskLight','kartpad':'Mario Kart Pad','kartpadImported':'Mario Kart Wii a été importé.','kartpadImportFailed':'Échec de l’import Mario Kart Pad. Vérifiez le fichier et l’espace disponible.','kartpadUnsupportedDisc':'Sélectionnez un disque PAL de Mario Kart Wii avec l’ID RMCP01.','kartpadUnsupportedRevision':'Mario Kart Pad requiert actuellement RMCP01, disque 0, révision 0.','kartpadFormatUnsupported':'KartPad accepte Mario Kart Wii au format ISO, WBFS ou RVZ. L’import d’un dossier DATA extrait sera ajouté séparément.','kartpadCorePending':'Le moteur KartPad n’est pas inclus dans cette installation de NeoStation.','kartpadLaunchFailed':'Mario Kart Pad n’a pas pu démarrer. Consultez les détails techniques.','kartpadBusy':'Une session Mario Kart Pad est déjà en cours.','kartpadRestartRequired':'Mario Kart Pad a rencontré une erreur native terminale. Redémarrez NeoStation avant de le relancer.','returnToLibrary':'Retour à NeoStation','kartpadRvzPrepareFailed':'KartPad n’a pas pu préparer ce RVZ. Vérifiez qu’il s’agit de Mario Kart Wii PAL RMCP01 révision 0.','settings':'Réglages KartPad','gameLanguage':'Langue du jeu','graphics':'Graphismes','renderResolution':'Résolution de rendu','aspectRatio':'Format d’image','aspectOriginal':'4:3','aspectWidescreen':'16:9','aspectFill':'Plein écran','fpsCounter':'Afficher les FPS','settingsRestartHint':'Redémarrez NeoStation pour appliquer les changements de langue et de graphismes.','languageEnglish':'Anglais','languageGerman':'Allemand','languageFrench':'Français','languageSpanish':'Espagnol','languageItalian':'Italien','languageDutch':'Néerlandais'},
    'es': {'import':'Importar','dusklight':'DuskLight','kartpad':'Mario Kart Pad','kartpadImported':'Mario Kart Wii importado.','kartpadImportFailed':'Error al importar Mario Kart Pad. Comprueba el archivo y el espacio disponible.','kartpadUnsupportedDisc':'Selecciona un disco PAL de Mario Kart Wii con ID RMCP01.','kartpadUnsupportedRevision':'Mario Kart Pad requiere RMCP01, disco 0, revisión 0.','kartpadFormatUnsupported':'KartPad acepta Mario Kart Wii en formato ISO, WBFS o RVZ. La importación de una carpeta DATA extraída se añadirá por separado.','kartpadCorePending':'El motor KartPad no está incluido en esta instalación de NeoStation.','kartpadLaunchFailed':'Mario Kart Pad no pudo iniciarse. Consulta los detalles técnicos.','kartpadBusy':'Ya hay una sesión de Mario Kart Pad en ejecución.','kartpadRestartRequired':'Mario Kart Pad encontró un error nativo terminal. Reinicia NeoStation antes de volver a iniciarlo.','returnToLibrary':'Volver a NeoStation','kartpadRvzPrepareFailed':'KartPad no pudo preparar este RVZ. Comprueba que sea Mario Kart Wii PAL RMCP01 revisión 0.','settings':'Ajustes de KartPad','gameLanguage':'Idioma del juego','graphics':'Gráficos','renderResolution':'Resolución de renderizado','aspectRatio':'Relación de aspecto','aspectOriginal':'4:3','aspectWidescreen':'16:9','aspectFill':'Llenar pantalla','fpsCounter':'Mostrar FPS','settingsRestartHint':'Reinicia NeoStation para aplicar los cambios de idioma y gráficos.','languageEnglish':'Inglés','languageGerman':'Alemán','languageFrench':'Francés','languageSpanish':'Español','languageItalian':'Italiano','languageDutch':'Neerlandés'},
    'pt': {'import':'Importar','dusklight':'DuskLight','kartpad':'Mario Kart Pad','kartpadImported':'Mario Kart Wii importado.','kartpadImportFailed':'Falha ao importar Mario Kart Pad. Verifique o arquivo e o espaço disponível.','kartpadUnsupportedDisc':'Selecione um disco PAL do Mario Kart Wii com ID RMCP01.','kartpadUnsupportedRevision':'Mario Kart Pad requer RMCP01, disco 0, revisão 0.','kartpadFormatUnsupported':'KartPad aceita Mario Kart Wii em ISO, WBFS ou RVZ. A importação de uma pasta DATA extraída será adicionada separadamente.','kartpadCorePending':'O motor KartPad não está incluído nesta instalação do NeoStation.','kartpadLaunchFailed':'Mario Kart Pad não pôde iniciar. Consulte os detalhes técnicos.','kartpadBusy':'Já existe uma sessão do Mario Kart Pad em execução.','kartpadRestartRequired':'Mario Kart Pad encontrou um erro nativo terminal. Reinicie o NeoStation antes de iniciá-lo novamente.','returnToLibrary':'Voltar ao NeoStation','kartpadRvzPrepareFailed':'KartPad não conseguiu preparar este RVZ. Verifique se é Mario Kart Wii PAL RMCP01 revisão 0.','settings':'Definições do KartPad','gameLanguage':'Idioma do jogo','graphics':'Gráficos','renderResolution':'Resolução de renderização','aspectRatio':'Proporção da tela','aspectOriginal':'4:3','aspectWidescreen':'16:9','aspectFill':'Preencher tela','fpsCounter':'Mostrar FPS','settingsRestartHint':'Reinicie o NeoStation para aplicar as alterações de idioma e gráficos.','languageEnglish':'Inglês','languageGerman':'Alemão','languageFrench':'Francês','languageSpanish':'Espanhol','languageItalian':'Italiano','languageDutch':'Neerlandês'},
    'de': {'import':'Importieren','dusklight':'DuskLight','kartpad':'Mario Kart Pad','kartpadImported':'Mario Kart Wii wurde importiert.','kartpadImportFailed':'Mario Kart Pad konnte nicht importiert werden. Prüfe Datei und freien Speicher.','kartpadUnsupportedDisc':'Wähle eine PAL-Mario-Kart-Wii-Disc mit der ID RMCP01.','kartpadUnsupportedRevision':'Mario Kart Pad benötigt derzeit RMCP01, Disc 0, Revision 0.','kartpadFormatUnsupported':'KartPad akzeptiert Mario Kart Wii als ISO, WBFS oder RVZ. Der Import eines extrahierten DATA-Ordners wird separat ergänzt.','kartpadCorePending':'Die KartPad-Engine ist in dieser NeoStation-Installation nicht enthalten.','kartpadLaunchFailed':'Mario Kart Pad konnte nicht gestartet werden. Siehe technische Details.','kartpadBusy':'Eine Mario-Kart-Pad-Sitzung läuft bereits.','kartpadRestartRequired':'Mario Kart Pad hat einen terminalen nativen Fehler festgestellt. Starte NeoStation neu, bevor du es erneut öffnest.','returnToLibrary':'Zurück zu NeoStation','kartpadRvzPrepareFailed':'KartPad konnte diese RVZ-Datei nicht vorbereiten. Prüfe, ob es Mario Kart Wii PAL RMCP01 Revision 0 ist.','settings':'KartPad-Einstellungen','gameLanguage':'Spielsprache','graphics':'Grafik','renderResolution':'Renderauflösung','aspectRatio':'Seitenverhältnis','aspectOriginal':'4:3','aspectWidescreen':'16:9','aspectFill':'Bildschirm füllen','fpsCounter':'FPS anzeigen','settingsRestartHint':'Starte NeoStation neu, um Sprach- und Grafikänderungen anzuwenden.','languageEnglish':'Englisch','languageGerman':'Deutsch','languageFrench':'Französisch','languageSpanish':'Spanisch','languageItalian':'Italienisch','languageDutch':'Niederländisch'},
    'it': {'import':'Importa','dusklight':'DuskLight','kartpad':'Mario Kart Pad','kartpadImported':'Mario Kart Wii importato.','kartpadImportFailed':'Importazione Mario Kart Pad non riuscita. Controlla il file e lo spazio disponibile.','kartpadUnsupportedDisc':'Seleziona un disco PAL di Mario Kart Wii con ID RMCP01.','kartpadUnsupportedRevision':'Mario Kart Pad richiede RMCP01, disco 0, revisione 0.','kartpadFormatUnsupported':'KartPad accetta Mario Kart Wii in formato ISO, WBFS o RVZ. L’importazione di una cartella DATA estratta verrà aggiunta separatamente.','kartpadCorePending':'Il motore KartPad non è incluso in questa installazione di NeoStation.','kartpadLaunchFailed':'Mario Kart Pad non è riuscito ad avviarsi. Consulta i dettagli tecnici.','kartpadBusy':'È già in esecuzione una sessione Mario Kart Pad.','kartpadRestartRequired':'Mario Kart Pad ha riscontrato un errore nativo terminale. Riavvia NeoStation prima di avviarlo di nuovo.','returnToLibrary':'Torna a NeoStation','kartpadRvzPrepareFailed':'KartPad non ha potuto preparare questo RVZ. Verifica che sia Mario Kart Wii PAL RMCP01 revisione 0.','settings':'Impostazioni KartPad','gameLanguage':'Lingua del gioco','graphics':'Grafica','renderResolution':'Risoluzione di rendering','aspectRatio':'Proporzioni','aspectOriginal':'4:3','aspectWidescreen':'16:9','aspectFill':'Riempi schermo','fpsCounter':'Mostra FPS','settingsRestartHint':'Riavvia NeoStation per applicare le modifiche a lingua e grafica.','languageEnglish':'Inglese','languageGerman':'Tedesco','languageFrench':'Francese','languageSpanish':'Spagnolo','languageItalian':'Italiano','languageDutch':'Olandese'},
    'ru': {'import':'Импорт','dusklight':'DuskLight','kartpad':'Mario Kart Pad','kartpadImported':'Mario Kart Wii импортирована.','kartpadImportFailed':'Не удалось импортировать Mario Kart Pad. Проверьте файл и свободное место.','kartpadUnsupportedDisc':'Выберите PAL-диск Mario Kart Wii с ID RMCP01.','kartpadUnsupportedRevision':'Mario Kart Pad требует RMCP01, диск 0, ревизия 0.','kartpadFormatUnsupported':'KartPad принимает Mario Kart Wii в ISO, WBFS или RVZ. Импорт распакованной папки DATA будет добавлен отдельно.','kartpadCorePending':'Движок KartPad не включён в эту установку NeoStation.','kartpadLaunchFailed':'Mario Kart Pad не удалось запустить. См. технические сведения.','kartpadBusy':'Сеанс Mario Kart Pad уже запущен.','kartpadRestartRequired':'Mario Kart Pad столкнулся с терминальной нативной ошибкой. Перезапустите NeoStation перед повторным запуском.','returnToLibrary':'Вернуться в NeoStation','kartpadRvzPrepareFailed':'KartPad не удалось подготовить RVZ. Убедитесь, что это Mario Kart Wii PAL RMCP01, ревизия 0.','settings':'Настройки KartPad','gameLanguage':'Язык игры','graphics':'Графика','renderResolution':'Разрешение рендеринга','aspectRatio':'Соотношение сторон','aspectOriginal':'4:3','aspectWidescreen':'16:9','aspectFill':'Заполнить экран','fpsCounter':'Показывать FPS','settingsRestartHint':'Перезапустите NeoStation, чтобы применить изменения языка и графики.','languageEnglish':'Английский','languageGerman':'Немецкий','languageFrench':'Французский','languageSpanish':'Испанский','languageItalian':'Итальянский','languageDutch':'Нидерландский'},
    'zh': {'import':'导入','dusklight':'DuskLight','kartpad':'Mario Kart Pad','kartpadImported':'已导入 Mario Kart Wii。','kartpadImportFailed':'Mario Kart Pad 导入失败。请检查文件和可用空间。','kartpadUnsupportedDisc':'请选择游戏 ID 为 RMCP01 的 PAL 版 Mario Kart Wii 光盘。','kartpadUnsupportedRevision':'Mario Kart Pad 当前要求 RMCP01、光盘 0、修订版 0。','kartpadFormatUnsupported':'KartPad 支持 ISO、WBFS 或 RVZ 格式的 Mario Kart Wii。解压后的 DATA 文件夹导入将另行加入。','kartpadCorePending':'此 NeoStation 安装中未包含 KartPad 引擎。','kartpadLaunchFailed':'Mario Kart Pad 无法启动。请查看技术详情。','kartpadBusy':'Mario Kart Pad 会话已在运行。','kartpadRestartRequired':'Mario Kart Pad 遇到终止性的原生错误。再次启动前请重新启动 NeoStation。','returnToLibrary':'返回 NeoStation','kartpadRvzPrepareFailed':'KartPad 无法准备此 RVZ。请确认它是 Mario Kart Wii PAL RMCP01 修订版 0。','settings':'KartPad 设置','gameLanguage':'游戏语言','graphics':'图形','renderResolution':'渲染分辨率','aspectRatio':'宽高比','aspectOriginal':'4:3','aspectWidescreen':'16:9','aspectFill':'填满屏幕','fpsCounter':'显示 FPS','settingsRestartHint':'重新启动 NeoStation 以应用语言和图形更改。','languageEnglish':'英语','languageGerman':'德语','languageFrench':'法语','languageSpanish':'西班牙语','languageItalian':'意大利语','languageDutch':'荷兰语'},
    'zh_Hant': {'import':'匯入','dusklight':'DuskLight','kartpad':'Mario Kart Pad','kartpadImported':'已匯入 Mario Kart Wii。','kartpadImportFailed':'Mario Kart Pad 匯入失敗。請檢查檔案與可用空間。','kartpadUnsupportedDisc':'請選擇遊戲 ID 為 RMCP01 的 PAL 版 Mario Kart Wii 光碟。','kartpadUnsupportedRevision':'Mario Kart Pad 目前需要 RMCP01、光碟 0、修訂版 0。','kartpadFormatUnsupported':'KartPad 支援 ISO、WBFS 或 RVZ 格式的 Mario Kart Wii。解壓後的 DATA 資料夾匯入將另行加入。','kartpadCorePending':'此 NeoStation 安裝中未包含 KartPad 引擎。','kartpadLaunchFailed':'Mario Kart Pad 無法啟動。請查看技術詳細資料。','kartpadBusy':'Mario Kart Pad 工作階段已在執行。','kartpadRestartRequired':'Mario Kart Pad 遇到終止性的原生錯誤。再次啟動前請重新啟動 NeoStation。','returnToLibrary':'返回 NeoStation','kartpadRvzPrepareFailed':'KartPad 無法準備此 RVZ。請確認它是 Mario Kart Wii PAL RMCP01 修訂版 0。','settings':'KartPad 設定','gameLanguage':'遊戲語言','graphics':'圖形','renderResolution':'渲染解析度','aspectRatio':'長寬比','aspectOriginal':'4:3','aspectWidescreen':'16:9','aspectFill':'填滿螢幕','fpsCounter':'顯示 FPS','settingsRestartHint':'重新啟動 NeoStation 以套用語言與圖形變更。','languageEnglish':'英文','languageGerman':'德文','languageFrench':'法文','languageSpanish':'西班牙文','languageItalian':'義大利文','languageDutch':'荷蘭文'},
    'id': {'import':'Impor','dusklight':'DuskLight','kartpad':'Mario Kart Pad','kartpadImported':'Mario Kart Wii berhasil diimpor.','kartpadImportFailed':'Impor Mario Kart Pad gagal. Periksa file dan ruang penyimpanan.','kartpadUnsupportedDisc':'Pilih disc PAL Mario Kart Wii dengan ID RMCP01.','kartpadUnsupportedRevision':'Mario Kart Pad saat ini memerlukan RMCP01, disc 0, revisi 0.','kartpadFormatUnsupported':'KartPad menerima Mario Kart Wii dalam format ISO, WBFS, atau RVZ. Impor folder DATA hasil ekstraksi akan ditambahkan terpisah.','kartpadCorePending':'Mesin KartPad tidak disertakan dalam instalasi NeoStation ini.','kartpadLaunchFailed':'Mario Kart Pad tidak dapat dimulai. Lihat detail teknis.','kartpadBusy':'Sesi Mario Kart Pad sudah berjalan.','kartpadRestartRequired':'Mario Kart Pad mengalami kesalahan native terminal. Mulai ulang NeoStation sebelum menjalankannya lagi.','returnToLibrary':'Kembali ke NeoStation','kartpadRvzPrepareFailed':'KartPad tidak dapat menyiapkan RVZ ini. Pastikan ini Mario Kart Wii PAL RMCP01 revisi 0.','settings':'Pengaturan KartPad','gameLanguage':'Bahasa Game','graphics':'Grafis','renderResolution':'Resolusi Render','aspectRatio':'Rasio Aspek','aspectOriginal':'4:3','aspectWidescreen':'16:9','aspectFill':'Penuhi Layar','fpsCounter':'Tampilkan FPS','settingsRestartHint':'Mulai ulang NeoStation untuk menerapkan perubahan bahasa dan grafis.','languageEnglish':'Inggris','languageGerman':'Jerman','languageFrench':'Prancis','languageSpanish':'Spanyol','languageItalian':'Italia','languageDutch':'Belanda'},
    'ja': {'import':'インポート','dusklight':'DuskLight','kartpad':'Mario Kart Pad','kartpadImported':'Mario Kart Wii をインポートしました。','kartpadImportFailed':'Mario Kart Pad のインポートに失敗しました。ファイルと空き容量を確認してください。','kartpadUnsupportedDisc':'ゲーム ID が RMCP01 の PAL 版 Mario Kart Wii ディスクを選択してください。','kartpadUnsupportedRevision':'Mario Kart Pad は現在 RMCP01、ディスク 0、リビジョン 0 が必要です。','kartpadFormatUnsupported':'KartPad は Mario Kart Wii の ISO、WBFS、RVZ を受け付けます。展開済み DATA フォルダーのインポートは別途追加されます。','kartpadCorePending':'この NeoStation インストールには KartPad エンジンが含まれていません。','kartpadLaunchFailed':'Mario Kart Pad を起動できませんでした。技術情報を確認してください。','kartpadBusy':'Mario Kart Pad のセッションはすでに実行中です。','kartpadRestartRequired':'Mario Kart Pad で致命的なネイティブエラーが発生しました。再起動する前に NeoStation を再起動してください。','returnToLibrary':'NeoStation に戻る','kartpadRvzPrepareFailed':'KartPad はこの RVZ を準備できませんでした。Mario Kart Wii PAL RMCP01 リビジョン 0 であることを確認してください。','settings':'KartPad 設定','gameLanguage':'ゲーム言語','graphics':'グラフィック','renderResolution':'レンダリング解像度','aspectRatio':'アスペクト比','aspectOriginal':'4:3','aspectWidescreen':'16:9','aspectFill':'画面に合わせる','fpsCounter':'FPS を表示','settingsRestartHint':'言語とグラフィックの変更を適用するには NeoStation を再起動してください。','languageEnglish':'英語','languageGerman':'ドイツ語','languageFrench':'フランス語','languageSpanish':'スペイン語','languageItalian':'イタリア語','languageDutch':'オランダ語'},
    'ko': {'import':'가져오기','dusklight':'DuskLight','kartpad':'Mario Kart Pad','kartpadImported':'Mario Kart Wii를 가져왔습니다.','kartpadImportFailed':'Mario Kart Pad 가져오기에 실패했습니다. 파일과 저장 공간을 확인하세요.','kartpadUnsupportedDisc':'게임 ID가 RMCP01인 PAL Mario Kart Wii 디스크를 선택하세요.','kartpadUnsupportedRevision':'Mario Kart Pad는 현재 RMCP01, 디스크 0, 리비전 0이 필요합니다.','kartpadFormatUnsupported':'KartPad는 Mario Kart Wii ISO, WBFS 또는 RVZ를 지원합니다. 추출된 DATA 폴더 가져오기는 별도로 추가됩니다.','kartpadCorePending':'이 NeoStation 설치에는 KartPad 엔진이 포함되어 있지 않습니다.','kartpadLaunchFailed':'Mario Kart Pad를 시작할 수 없습니다. 기술 세부 정보를 확인하세요.','kartpadBusy':'Mario Kart Pad 세션이 이미 실행 중입니다.','kartpadRestartRequired':'Mario Kart Pad에 치명적인 네이티브 오류가 발생했습니다. 다시 실행하기 전에 NeoStation을 재시작하세요.','returnToLibrary':'NeoStation으로 돌아가기','kartpadRvzPrepareFailed':'KartPad가 이 RVZ를 준비하지 못했습니다. Mario Kart Wii PAL RMCP01 리비전 0인지 확인하세요.','settings':'KartPad 설정','gameLanguage':'게임 언어','graphics':'그래픽','renderResolution':'렌더링 해상도','aspectRatio':'화면 비율','aspectOriginal':'4:3','aspectWidescreen':'16:9','aspectFill':'화면 채우기','fpsCounter':'FPS 표시','settingsRestartHint':'언어 및 그래픽 변경 사항을 적용하려면 NeoStation을 다시 시작하세요.','languageEnglish':'영어','languageGerman':'독일어','languageFrench':'프랑스어','languageSpanish':'스페인어','languageItalian':'이탈리아어','languageDutch':'네덜란드어'},
  };

  static String localeKey(Locale locale) => locale.languageCode == 'zh' &&
          (locale.scriptCode?.toLowerCase() == 'hant' ||
              ['TW', 'HK', 'MO'].contains(locale.countryCode?.toUpperCase()))
      ? 'zh_Hant'
      : locale.languageCode;

  static String forLocale(Locale locale, String key) {
    final table = values[localeKey(locale)] ?? values['en']!;
    return table[key] ?? values['en']![key] ?? key;
  }

  static String text(BuildContext context, String key) =>
      forLocale(Localizations.localeOf(context), key);

  static String kartPadLaunchError(Locale locale, String? errorCode) =>
      forLocale(
        locale,
        kartPadLaunchErrorKeys[errorCode] ?? 'kartpadLaunchFailed',
      );

  static Map<String, String> kartPadNativeUI(Locale locale) =>
      <String, String>{
        for (final key in <String>[
          'returnToLibrary',
          'settings',
          'gameLanguage',
          'graphics',
          'renderResolution',
          'aspectRatio',
          'aspectOriginal',
          'aspectWidescreen',
          'aspectFill',
          'fpsCounter',
          'settingsRestartHint',
          'languageEnglish',
          'languageGerman',
          'languageFrench',
          'languageSpanish',
          'languageItalian',
          'languageDutch',
        ])
          key: forLocale(locale, key),
      };
}
